package com.ritvyom.yashoraReelgenerator.presentation.utils

/**
 * High-fidelity translation dictionaries for Global languages (Asian, Middle Eastern, and African).
 * Covers full UI strings across Yashora Reel Generator.
 */
object LocalizationGlobal {

    val ARABIC_MAP = mapOf(
        "Yashora" to "ياشورا",
        "AI REEL GENERATOR" to "مُولّد ريلز بالذكاء الاصطناعي",
        "REEL GENERATOR" to "مولد ريلز",
        "Home" to "الرئيسية",
        "AI Tools" to "أدوات الذكاء الاصطناعي",
        "AI Chat" to "دردشة الذكاء الاصطناعي",
        "My Library" to "مكتبتي",
        "Projects" to "المشاريع",
        "Saved Scripts" to "النصوص المحفوظة",
        "Export History" to "سجل التصدير",
        "Templates" to "القوالب",
        "Premium" to "بريميوم",
        "Settings" to "الإعدادات",
        "App Settings" to "إعدادات التطبيق",
        "Back" to "رجوع",
        "Preferences" to "التفضيلات",
        "App Theme" to "مظهر التطبيق",
        "App Interface Language" to "لغة واجهة التطبيق",
        "AI Video Generation Language" to "لغة إنشاء الفيديو",
        "Voice Engine & ElevenLabs (VoxEleven)" to "محرك الصوت وElevenLabs",
        "AI Smart Source Matchmaker" to "مطابق المصادر الذكي",
        "Storage & Local Cache" to "التخزين والذاكرة المؤقتة",
        "Clear Local Cache & Storage" to "مسح الذاكرة المؤقتة والتخزين",
        "Legal & About" to "قانوني ومعلومات",
        "Privacy Policy" to "سياسة الخصوصية",
        "Terms & Conditions" to "الشروط والأحكام",
        "About Yashora Reel Generator" to "حول ياشورا",
        "Recent Projects" to "المشاريع الأخيرة",
        "Create Reel" to "إنشاء ريل",
        "Create New Reel" to "إنشاء ريل جديد",
        "AI Reel Architect" to "مهندس الريلز الذكي",
        "AI Script Writer" to "كاتب النصوص الذكي",
        "VoxEleven Voice" to "صوت VoxEleven",
        "Edit" to "تعديل",
        "Edit Studio" to "استوديو التحرير",
        "Manual Studio" to "الاستوديو اليدوي",
        "Learn How It Works" to "كيف يعمل التطبيق",
        "Got It!" to "فهمت ذلك!",
        "Write / Paste Reel Script" to "اكتب أو الصق النص هنا",
        "Generate with AI" to "إنشاء بالذكاء الاصطناعي",
        "Speech & Video Language" to "لغة الصوت والفيديو",
        "Primary Narrator Voice" to "صوت الراوي الرئيسي",
        "Selected: " to "المحدد: ",
        "Selected" to "محدد",
        "Male" to "صوت رجالي",
        "Female" to "صوت نسائي",
        "Child" to "صوت طفل",
        "Speech Speed: " to "سرعة الكلام: ",
        "Speech Pitch: " to "طبقة الصوت: ",
        "Preview Voice" to "استمع للصوت",
        "Resolution" to "الدقة",
        "Background Soundtrack Overlay" to "الموسيقى التصويرية",
        "Generate Video" to "إنشاء الفيديو",
        "Skip & Generate Video" to "تخطي وإنشاء الفيديو",
        "Visual Timeline Editor" to "محرر المخطط الزمني",
        "Export" to "تصدير",
        "Scene Canvas" to "لوحة المشهد",
        "Add Clip" to "إضافة مقطع",
        "Subtitles" to "الترجمة والنصوص",
        "50+ Filters" to "أكثر من 50 فلتر",
        "Delete" to "حذف",
        "Cancel" to "إلغاء",
        "Save" to "حفظ",
        "Copy" to "نسخ",
        "Done" to "تم",
        "Yes" to "نعم",
        "No" to "لا",
        "Share" to "مشاركة",
        "Share Reel" to "مشاركة الريل",
        "Search..." to "بحث...",
        "Search" to "بحث",
        "Clear" to "مسح",
        "Loading..." to "جارٍ التحميل...",
        "All Languages" to "جميع اللغات",
        "Popular ⭐" to "شائع ⭐",
        "Indian Languages 🇮🇳" to "لغات هندية 🇮🇳",
        "Global 🌐" to "لغات عالمية 🌐",
        "Select Language" to "اختر اللغة",
        "Clear Cache" to "مسح الذاكرة المؤقتة",
        "Sign Out" to "تسجيل الخروج",
        "Open in Studio" to "فتح في الاستوديو",
        "Use Template" to "استخدام القالب"
    )

    val PERSIAN_MAP = mapOf(
        "Yashora" to "یاشورا",
        "AI REEL GENERATOR" to "سازنده ریلز هوش مصنوعی",
        "REEL GENERATOR" to "سازنده ریلز",
        "Home" to "خانه",
        "AI Tools" to "ابزارهای هوش مصنوعی",
        "AI Chat" to "چت هوش مصنوعی",
        "My Library" to "کتابخانه من",
        "Projects" to "پروژه‌ها",
        "Saved Scripts" to "فیلم‌نامه‌های ذخیره‌شده",
        "Export History" to "تاریخچه خروجی‌ها",
        "Templates" to "قالب‌ها",
        "Premium" to "پریمیوم",
        "Settings" to "تنظیمات",
        "App Settings" to "تنظیمات برنامه",
        "Back" to "بازگشت",
        "Preferences" to "ترجیحات",
        "App Theme" to "پوسته برنامه",
        "App Interface Language" to "زبان رابط کاربری",
        "AI Video Generation Language" to "زبان تولید ویدیو",
        "Storage & Local Cache" to "حافظه و کش",
        "Clear Local Cache & Storage" to "پاکسازی حافظه پنهان",
        "Recent Projects" to "پروژه‌های اخیر",
        "Create Reel" to "ایجاد ریلز",
        "Create New Reel" to "ایجاد ریلز جدید",
        "AI Reel Architect" to "معمار ریلز هوش مصنوعی",
        "Edit" to "ویرایش",
        "Learn How It Works" to "نحوه کارکرد",
        "Got It!" to "متوجه شدم!",
        "Generate with AI" to "تولید با هوش مصنوعی",
        "Speech & Video Language" to "زبان صدا و ویدیو",
        "Primary Narrator Voice" to "صدای راوی اصلی",
        "Selected: " to "انتخاب‌شده: ",
        "Selected" to "انتخاب‌شده",
        "Male" to "مرد",
        "Female" to "زن",
        "Child" to "کودک",
        "Speech Speed: " to "سرعت گفتار: ",
        "Speech Pitch: " to "زیروبمی صدا: ",
        "Preview Voice" to "پیش‌شنیدن صدا",
        "Resolution" to "رزولوشن",
        "Background Soundtrack Overlay" to "موسیقی پس‌زمینه",
        "Generate Video" to "تولید ویدیو",
        "Skip & Generate Video" to "رد شدن و تولید ویدیو",
        "Visual Timeline Editor" to "ویرایشگر تایم‌لاین",
        "Export" to "خروجی گرفتن",
        "Scene Canvas" to "بوم صحنه",
        "Add Clip" to "افزودن کلیپ",
        "Subtitles" to "زیرنویس",
        "50+ Filters" to "بیش از ۵۰ فیلتر",
        "Delete" to "حذف",
        "Cancel" to "لغو",
        "Save" to "ذخیره",
        "Copy" to "کپی",
        "Done" to "انجام شد",
        "Yes" to "بله",
        "No" to "خیر",
        "Share" to "اشتراک‌گذاری",
        "Share Reel" to "اشتراک‌گذاری ریلز",
        "Search..." to "جستجو...",
        "Search" to "جستجو",
        "Clear" to "پاک کردن",
        "Loading..." to "در حال بارگذاری...",
        "All Languages" to "همه زبان‌ها",
        "Popular ⭐" to "محبوب ⭐",
        "Indian Languages 🇮🇳" to "زبان‌های هندی 🇮🇳",
        "Global 🌐" to "زبان‌های جهانی 🌐",
        "Select Language" to "انتخاب زبان",
        "Clear Cache" to "پاکسازی حافظه پنهان",
        "Sign Out" to "خروج از حساب",
        "Open in Studio" to "باز کردن در استودیو",
        "Use Template" to "استفاده از قالب"
    )

    val HEBREW_MAP = mapOf(
        "Yashora" to "יאשורה",
        "AI REEL GENERATOR" to "מחולל סרטוני רילס AI",
        "REEL GENERATOR" to "מחולל רילס",
        "Home" to "בית",
        "AI Tools" to "כלי AI",
        "AI Chat" to "צ'אט AI",
        "My Library" to "הספרייה שלי",
        "Projects" to "פרויקטים",
        "Saved Scripts" to "תסריטים שמורים",
        "Export History" to "היסטוריית ייצוא",
        "Templates" to "תבניות",
        "Premium" to "פרימיום",
        "Settings" to "הגדרות",
        "App Settings" to "הגדרות יישום",
        "Back" to "חזור",
        "Preferences" to "העדפות",
        "App Theme" to "עיצוב היישום",
        "App Interface Language" to "שפת ממשק",
        "AI Video Generation Language" to "שפת יצירת וידאו",
        "Storage & Local Cache" to "אחסון ומטמון",
        "Clear Local Cache & Storage" to "נקה זיכרון מטמון",
        "Recent Projects" to "פרויקטים אחרונים",
        "Create Reel" to "צור ריל",
        "Create New Reel" to "צור ריל חדש",
        "AI Reel Architect" to "אדריכל רילס AI",
        "Edit" to "ערוך",
        "Learn How It Works" to "איך זה עובד",
        "Got It!" to "הבנתי!",
        "Generate with AI" to "צור באמצעות AI",
        "Speech & Video Language" to "שפת דיבור ווידאו",
        "Primary Narrator Voice" to "קול קריין ראשי",
        "Selected: " to "נבחר: ",
        "Selected" to "נבחר",
        "Male" to "גבר",
        "Female" to "אישה",
        "Child" to "ילד",
        "Speech Speed: " to "מהירות דיבור: ",
        "Speech Pitch: " to "גובה צליל: ",
        "Preview Voice" to "השמע קול",
        "Resolution" to "רזולוציה",
        "Background Soundtrack Overlay" to "מוזיקת רקע",
        "Generate Video" to "צור וידאו",
        "Skip & Generate Video" to "דלג וצור וידאו",
        "Visual Timeline Editor" to "עורך ציר זמן",
        "Export" to "ייצא",
        "Scene Canvas" to "קנבס סצנה",
        "Add Clip" to "הוסף קליפ",
        "Subtitles" to "כתוביות",
        "50+ Filters" to "50+ מסננים",
        "Delete" to "מחק",
        "Cancel" to "ביטול",
        "Save" to "שמור",
        "Copy" to "העתק",
        "Done" to "בוצע",
        "Yes" to "כן",
        "No" to "לא",
        "Share" to "שתף",
        "Share Reel" to "שתף ריל",
        "Search..." to "חיפוש...",
        "Search" to "חפש",
        "Clear" to "נקה",
        "Loading..." to "טוען...",
        "All Languages" to "כל השפות",
        "Popular ⭐" to "פופולרי ⭐",
        "Indian Languages 🇮🇳" to "שפות הודיות 🇮🇳",
        "Global 🌐" to "שפות גלובליות 🌐",
        "Select Language" to "בחר שפה",
        "Clear Cache" to "נקה מטמון",
        "Sign Out" to "התנתק",
        "Open in Studio" to "פתח בסטודיו",
        "Use Template" to "השתמש בתבנית"
    )

    val TURKISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "YAPAY ZEKA REEL ÜRETİCİ",
        "REEL GENERATOR" to "Reel Üretici",
        "Home" to "Ana Sayfa",
        "AI Tools" to "Yapay Zeka Araçları",
        "AI Chat" to "YZ Sohbet",
        "My Library" to "Kütüphanem",
        "Projects" to "Projeler",
        "Saved Scripts" to "Kayıtlı Senaryolar",
        "Export History" to "Dışa Aktarma Geçmişi",
        "Templates" to "Şablonlar",
        "Premium" to "Premium",
        "Settings" to "Ayarlar",
        "App Settings" to "Uygulama Ayarları",
        "Back" to "Geri",
        "Preferences" to "Tercihler",
        "App Theme" to "Uygulama Teması",
        "App Interface Language" to "Arayüz Dili",
        "AI Video Generation Language" to "Video Üretim Dili",
        "Storage & Local Cache" to "Depolama ve Önbellek",
        "Clear Local Cache & Storage" to "Önbelleği ve Depolamayı Temizle",
        "Recent Projects" to "Son Projeler",
        "Create Reel" to "Reel Oluştur",
        "Create New Reel" to "Yeni Reel Oluştur",
        "AI Reel Architect" to "YZ Reel Mimarı",
        "AI Script Writer" to "YZ Senaryo Yazarı",
        "Edit" to "Düzenle",
        "Learn How It Works" to "Nasıl Çalışır",
        "Got It!" to "Anladım!",
        "Write / Paste Reel Script" to "Senaryo Yaz veya Yapıştır",
        "Generate with AI" to "YZ ile Oluştur",
        "Speech & Video Language" to "Ses ve Video Dili",
        "Primary Narrator Voice" to "Ana Anlatıcı Sesi",
        "Selected: " to "Seçilen: ",
        "Selected" to "Seçildi",
        "Male" to "Erkek",
        "Female" to "Kadın",
        "Child" to "Çocuk",
        "Speech Speed: " to "Konuşma Hızı: ",
        "Speech Pitch: " to "Ses Tonu: ",
        "Preview Voice" to "Sesi Dinle",
        "Resolution" to "Çözünürlük",
        "Background Soundtrack Overlay" to "Arka Plan Müziği",
        "Generate Video" to "Video Oluştur",
        "Skip & Generate Video" to "Geç ve Video Oluştur",
        "Visual Timeline Editor" to "Zaman Çizelgesi Düzenleyici",
        "Export" to "Dışa Aktar",
        "Scene Canvas" to "Sahne Tuvali",
        "Add Clip" to "Klip Ekle",
        "Subtitles" to "Altyazılar",
        "50+ Filters" to "50+ Filtre",
        "Delete" to "Sil",
        "Cancel" to "İptal",
        "Save" to "Kaydet",
        "Copy" to "Kopyala",
        "Done" to "Tamamlandı",
        "Yes" to "Evet",
        "No" to "Hayır",
        "Share" to "Paylaş",
        "Share Reel" to "Reel Paylaş",
        "Search..." to "Ara...",
        "Search" to "Ara",
        "Clear" to "Temizle",
        "Loading..." to "Yükleniyor...",
        "All Languages" to "Tüm Diller",
        "Popular ⭐" to "Popüler ⭐",
        "Indian Languages 🇮🇳" to "Hint Dilleri 🇮🇳",
        "Global 🌐" to "Küresel Diller 🌐",
        "Select Language" to "Dil Seçin",
        "Clear Cache" to "Önbelleği Temizle",
        "Sign Out" to "Çıkış Yap",
        "Open in Studio" to "Studio'da Aç",
        "Use Template" to "Şablonu Kullan"
    )

    val CHINESE_SIMPLIFIED_MAP = mapOf(
        "Yashora" to "雅硕拉",
        "AI REEL GENERATOR" to "AI 短视频生成器",
        "REEL GENERATOR" to "短视频生成器",
        "Home" to "首页",
        "AI Tools" to "AI 工具",
        "AI Chat" to "AI 对话",
        "My Library" to "我的素材库",
        "Projects" to "项目",
        "Saved Scripts" to "已存文案",
        "Export History" to "导出历史",
        "Templates" to "模板",
        "Premium" to "高级版",
        "Settings" to "设置",
        "App Settings" to "应用设置",
        "Back" to "返回",
        "Preferences" to "偏好设置",
        "App Theme" to "应用主题",
        "App Interface Language" to "界面语言",
        "AI Video Generation Language" to "视频生成语言",
        "Voice Engine & ElevenLabs (VoxEleven)" to "语音引擎与 ElevenLabs",
        "Storage & Local Cache" to "存储与本地缓存",
        "Clear Local Cache & Storage" to "清理缓存与存储",
        "Recent Projects" to "最近项目",
        "Create Reel" to "制作短视频",
        "Create New Reel" to "新建短视频",
        "AI Reel Architect" to "AI 视频架构师",
        "AI Script Writer" to "AI 剧本作家",
        "Edit" to "编辑",
        "Learn How It Works" to "了解工作原理",
        "Got It!" to "明白！",
        "Write / Paste Reel Script" to "编写或粘贴文案",
        "Generate with AI" to "AI 一键生成",
        "Speech & Video Language" to "配音与视频语言",
        "Primary Narrator Voice" to "主讲人音色",
        "Selected: " to "已选择：",
        "Selected" to "已选",
        "Male" to "男声",
        "Female" to "女声",
        "Child" to "童声",
        "Speech Speed: " to "语速：",
        "Speech Pitch: " to "音调：",
        "Preview Voice" to "试听声音",
        "Resolution" to "分辨率",
        "Background Soundtrack Overlay" to "背景音乐",
        "Generate Video" to "合成视频",
        "Skip & Generate Video" to "跳过并合成视频",
        "Visual Timeline Editor" to "时间轴编辑器",
        "Export" to "导出",
        "Scene Canvas" to "场景画布",
        "Add Clip" to "添加素材",
        "Subtitles" to "字幕",
        "50+ Filters" to "50+ 滤镜",
        "Delete" to "删除",
        "Cancel" to "取消",
        "Save" to "保存",
        "Copy" to "复制",
        "Done" to "完成",
        "Yes" to "是",
        "No" to "否",
        "Share" to "分享",
        "Share Reel" to "分享短视频",
        "Search..." to "搜索...",
        "Search" to "搜索",
        "Clear" to "清除",
        "Loading..." to "加载中...",
        "All Languages" to "所有语言",
        "Popular ⭐" to "热门 ⭐",
        "Indian Languages 🇮🇳" to "印度语系 🇮🇳",
        "Global 🌐" to "全球语言 🌐",
        "Select Language" to "选择语言",
        "Clear Cache" to "清理缓存",
        "Sign Out" to "退出登录",
        "Open in Studio" to "在工作室中打开",
        "Use Template" to "使用模板"
    )

    val CHINESE_TRADITIONAL_MAP = mapOf(
        "Yashora" to "雅碩拉",
        "AI REEL GENERATOR" to "AI 短影音生成器",
        "REEL GENERATOR" to "短影音生成器",
        "Home" to "首頁",
        "AI Tools" to "AI 工具",
        "AI Chat" to "AI 對話",
        "My Library" to "我的素材庫",
        "Projects" to "專案",
        "Saved Scripts" to "已儲存文案",
        "Export History" to "匯出歷史",
        "Templates" to "範本",
        "Premium" to "高級版",
        "Settings" to "設定",
        "App Settings" to "應用程式設定",
        "Back" to "返回",
        "Preferences" to "偏好設定",
        "App Theme" to "應用程式主題",
        "App Interface Language" to "介面語言",
        "AI Video Generation Language" to "影片生成語言",
        "Storage & Local Cache" to "儲存空間與快取",
        "Clear Local Cache & Storage" to "清理快取與儲存空間",
        "Recent Projects" to "最近專案",
        "Create Reel" to "製作短影音",
        "Create New Reel" to "新建短影音",
        "AI Reel Architect" to "AI 影片架構師",
        "Edit" to "編輯",
        "Learn How It Works" to "了解運作方式",
        "Got It!" to "明白！",
        "Generate with AI" to "AI 一鍵生成",
        "Speech & Video Language" to "語音與影片語言",
        "Primary Narrator Voice" to "主講人聲音",
        "Selected: " to "已選擇：",
        "Selected" to "已選",
        "Male" to "男聲",
        "Female" to "女聲",
        "Child" to "童聲",
        "Speech Speed: " to "語速：",
        "Speech Pitch: " to "音調：",
        "Preview Voice" to "試聽聲音",
        "Resolution" to "解析度",
        "Background Soundtrack Overlay" to "背景音樂",
        "Generate Video" to "合成影片",
        "Skip & Generate Video" to "略過並合成影片",
        "Visual Timeline Editor" to "時間軸編輯器",
        "Export" to "匯出",
        "Scene Canvas" to "場景畫布",
        "Add Clip" to "添加素材",
        "Subtitles" to "字幕",
        "50+ Filters" to "50+ 濾鏡",
        "Delete" to "刪除",
        "Cancel" to "取消",
        "Save" to "儲存",
        "Copy" to "複製",
        "Done" to "完成",
        "Yes" to "是",
        "No" to "否",
        "Share" to "分享",
        "Share Reel" to "分享短影音",
        "Search..." to "搜尋...",
        "Search" to "搜尋",
        "Clear" to "清除",
        "Loading..." to "載入中...",
        "All Languages" to "所有語言",
        "Popular ⭐" to "熱門 ⭐",
        "Indian Languages 🇮🇳" to "印度語言 🇮🇳",
        "Global 🌐" to "全球語言 🌐",
        "Select Language" to "選擇語言",
        "Clear Cache" to "清理快取",
        "Sign Out" to "登出",
        "Open in Studio" to "在工作室開啟",
        "Use Template" to "使用範本"
    )

    val JAPANESE_MAP = mapOf(
        "Yashora" to "ヤショラ",
        "AI REEL GENERATOR" to "AIリール動画ジェネレーター",
        "REEL GENERATOR" to "リールジェネレーター",
        "Home" to "ホーム",
        "AI Tools" to "AIツール",
        "AI Chat" to "AIチャット",
        "My Library" to "マイライブラリ",
        "Projects" to "プロジェクト",
        "Saved Scripts" to "保存された台本",
        "Export History" to "エクスポート履歴",
        "Templates" to "テンプレート",
        "Premium" to "プレミアム",
        "Settings" to "設定",
        "App Settings" to "アプリ設定",
        "Back" to "戻る",
        "Preferences" to "環境設定",
        "App Theme" to "アプリテーマ",
        "App Interface Language" to "UI言語",
        "AI Video Generation Language" to "動画生成言語",
        "Voice Engine & ElevenLabs (VoxEleven)" to "音声エンジン & ElevenLabs",
        "Storage & Local Cache" to "ストレージとキャッシュ",
        "Clear Local Cache & Storage" to "キャッシュとデータを削除",
        "Recent Projects" to "最近のプロジェクト",
        "Create Reel" to "リールを作成",
        "Create New Reel" to "新規リール作成",
        "AI Reel Architect" to "AIリールアーキテクト",
        "AI Script Writer" to "AI脚本ライター",
        "Edit" to "編集",
        "Learn How It Works" to "使い方を見る",
        "Got It!" to "了解！",
        "Write / Paste Reel Script" to "台本を入力または貼り付け",
        "Generate with AI" to "AIで自動生成",
        "Speech & Video Language" to "音声と動画の言語",
        "Primary Narrator Voice" to "メインナレーター音声",
        "Selected: " to "選択中: ",
        "Selected" to "選択済み",
        "Male" to "男性",
        "Female" to "女性",
        "Child" to "子供",
        "Speech Speed: " to "話速: ",
        "Speech Pitch: " to "音程: ",
        "Preview Voice" to "音声を試聴",
        "Resolution" to "解像度",
        "Background Soundtrack Overlay" to "BGM音源",
        "Generate Video" to "動画を生成",
        "Skip & Generate Video" to "スキップして生成",
        "Visual Timeline Editor" to "タイムライン編集",
        "Export" to "エクスポート",
        "Scene Canvas" to "シーンキャンバス",
        "Add Clip" to "クリップ追加",
        "Subtitles" to "字幕",
        "50+ Filters" to "50種以上のフィルター",
        "Delete" to "削除",
        "Cancel" to "キャンセル",
        "Save" to "保存",
        "Copy" to "コピー",
        "Done" to "完了",
        "Yes" to "はい",
        "No" to "いいえ",
        "Share" to "共有",
        "Share Reel" to "リールを共有",
        "Search..." to "検索...",
        "Search" to "検索",
        "Clear" to "クリア",
        "Loading..." to "読み込み中...",
        "All Languages" to "すべての言語",
        "Popular ⭐" to "人気 ⭐",
        "Indian Languages 🇮🇳" to "インド系言語 🇮🇳",
        "Global 🌐" to "世界言語 🌐",
        "Select Language" to "言語を選択",
        "Clear Cache" to "キャッシュを削除",
        "Sign Out" to "ログアウト",
        "Open in Studio" to "スタジオで開く",
        "Use Template" to "テンプレートを使用"
    )

    val KOREAN_MAP = mapOf(
        "Yashora" to "야쇼라",
        "AI REEL GENERATOR" to "AI 릴스 생성기",
        "REEL GENERATOR" to "릴스 생성기",
        "Home" to "홈",
        "AI Tools" to "AI 도구",
        "AI Chat" to "AI 챗",
        "My Library" to "내 보관함",
        "Projects" to "프로젝트",
        "Saved Scripts" to "저장된 대본",
        "Export History" to "내보내기 기록",
        "Templates" to "템플릿",
        "Premium" to "프리미엄",
        "Settings" to "설정",
        "App Settings" to "앱 설정",
        "Back" to "뒤로",
        "Preferences" to "기본 설정",
        "App Theme" to "앱 테마",
        "App Interface Language" to "앱 언어",
        "AI Video Generation Language" to "영상 생성 언어",
        "Storage & Local Cache" to "저장소 및 캐시",
        "Clear Local Cache & Storage" to "캐시 및 데이터 지우기",
        "Recent Projects" to "최근 프로젝트",
        "Create Reel" to "릴스 만들기",
        "Create New Reel" to "새 릴스 생성",
        "AI Reel Architect" to "AI 릴스 아키텍트",
        "AI Script Writer" to "AI 대본 작가",
        "Edit" to "편집",
        "Learn How It Works" to "사용 방법 알아보기",
        "Got It!" to "확인!",
        "Write / Paste Reel Script" to "대본 작성 또는 붙여넣기",
        "Generate with AI" to "AI로 생성하기",
        "Speech & Video Language" to "음성 및 영상 언어",
        "Primary Narrator Voice" to "주요 내레이터 음성",
        "Selected: " to "선택됨: ",
        "Selected" to "선택됨",
        "Male" to "남성",
        "Female" to "여성",
        "Child" to "어린이",
        "Speech Speed: " to "말하기 속도: ",
        "Speech Pitch: " to "음조: ",
        "Preview Voice" to "음성 미리듣기",
        "Resolution" to "해상도",
        "Background Soundtrack Overlay" to "배경 음악",
        "Generate Video" to "영상 생성",
        "Skip & Generate Video" to "건너뛰고 바로 생성",
        "Visual Timeline Editor" to "타임라인 편집기",
        "Export" to "내보내기",
        "Scene Canvas" to "장면 캔버스",
        "Add Clip" to "클립 추가",
        "Subtitles" to "자막",
        "50+ Filters" to "50+ 필터",
        "Delete" to "삭제",
        "Cancel" to "취소",
        "Save" to "저장",
        "Copy" to "복사",
        "Done" to "완료",
        "Yes" to "예",
        "No" to "아니요",
        "Share" to "공유",
        "Share Reel" to "릴스 공유",
        "Search..." to "검색...",
        "Search" to "검색",
        "Clear" to "지우기",
        "Loading..." to "로딩 중...",
        "All Languages" to "모든 언어",
        "Popular ⭐" to "인기 ⭐",
        "Indian Languages 🇮🇳" to "인도 언어 🇮🇳",
        "Global 🌐" to "글로벌 언어 🌐",
        "Select Language" to "언어 선택",
        "Clear Cache" to "캐시 지우기",
        "Sign Out" to "로그아웃",
        "Open in Studio" to "스튜디오에서 열기",
        "Use Template" to "템플릿 사용"
    )

    val INDONESIAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GENERATOR REEL AI",
        "REEL GENERATOR" to "Generator Reel",
        "Home" to "Beranda",
        "AI Tools" to "Alat AI",
        "AI Chat" to "Chat AI",
        "My Library" to "Pustaka Saya",
        "Projects" to "Proyek",
        "Saved Scripts" to "Naskah Tersimpan",
        "Export History" to "Riwayat Ekspor",
        "Templates" to "Templat",
        "Premium" to "Premium",
        "Settings" to "Pengaturan",
        "App Settings" to "Pengaturan Aplikasi",
        "Back" to "Kembali",
        "Preferences" to "Preferensi",
        "App Theme" to "Tema Aplikasi",
        "App Interface Language" to "Bahasa Antarmuka",
        "AI Video Generation Language" to "Bahasa Pembuatan Video",
        "Storage & Local Cache" to "Penyimpanan & Cache",
        "Clear Local Cache & Storage" to "Hapus Cache & Data",
        "Recent Projects" to "Proyek Terbaru",
        "Create Reel" to "Buat Reel",
        "Create New Reel" to "Buat Reel Baru",
        "AI Reel Architect" to "Arsitek Reel AI",
        "Edit" to "Edit",
        "Learn How It Works" to "Cara Kerja",
        "Got It!" to "Paham!",
        "Generate with AI" to "Buat dengan AI",
        "Speech & Video Language" to "Bahasa Suara & Video",
        "Primary Narrator Voice" to "Suara Narator Utama",
        "Selected: " to "Dipilih: ",
        "Selected" to "Dipilih",
        "Male" to "Pria",
        "Female" to "Wanita",
        "Child" to "Anak-anak",
        "Speech Speed: " to "Kecepatan Suara: ",
        "Speech Pitch: " to "Nada Suara: ",
        "Preview Voice" to "Dengarkan Suara",
        "Resolution" to "Resolusi",
        "Background Soundtrack Overlay" to "Musik Latar",
        "Generate Video" to "Buat Video",
        "Skip & Generate Video" to "Lewati & Buat Video",
        "Visual Timeline Editor" to "Editor Timeline",
        "Export" to "Ekspor",
        "Scene Canvas" to "Kanvas Adegan",
        "Add Clip" to "Tambah Klip",
        "Subtitles" to "Subtitel",
        "50+ Filters" to "50+ Filter",
        "Delete" to "Hapus",
        "Cancel" to "Batal",
        "Save" to "Simpan",
        "Copy" to "Salin",
        "Done" to "Selesai",
        "Yes" to "Ya",
        "No" to "Tidak",
        "Share" to "Bagikan",
        "Share Reel" to "Bagikan Reel",
        "Search..." to "Cari...",
        "Search" to "Cari",
        "Clear" to "Bersihkan",
        "Loading..." to "Memuat...",
        "All Languages" to "Semua Bahasa",
        "Popular ⭐" to "Populer ⭐",
        "Indian Languages 🇮🇳" to "Bahasa India 🇮🇳",
        "Global 🌐" to "Bahasa Global 🌐",
        "Select Language" to "Pilih Bahasa",
        "Clear Cache" to "Hapus Cache",
        "Sign Out" to "Keluar",
        "Open in Studio" to "Buka di Studio",
        "Use Template" to "Gunakan Templat"
    )

    val MALAY_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "PENJANA REEL AI",
        "REEL GENERATOR" to "Penjana Reel",
        "Home" to "Laman Utama",
        "AI Tools" to "Alat AI",
        "AI Chat" to "Sembang AI",
        "My Library" to "Pustaka Saya",
        "Projects" to "Projek",
        "Saved Scripts" to "Skrip Tersimpan",
        "Export History" to "Sejarah Eksport",
        "Templates" to "Templat",
        "Premium" to "Premium",
        "Settings" to "Tetapan",
        "App Settings" to "Tetapan Aplikasi",
        "Back" to "Kembali",
        "Preferences" to "Keutamaan",
        "App Theme" to "Tema Aplikasi",
        "App Interface Language" to "Bahasa Antara Muka",
        "AI Video Generation Language" to "Bahasa Penjanaan Video",
        "Storage & Local Cache" to "Storan & Cache",
        "Clear Local Cache & Storage" to "Kosongkan Cache & Storan",
        "Recent Projects" to "Projek Terkini",
        "Create Reel" to "Cipta Reel",
        "Create New Reel" to "Cipta Reel Baharu",
        "AI Reel Architect" to "Arkitek Reel AI",
        "Edit" to "Sunting",
        "Learn How It Works" to "Cara Ia Berfungsi",
        "Got It!" to "Faham!",
        "Generate with AI" to "Jana dengan AI",
        "Speech & Video Language" to "Bahasa Pertuturan & Video",
        "Primary Narrator Voice" to "Suara Pencerita Utama",
        "Selected: " to "Dipilih: ",
        "Selected" to "Dipilih",
        "Male" to "Lelaki",
        "Female" to "Perempuan",
        "Child" to "Kanak-kanak",
        "Speech Speed: " to "Kelajuan Suara: ",
        "Speech Pitch: " to "Nada Suara: ",
        "Preview Voice" to "Dengar Suara",
        "Resolution" to "Resolusi",
        "Background Soundtrack Overlay" to "Muzik Latar",
        "Generate Video" to "Jana Video",
        "Skip & Generate Video" to "Langkau & Jana Video",
        "Visual Timeline Editor" to "Penyunting Garis Masa",
        "Export" to "Eksport",
        "Scene Canvas" to "Kanvas Babak",
        "Add Clip" to "Tambah Klip",
        "Subtitles" to "Sari Kata",
        "50+ Filters" to "50+ Penapis",
        "Delete" to "Padam",
        "Cancel" to "Batal",
        "Save" to "Simpan",
        "Copy" to "Salin",
        "Done" to "Selesai",
        "Yes" to "Ya",
        "No" to "Tidak",
        "Share" to "Kongsi",
        "Share Reel" to "Kongsi Reel",
        "Search..." to "Cari...",
        "Search" to "Carian",
        "Clear" to "Padam",
        "Loading..." to "Memuatkan...",
        "All Languages" to "Semua Bahasa",
        "Popular ⭐" to "Popular ⭐",
        "Indian Languages 🇮🇳" to "Bahasa India 🇮🇳",
        "Global 🌐" to "Bahasa Global 🌐",
        "Select Language" to "Pilih Bahasa",
        "Clear Cache" to "Kosongkan Cache",
        "Sign Out" to "Log Keluar",
        "Open in Studio" to "Buka di Studio",
        "Use Template" to "Guna Templat"
    )

    val VIETNAMESE_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "TRÌNH TẠO REEL AI",
        "REEL GENERATOR" to "Trình tạo Reel",
        "Home" to "Trang chủ",
        "AI Tools" to "Công cụ AI",
        "AI Chat" to "Trò chuyện AI",
        "My Library" to "Thư viện của tôi",
        "Projects" to "Dự án",
        "Saved Scripts" to "Kịch bản đã lưu",
        "Export History" to "Lịch sử xuất",
        "Templates" to "Mẫu",
        "Premium" to "Cao cấp",
        "Settings" to "Cài đặt",
        "App Settings" to "Cài đặt ứng dụng",
        "Back" to "Quay lại",
        "Preferences" to "Tùy chọn",
        "App Theme" to "Giao diện",
        "App Interface Language" to "Ngôn ngữ giao diện",
        "AI Video Generation Language" to "Ngôn ngữ tạo video",
        "Storage & Local Cache" to "Bộ nhớ & Bộ nhớ đệm",
        "Clear Local Cache & Storage" to "Xóa bộ nhớ đệm",
        "Recent Projects" to "Dự án gần đây",
        "Create Reel" to "Tạo Reel",
        "Create New Reel" to "Tạo Reel mới",
        "AI Reel Architect" to "Kiến trúc sư Reel AI",
        "Edit" to "Chỉnh sửa",
        "Learn How It Works" to "Cách hoạt động",
        "Got It!" to "Đã hiểu!",
        "Generate with AI" to "Tạo bằng AI",
        "Speech & Video Language" to "Ngôn ngữ giọng nói & video",
        "Primary Narrator Voice" to "Giọng người thuyết minh",
        "Selected: " to "Đã chọn: ",
        "Selected" to "Đã chọn",
        "Male" to "Nam",
        "Female" to "Nữ",
        "Child" to "Trẻ em",
        "Speech Speed: " to "Tốc độ nói: ",
        "Speech Pitch: " to "Cao độ giọng: ",
        "Preview Voice" to "Nghe thử giọng",
        "Resolution" to "Độ phân giải",
        "Background Soundtrack Overlay" to "Nhạc nền",
        "Generate Video" to "Tạo Video",
        "Skip & Generate Video" to "Bỏ qua & Tạo Video",
        "Visual Timeline Editor" to "Trình chỉnh sửa dòng thời gian",
        "Export" to "Xuất",
        "Scene Canvas" to "Khung cảnh",
        "Add Clip" to "Thêm Clip",
        "Subtitles" to "Phụ đề",
        "50+ Filters" to "50+ Bộ lọc",
        "Delete" to "Xóa",
        "Cancel" to "Hủy",
        "Save" to "Lưu",
        "Copy" to "Sao chép",
        "Done" to "Xong",
        "Yes" to "Có",
        "No" to "Không",
        "Share" to "Chia sẻ",
        "Share Reel" to "Chia sẻ Reel",
        "Search..." to "Tìm kiếm...",
        "Search" to "Tìm kiếm",
        "Clear" to "Xóa",
        "Loading..." to "Đang tải...",
        "All Languages" to "Tất cả ngôn ngữ",
        "Popular ⭐" to "Phổ biến ⭐",
        "Indian Languages 🇮🇳" to "Ngôn ngữ Ấn Độ 🇮🇳",
        "Global 🌐" to "Ngôn ngữ toàn cầu 🌐",
        "Select Language" to "Chọn ngôn ngữ",
        "Clear Cache" to "Xóa bộ nhớ đệm",
        "Sign Out" to "Đăng xuất",
        "Open in Studio" to "Mở trong Studio",
        "Use Template" to "Dùng mẫu này"
    )

    val THAI_MAP = mapOf(
        "Yashora" to "ยาโชรา",
        "AI REEL GENERATOR" to "เครื่องมือสร้างคลิป AI",
        "REEL GENERATOR" to "สร้างคลิปสั้น",
        "Home" to "หน้าหลัก",
        "AI Tools" to "เครื่องมือ AI",
        "AI Chat" to "แชท AI",
        "My Library" to "คลังของฉัน",
        "Projects" to "โปรเจกต์",
        "Saved Scripts" to "สคริปต์ที่บันทึก",
        "Export History" to "ประวัติการส่งออก",
        "Templates" to "เทมเพลต",
        "Premium" to "พรีเมียม",
        "Settings" to "การตั้งค่า",
        "App Settings" to "ตั้งค่าแอป",
        "Back" to "ย้อนกลับ",
        "Preferences" to "การตั้งค่าส่วนบุคคล",
        "App Theme" to "ธีมแอป",
        "App Interface Language" to "ภาษาอินเทอร์เฟซ",
        "AI Video Generation Language" to "ภาษาในการสร้างวิดีโอ",
        "Storage & Local Cache" to "ที่จัดเก็บและแคช",
        "Clear Local Cache & Storage" to "ล้างแคชและข้อมูล",
        "Recent Projects" to "โปรเจกต์ล่าสุด",
        "Create Reel" to "สร้าง Reel",
        "Create New Reel" to "สร้าง Reel ใหม่",
        "AI Reel Architect" to "สถาปนิกคลิป AI",
        "Edit" to "แก้ไข",
        "Learn How It Works" to "วิธีใช้งาน",
        "Got It!" to "เข้าใจแล้ว!",
        "Generate with AI" to "สร้างด้วย AI",
        "Speech & Video Language" to "ภาษาเสียงและวิดีโอ",
        "Primary Narrator Voice" to "เสียงผู้บรรยายหลัก",
        "Selected: " to "ที่เลือก: ",
        "Selected" to "เลือกแล้ว",
        "Male" to "ผู้ชาย",
        "Female" to "ผู้หญิง",
        "Child" to "เด็ก",
        "Speech Speed: " to "ความเร็วเสียง: ",
        "Speech Pitch: " to "ระดับเสียง: ",
        "Preview Voice" to "ฟังตัวอย่างเสียง",
        "Resolution" to "ความละเอียด",
        "Background Soundtrack Overlay" to "เพลงประกอบ",
        "Generate Video" to "สร้างวิดีโอ",
        "Skip & Generate Video" to "ข้ามและสร้างวิดีโอ",
        "Visual Timeline Editor" to "เครื่องมือไทม์ไลน์",
        "Export" to "ส่งออก",
        "Scene Canvas" to "แคนวาสฉาก",
        "Add Clip" to "เพิ่มคลิป",
        "Subtitles" to "คำบรรยาย",
        "50+ Filters" to "50+ ฟิลเตอร์",
        "Delete" to "ลบ",
        "Cancel" to "ยกเลิก",
        "Save" to "บันทึก",
        "Copy" to "คัดลอก",
        "Done" to "เสร็จสิ้น",
        "Yes" to "ใช่",
        "No" to "ไม่ใช่",
        "Share" to "แชร์",
        "Share Reel" to "แชร์ Reel",
        "Search..." to "ค้นหา...",
        "Search" to "ค้นหา",
        "Clear" to "ล้าง",
        "Loading..." to "กำลังโหลด...",
        "All Languages" to "ทุกภาษา",
        "Popular ⭐" to "ยอดนิยม ⭐",
        "Indian Languages 🇮🇳" to "ภาษาอินเดีย 🇮🇳",
        "Global 🌐" to "ภาษาสากล 🌐",
        "Select Language" to "เลือกภาษา",
        "Clear Cache" to "ล้างแคช",
        "Sign Out" to "ออกจากระบบ",
        "Open in Studio" to "เปิดในสตูดิโอ",
        "Use Template" to "ใช้เทมเพลตนี้"
    )

    val FILIPINO_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "AI REEL GENERATOR",
        "REEL GENERATOR" to "Tagagawa ng Reel",
        "Home" to "Home",
        "AI Tools" to "Mga Tool ng AI",
        "AI Chat" to "AI Chat",
        "My Library" to "Aking Library",
        "Projects" to "Mga Proyekto",
        "Saved Scripts" to "Nai-save na Iskrip",
        "Export History" to "Kasaysayan ng Pag-export",
        "Templates" to "Mga Template",
        "Premium" to "Premium",
        "Settings" to "Mga Setting",
        "App Settings" to "Setting ng App",
        "Back" to "Bumalik",
        "Preferences" to "Kagustuhan",
        "App Theme" to "Tema ng App",
        "App Interface Language" to "Wika ng App",
        "AI Video Generation Language" to "Wika ng Paglikha ng Video",
        "Storage & Local Cache" to "Imbakan at Cache",
        "Clear Local Cache & Storage" to "I-clear ang Cache at Imbakan",
        "Recent Projects" to "Kamakailang Proyekto",
        "Create Reel" to "Gumawa ng Reel",
        "Create New Reel" to "Gumawa ng Bagong Reel",
        "AI Reel Architect" to "Arkitekto ng AI Reel",
        "Edit" to "I-edit",
        "Learn How It Works" to "Alamin Kung Paano Gumagana",
        "Got It!" to "Nakuha Ko!",
        "Generate with AI" to "Bumuo gamit ang AI",
        "Speech & Video Language" to "Wika ng Boses at Video",
        "Primary Narrator Voice" to "Pangunahing Boses ng Tagapagsalaysay",
        "Selected: " to "Napili: ",
        "Selected" to "Napili",
        "Male" to "Lalaki",
        "Female" to "Babae",
        "Child" to "Bata",
        "Speech Speed: " to "Bilis ng Pagsasalita: ",
        "Speech Pitch: " to "Tono ng Boses: ",
        "Preview Voice" to "Pakinggan ang Boses",
        "Resolution" to "Resolusyon",
        "Background Soundtrack Overlay" to "Musika sa Background",
        "Generate Video" to "Bumuo ng Video",
        "Skip & Generate Video" to "Laktawan at Bumuo",
        "Visual Timeline Editor" to "Editor ng Timeline",
        "Export" to "I-export",
        "Scene Canvas" to "Canvas ng Eksena",
        "Add Clip" to "Magdagdag ng Clip",
        "Subtitles" to "Mga Subtitle",
        "50+ Filters" to "50+ Mga Filter",
        "Delete" to "Tanggalin",
        "Cancel" to "Kanselahin",
        "Save" to "I-save",
        "Copy" to "Kopyahin",
        "Done" to "Tapos na",
        "Yes" to "Oo",
        "No" to "Hindi",
        "Share" to "Ibahagi",
        "Share Reel" to "Ibahagi ang Reel",
        "Search..." to "Maghanap...",
        "Search" to "Maghanap",
        "Clear" to "I-clear",
        "Loading..." to "Naglo-load...",
        "All Languages" to "Lahat ng Wika",
        "Popular ⭐" to "Sikat ⭐",
        "Indian Languages 🇮🇳" to "Mga Wikang Indian 🇮🇳",
        "Global 🌐" to "Pandaigdigang Wika 🌐",
        "Select Language" to "Pumili ng Wika",
        "Clear Cache" to "I-clear ang Cache",
        "Sign Out" to "Mag-sign Out",
        "Open in Studio" to "Buksan sa Studio",
        "Use Template" to "Gamitin ang Template"
    )

    val SWAHILI_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "MTENGENEZA REELS WA AI",
        "REEL GENERATOR" to "Mtengeneza Reels",
        "Home" to "Nyumbani",
        "AI Tools" to "Zana za AI",
        "AI Chat" to "Gumzo la AI",
        "My Library" to "Maktaba Yangu",
        "Projects" to "Miradi",
        "Saved Scripts" to "Hati Zilizohifadhiwa",
        "Export History" to "Historia ya Usafirishaji",
        "Templates" to "Violezo",
        "Premium" to "Premium",
        "Settings" to "Mipangilio",
        "App Settings" to "Mipangilio ya Programu",
        "Back" to "Nyuma",
        "Preferences" to "Mapendeleo",
        "App Theme" to "Mandhari ya Programu",
        "App Interface Language" to "Lugha ya Programu",
        "AI Video Generation Language" to "Lugha ya Video ya AI",
        "Storage & Local Cache" to "Hifadhi na Akiba",
        "Clear Local Cache & Storage" to "Futa Akiba na Data",
        "Recent Projects" to "Miradi ya Hivi Karibuni",
        "Create Reel" to "Tengeneza Reel",
        "Create New Reel" to "Tengeneza Reel Mpya",
        "AI Reel Architect" to "Mbunifu wa Reel za AI",
        "Edit" to "Hariri",
        "Learn How It Works" to "Jinsi Inavyofanya Kazi",
        "Got It!" to "Nimeelewa!",
        "Generate with AI" to "Tengeneza kwa AI",
        "Speech & Video Language" to "Lugha ya Sauti na Video",
        "Primary Narrator Voice" to "Sauti Kuu ya Msimulizi",
        "Selected: " to "Iliyochaguliwa: ",
        "Selected" to "Imechaguliwa",
        "Male" to "Mwanaume",
        "Female" to "Mwanamke",
        "Child" to "Mtoto",
        "Speech Speed: " to "Kasi ya Mazungumzo: ",
        "Speech Pitch: " to "Kiwango cha Sauti: ",
        "Preview Voice" to "Sikiliza Sauti",
        "Resolution" to "Ubora wa Picha",
        "Background Soundtrack Overlay" to "Muziki wa Chini",
        "Generate Video" to "Tengeneza Video",
        "Skip & Generate Video" to "Ruka na Utengeneze",
        "Visual Timeline Editor" to "Kihariri cha Ratiba",
        "Export" to "Hamisha",
        "Scene Canvas" to "Turubai ya Mandhari",
        "Add Clip" to "Ongeza Kipande",
        "Subtitles" to "Manukuu",
        "50+ Filters" to "Vichujio 50+",
        "Delete" to "Futa",
        "Cancel" to "Ghairi",
        "Save" to "Hifadhi",
        "Copy" to "Nakili",
        "Done" to "Imekamilika",
        "Yes" to "Ndiyo",
        "No" to "Hapana",
        "Share" to "Shiriki",
        "Share Reel" to "Shiriki Reel",
        "Search..." to "Tafuta...",
        "Search" to "Tafuta",
        "Clear" to "Safisha",
        "Loading..." to "Inapakia...",
        "All Languages" to "Lugha Zote",
        "Popular ⭐" to "Maarufu ⭐",
        "Indian Languages 🇮🇳" to "Lugha za Kihindi 🇮🇳",
        "Global 🌐" to "Lugha za Kimataifa 🌐",
        "Select Language" to "Chagua Lugha",
        "Clear Cache" to "Futa Akiba",
        "Sign Out" to "Ondoka",
        "Open in Studio" to "Fungua katika Studio",
        "Use Template" to "Tumia Kiolezo"
    )

    val HAUSA_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "MAI KIRKIRAR BIDIYON REEL NA AI",
        "REEL GENERATOR" to "Mai Kirkirar Reel",
        "Home" to "Gida",
        "AI Tools" to "Kayan Aikin AI",
        "AI Chat" to "Tattaunawar AI",
        "My Library" to "Dakin Karatu Na",
        "Projects" to "Ayyuka",
        "Saved Scripts" to "Rubutun Da Aka Ajiye",
        "Export History" to "Tarihin Fitarwa",
        "Templates" to "Samfura",
        "Premium" to "Premium",
        "Settings" to "Saituna",
        "App Settings" to "Saitunan Manhaja",
        "Back" to "Koma Baya",
        "Preferences" to "Zabi",
        "App Theme" to "Jigon Manhaja",
        "App Interface Language" to "Yaren Manhaja",
        "AI Video Generation Language" to "Yaren Kirkirar Bidiyo",
        "Storage & Local Cache" to "Ma'ajiya da Cache",
        "Clear Local Cache & Storage" to "Share Cache da Bayanai",
        "Recent Projects" to "Sababbin Ayyuka",
        "Create Reel" to "Kirkiri Reel",
        "Create New Reel" to "Kirkiri Sabon Reel",
        "AI Reel Architect" to "Ginin Bidiyon Reel na AI",
        "Edit" to "Gyara",
        "Learn How It Works" to "Koyi Yadda Yake Aiki",
        "Got It!" to "Na Fahimta!",
        "Generate with AI" to "Kirkira da AI",
        "Speech & Video Language" to "Yaren Murya da Bidiyo",
        "Primary Narrator Voice" to "Babban Muryar Mai Magana",
        "Selected: " to "Wanda aka zaba: ",
        "Selected" to "An zaba",
        "Male" to "Namiji",
        "Female" to "Mace",
        "Child" to "Yaro",
        "Speech Speed: " to "Gaggawar Magana: ",
        "Speech Pitch: " to "Karar Murya: ",
        "Preview Voice" to "Saurari Murya",
        "Resolution" to "Ingancin Bidiyo",
        "Background Soundtrack Overlay" to "Kidan Baya",
        "Generate Video" to "Kirkiri Bidiyo",
        "Skip & Generate Video" to "Tsallake & Kirkira",
        "Visual Timeline Editor" to "Editan Lokaci",
        "Export" to "Fitar da Bidiyo",
        "Scene Canvas" to "Allon Fage",
        "Add Clip" to "Sanya Bidiyo",
        "Subtitles" to "Fassarar Kalmomi",
        "50+ Filters" to "Matatun Fage 50+",
        "Delete" to "Goge",
        "Cancel" to "Soke",
        "Save" to "Ajiye",
        "Copy" to "Kwafi",
        "Done" to "An Kammala",
        "Yes" to "I",
        "No" to "A'a",
        "Share" to "Raba",
        "Share Reel" to "Raba Reel",
        "Search..." to "Bincika...",
        "Search" to "Bincike",
        "Clear" to "Share",
        "Loading..." to "Yana Lodawa...",
        "All Languages" to "Duk Yarurruka",
        "Popular ⭐" to "Shahararru ⭐",
        "Indian Languages 🇮🇳" to "Yarurrukan Indiya 🇮🇳",
        "Global 🌐" to "Yarurrukan Duniya 🌐",
        "Select Language" to "Zabi Yare",
        "Clear Cache" to "Share Cache",
        "Sign Out" to "Fita daga Asusun",
        "Open in Studio" to "Bude a Studio",
        "Use Template" to "Yi Amfani da Samfuri"
    )

    val AMHARIC_MAP = mapOf(
        "Yashora" to "ያሾራ",
        "AI REEL GENERATOR" to "የኤአይ ሪል ቪዲዮ አመንጪ",
        "REEL GENERATOR" to "ሪል አመንጪ",
        "Home" to "መነሻ",
        "AI Tools" to "የኤአይ መሳሪያዎች",
        "AI Chat" to "የኤአይ ውይይት",
        "My Library" to "የእኔ ቤተ-መጽሐፍት",
        "Projects" to "ፕሮጀክቶች",
        "Saved Scripts" to "የተቀመጡ ጽሑፎች",
        "Export History" to "የወጡ ፋይሎች ታሪክ",
        "Templates" to "አብነቶች",
        "Premium" to "ፕሪሚየም",
        "Settings" to "ቅንብሮች",
        "App Settings" to "የመተግበሪያ ቅንብሮች",
        "Back" to "ተመለስ",
        "Preferences" to "ምርጫዎች",
        "App Theme" to "የመተግበሪያ ገጽታ",
        "App Interface Language" to "የመተግበሪያ ቋንቋ",
        "AI Video Generation Language" to "የቪዲዮ ማመንጫ ቋንቋ",
        "Storage & Local Cache" to "ማከማቻ እና መሸጎጫ",
        "Clear Local Cache & Storage" to "መሸጎጫ አጽዳ",
        "Recent Projects" to "የቅርብ ጊዜ ፕሮጀክቶች",
        "Create Reel" to "ሪል ፍጠር",
        "Create New Reel" to "አዲስ ሪል ፍጠር",
        "AI Reel Architect" to "የኤአይ ሪል አርክቴክት",
        "Edit" to "አርትዕ",
        "Learn How It Works" to "እንዴት እንደሚሰራ ተማር",
        "Got It!" to "ገባኝ!",
        "Generate with AI" to "በኤአይ ፍጠር",
        "Speech & Video Language" to "የድምጽና ቪዲዮ ቋንቋ",
        "Primary Narrator Voice" to "ዋና ተራኪ ድምጽ",
        "Selected: " to "የተመረጠው: ",
        "Selected" to "ተመርጧል",
        "Male" to "ወንድ",
        "Female" to "ሴት",
        "Child" to "ህጻን",
        "Speech Speed: " to "የንግግር ፍጥነት: ",
        "Speech Pitch: " to "የድምጽ መጠን: ",
        "Preview Voice" to "ድምጹን አዳምጥ",
        "Resolution" to "ጥራት",
        "Background Soundtrack Overlay" to "የጀርባ ሙዚቃ",
        "Generate Video" to "ቪዲዮ ፍጠር",
        "Skip & Generate Video" to "አልፍና ቪዲዮ ፍጠር",
        "Visual Timeline Editor" to "የጊዜ ሰሌዳ አርታዒ",
        "Export" to "ላክ (አውርድ)",
        "Scene Canvas" to "የትዕይንት ሰሌዳ",
        "Add Clip" to "ክሊፕ አክል",
        "Subtitles" to "ንዑስ ርዕሶች",
        "50+ Filters" to "50+ ማጣሪያዎች",
        "Delete" to "ሰርዝ",
        "Cancel" to "ይቅር",
        "Save" to "አስቀምጥ",
        "Copy" to "ቅዳ",
        "Done" to "ተጠናቋል",
        "Yes" to "አዎ",
        "No" to "አይ",
        "Share" to "አጋራ",
        "Share Reel" to "ሪል አጋራ",
        "Search..." to "ፈልግ...",
        "Search" to "ፍለጋ",
        "Clear" to "አጽዳ",
        "Loading..." to "በመጫን ላይ...",
        "All Languages" to "ሁሉም ቋንቋዎች",
        "Popular ⭐" to "ተወዳጅ ⭐",
        "Indian Languages 🇮🇳" to "የህንድ ቋንቋዎች 🇮🇳",
        "Global 🌐" to "ዓለም አቀፍ ቋንቋዎች 🌐",
        "Select Language" to "ቋንቋ ይምረጡ",
        "Clear Cache" to "መሸጎጫ አጽዳ",
        "Sign Out" to "ውጣ",
        "Open in Studio" to "በስቱዲዮ ውስጥ ክፈት",
        "Use Template" to "አብነት ተጠቀም"
    )
}
