package com.ritvyom.yashoraReelgenerator.presentation.utils

/**
 * High-fidelity translation dictionaries for European languages.
 * Covers full UI strings across Yashora Reel Generator.
 */
object LocalizationEuropean {

    val SPANISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GENERADOR DE REELS CON IA",
        "REEL GENERATOR" to "Generador de Reels",
        "Home" to "Inicio",
        "AI Tools" to "Herramientas IA",
        "AI Chat" to "Chat IA",
        "My Library" to "Mi Biblioteca",
        "Projects" to "Proyectos",
        "Saved Scripts" to "Guiones Guardados",
        "Export History" to "Historial de Exportación",
        "Templates" to "Plantillas",
        "Premium" to "Premium",
        "Settings" to "Ajustes",
        "App Settings" to "Ajustes de la Aplicación",
        "Back" to "Atrás",
        "Preferences" to "Preferencias",
        "App Theme" to "Tema de la Aplicación",
        "App Interface Language" to "Idioma de la Interfaz",
        "AI Video Generation Language" to "Idioma de Generación de Video",
        "Voice Engine & ElevenLabs (VoxEleven)" to "Motor de Voz y ElevenLabs",
        "AI Smart Source Matchmaker" to "Coincidencia Inteligente de Fuentes",
        "Storage & Local Cache" to "Almacenamiento y Caché",
        "Clear Local Cache & Storage" to "Borrar Caché y Almacenamiento",
        "Legal & About" to "Legal y Acerca de",
        "Privacy Policy" to "Política de Privacidad",
        "Terms & Conditions" to "Términos y Condiciones",
        "About Yashora Reel Generator" to "Acerca de Yashora Reel Generator",
        "Recent Projects" to "Proyectos Recientes",
        "Create Reel" to "Crear Reel",
        "Create New Reel" to "Crear Nuevo Reel",
        "AI Reel Architect" to "Arquitecto de Reels IA",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "Convierte guiones en guiones gráficos visuales al instante.",
        "AI Script Writer" to "Escritor de Guiones IA",
        "VoxEleven Voice" to "Voz VoxEleven",
        "Edit" to "Editar",
        "Edit Studio" to "Estudio de Edición",
        "Manual Studio" to "Estudio Manual",
        "Manual Studio Pro" to "Estudio Manual Pro",
        "Learn How It Works" to "Cómo Funciona",
        "Got It!" to "¡Entendido!",
        "Configure Reel Pipeline" to "Configurar Flujo de Reel",
        "Write / Paste Reel Script" to "Escribir o Pegar Guión",
        "Generate with AI" to "Generar con IA",
        "Select Cinematic Visual Style" to "Estilo Visual Cinemático",
        "Select Video Narration Style" to "Estilo de Narración",
        "Speech & Video Language" to "Idioma de Voz y Video",
        "Primary Narrator Voice" to "Voz Principal del Narrador",
        "Category / Voice Presets" to "Categoría / Ajustes de Voz",
        "Selected: " to "Seleccionado: ",
        "Selected" to "Seleccionado",
        "Active" to "Activo",
        "Completed" to "Completado",
        "Rendered" to "Renderizado",
        "Saved" to "Guardado",
        "Male" to "Masculino",
        "Female" to "Femenino",
        "Child" to "Infantil",
        "Speech Speed: " to "Velocidad de Voz: ",
        "Speech Pitch: " to "Tono de Voz: ",
        "Preview Voice" to "Escuchar Voz",
        "Resolution" to "Resolución",
        "Video Framerate" to "Fotogramas por Segundo",
        "Background Soundtrack Overlay" to "Música de Fondo",
        "Add smart rhythmic backing beats" to "Añadir ritmo de fondo",
        "Generate Video" to "Generar Video",
        "Skip & Generate Video" to "Omitir y Generar Video",
        "Watch 1 Reward Ad to Start Generation" to "Ver 1 anuncio para generar",
        "Visual Timeline Editor" to "Editor de Línea de Tiempo",
        "Export" to "Exportar",
        "Scene Canvas" to "Lienzo de Escena",
        "Add Clip" to "Añadir Clip",
        "Subtitles" to "Subtítulos",
        "50+ Filters" to "Más de 50 Filtros",
        "Overlays" to "Superposiciones",
        "Transitions" to "Transiciones",
        "AI Background" to "Fondo IA",
        "Split Clip" to "Dividir Clip",
        "Add Sticker" to "Añadir Pegatina",
        "Delete Scene" to "Eliminar Escena",
        "Scene" to "Escena",
        "Play" to "Reproducir",
        "Trim" to "Recortar",
        "Trim ✂️" to "Recortar ✂️",
        "Undo" to "Deshacer",
        "Redo" to "Rehacer",
        "words" to "palabras",
        "Delete" to "Eliminar",
        "Cancel" to "Cancelar",
        "Save" to "Guardar",
        "Copy" to "Copiar",
        "Done" to "Hecho",
        "Yes" to "Sí",
        "No" to "No",
        "Yes, Cancel" to "Sí, Cancelar",
        "No, Continue" to "No, Continuar",
        "Remove" to "Quitar",
        "Replace" to "Reemplazar",
        "REPLACE" to "REEMPLAZAR",
        "Replace Clip" to "Reemplazar Clip",
        "Replace Asset" to "Reemplazar Medio",
        "Replace Media" to "Reemplazar Medio",
        "Search & Replace Clip" to "Buscar y Reemplazar Clip",
        "Search Online Footage & Photos" to "Buscar Videos y Fotos en Línea",
        "Phone Files & Gallery" to "Archivos y Galería del Teléfono",
        "Pick from Phone Gallery" to "Elegir de la Galería",
        "Pick from Device Storage / Files" to "Elegir del Almacenamiento",
        "Search online footage or pick from device files" to "Buscar clips o elegir de archivos del teléfono",
        "Search videos or photos..." to "Buscar videos o fotos...",
        "Share" to "Compartir",
        "Share Reel" to "Compartir Reel",
        "Share Video" to "Compartir Video",
        "Search..." to "Buscar...",
        "Search" to "Buscar",
        "Clear" to "Limpiar",
        "No results found" to "No se encontraron resultados",
        "Loading..." to "Cargando...",
        "Retry Connection" to "Reintentar Conexión",
        "AI Script Generator" to "Generador de Guiones IA",
        "Your AI Generated Script" to "Tu Guión Generado por IA",
        "Saved Scripts History" to "Historial de Guiones Guardados",
        "Regenerate" to "Regenerar",
        "Regenerate Script Variant" to "Regenerar Variante",
        "Send to Video Generator" to "Enviar al Generador de Video",
        "Write Another Script" to "Escribir Otro Guión",
        "All Languages" to "Todos los Idiomas",
        "Popular ⭐" to "Populares ⭐",
        "Indian Languages 🇮🇳" to "Idiomas Indios 🇮🇳",
        "Global 🌐" to "Idiomas Globales 🌐",
        "Select Language" to "Seleccionar Idioma",
        "languages available" to "idiomas disponibles",
        "Search language (e.g. Hindi, Spanish)..." to "Buscar idioma...",
        "No languages match" to "Sin coincidencias",
        "Confirm Cache Clear" to "Confirmar Borrado de Caché",
        "Cache & Storage cleared successfully!" to "¡Caché y almacenamiento borrados con éxito!",
        "Clear Cache" to "Borrar Caché",
        "Sign in to backup and sync" to "Iniciar sesión para sincronizar",
        "Sign Out" to "Cerrar Sesión",
        "Open in Studio" to "Abrir en Estudio",
        "Use Template" to "Usar Plantilla"
    )

    val FRENCH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GÉNÉRATEUR DE REELS IA",
        "REEL GENERATOR" to "Générateur de Reels",
        "Home" to "Accueil",
        "AI Tools" to "Outils IA",
        "AI Chat" to "Discussion IA",
        "My Library" to "Ma Bibliothèque",
        "Projects" to "Projets",
        "Saved Scripts" to "Scripts Enregistrés",
        "Export History" to "Historique d'Exportation",
        "Templates" to "Modèles",
        "Premium" to "Premium",
        "Settings" to "Paramètres",
        "App Settings" to "Paramètres de l'Application",
        "Back" to "Retour",
        "Preferences" to "Préférences",
        "App Theme" to "Thème de l'App",
        "App Interface Language" to "Langue de l'Interface",
        "AI Video Generation Language" to "Langue de Génération Vidéo",
        "Voice Engine & ElevenLabs (VoxEleven)" to "Moteur Vocal & ElevenLabs",
        "Storage & Local Cache" to "Stockage et Cache",
        "Clear Local Cache & Storage" to "Vider le Cache et le Stockage",
        "Legal & About" to "Mentions Légales",
        "Privacy Policy" to "Politique de Confidentialité",
        "Terms & Conditions" to "Conditions Générales",
        "Recent Projects" to "Projets Récents",
        "Create Reel" to "Créer un Reel",
        "Create New Reel" to "Créer un Nouveau Reel",
        "AI Reel Architect" to "Architecte Reel IA",
        "AI Script Writer" to "Scénariste IA",
        "Edit" to "Modifier",
        "Learn How It Works" to "Comment ça Marche",
        "Got It!" to "Compris !",
        "Write / Paste Reel Script" to "Écrire ou Coller le Script",
        "Generate with AI" to "Générer avec l'IA",
        "Speech & Video Language" to "Langue Vocale et Vidéo",
        "Primary Narrator Voice" to "Voix Principale",
        "Selected: " to "Sélectionné : ",
        "Selected" to "Sélectionné",
        "Male" to "Homme",
        "Female" to "Femme",
        "Child" to "Enfant",
        "Speech Speed: " to "Vitesse de Voix : ",
        "Speech Pitch: " to "Hauteur de Voix : ",
        "Preview Voice" to "Écouter la Voix",
        "Resolution" to "Résolution",
        "Background Soundtrack Overlay" to "Bande-son d'Arrière-plan",
        "Generate Video" to "Générer la Vidéo",
        "Skip & Generate Video" to "Passer et Générer",
        "Visual Timeline Editor" to "Éditeur de Montage",
        "Export" to "Exporter",
        "Scene Canvas" to "Canevas de Scène",
        "Add Clip" to "Ajouter un Clip",
        "Subtitles" to "Sous-titres",
        "50+ Filters" to "50+ Filtres",
        "Delete" to "Supprimer",
        "Cancel" to "Annuler",
        "Save" to "Enregistrer",
        "Copy" to "Copier",
        "Done" to "Terminé",
        "Yes" to "Oui",
        "No" to "Non",
        "Share" to "Partager",
        "Share Reel" to "Partager le Reel",
        "Search..." to "Rechercher...",
        "Search" to "Recherche",
        "Clear" to "Effacer",
        "Loading..." to "Chargement...",
        "All Languages" to "Toutes les Langues",
        "Popular ⭐" to "Populaires ⭐",
        "Indian Languages 🇮🇳" to "Langues Indiennes 🇮🇳",
        "Global 🌐" to "Langues Mondiales 🌐",
        "Select Language" to "Sélectionner la Langue",
        "Clear Cache" to "Vider le Cache",
        "Sign Out" to "Déconnexion",
        "Open in Studio" to "Ouvrir dans Studio",
        "Use Template" to "Utiliser le Modèle"
    )

    val GERMAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "KI REEL GENERATOR",
        "REEL GENERATOR" to "Reel Generator",
        "Home" to "Startseite",
        "AI Tools" to "KI-Werkzeuge",
        "AI Chat" to "KI-Chat",
        "My Library" to "Meine Bibliothek",
        "Projects" to "Projekte",
        "Saved Scripts" to "Gespeicherte Skripte",
        "Export History" to "Exportverlauf",
        "Templates" to "Vorlagen",
        "Premium" to "Premium",
        "Settings" to "Einstellungen",
        "App Settings" to "App-Einstellungen",
        "Back" to "Zurück",
        "Preferences" to "Präferenzen",
        "App Theme" to "App-Design",
        "App Interface Language" to "Oberflächensprache",
        "AI Video Generation Language" to "Videogenerierungssprache",
        "Voice Engine & ElevenLabs (VoxEleven)" to "Sprach-Engine & ElevenLabs",
        "Storage & Local Cache" to "Speicher & Cache",
        "Clear Local Cache & Storage" to "Cache und Speicher löschen",
        "Recent Projects" to "Aktuelle Projekte",
        "Create Reel" to "Reel erstellen",
        "Create New Reel" to "Neues Reel erstellen",
        "AI Reel Architect" to "KI Reel Architekt",
        "AI Script Writer" to "KI Drehbuchautor",
        "Edit" to "Bearbeiten",
        "Learn How It Works" to "Funktionsweise",
        "Got It!" to "Verstanden!",
        "Write / Paste Reel Script" to "Skript schreiben oder einfügen",
        "Generate with AI" to "Mit KI erstellen",
        "Speech & Video Language" to "Sprach- und Videoausgabe",
        "Primary Narrator Voice" to "Hauptstimme",
        "Selected: " to "Ausgewählt: ",
        "Selected" to "Ausgewählt",
        "Male" to "Männlich",
        "Female" to "Weiblich",
        "Child" to "Kind",
        "Speech Speed: " to "Sprechtempo: ",
        "Speech Pitch: " to "Tonhöhe: ",
        "Preview Voice" to "Stimme anhören",
        "Resolution" to "Auflösung",
        "Background Soundtrack Overlay" to "Hintergrundmusik",
        "Generate Video" to "Video erstellen",
        "Skip & Generate Video" to "Überspringen & Erstellen",
        "Visual Timeline Editor" to "Timeline-Editor",
        "Export" to "Exportieren",
        "Scene Canvas" to "Szenen-Leinwand",
        "Add Clip" to "Clip hinzufügen",
        "Subtitles" to "Untertitel",
        "50+ Filters" to "50+ Filter",
        "Delete" to "Löschen",
        "Cancel" to "Abbrechen",
        "Save" to "Speichern",
        "Copy" to "Kopieren",
        "Done" to "Fertig",
        "Yes" to "Ja",
        "No" to "Nein",
        "Share" to "Teilen",
        "Share Reel" to "Reel teilen",
        "Search..." to "Suchen...",
        "Search" to "Suche",
        "Clear" to "Löschen",
        "Loading..." to "Laden...",
        "All Languages" to "Alle Sprachen",
        "Popular ⭐" to "Beliebt ⭐",
        "Indian Languages 🇮🇳" to "Indische Sprachen 🇮🇳",
        "Global 🌐" to "Globale Sprachen 🌐",
        "Select Language" to "Sprache wählen",
        "Clear Cache" to "Cache leeren",
        "Sign Out" to "Abmelden",
        "Open in Studio" to "Im Studio öffnen",
        "Use Template" to "Vorlage verwenden"
    )

    val ITALIAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GENERATORE REEL IA",
        "REEL GENERATOR" to "Generatore Reel",
        "Home" to "Home",
        "AI Tools" to "Strumenti IA",
        "AI Chat" to "Chat IA",
        "My Library" to "La Mia Libreria",
        "Projects" to "Progetti",
        "Saved Scripts" to "Script Salvati",
        "Export History" to "Cronologia Esportazioni",
        "Templates" to "Modelli",
        "Premium" to "Premium",
        "Settings" to "Impostazioni",
        "App Settings" to "Impostazioni App",
        "Back" to "Indietro",
        "Preferences" to "Preferenze",
        "App Theme" to "Tema dell'App",
        "App Interface Language" to "Lingua dell'Interfaccia",
        "AI Video Generation Language" to "Lingua Creazione Video",
        "Storage & Local Cache" to "Archiviazione e Cache",
        "Clear Local Cache & Storage" to "Cancella Cache e Dati",
        "Recent Projects" to "Progetti Recenti",
        "Create Reel" to "Crea Reel",
        "Create New Reel" to "Crea Nuovo Reel",
        "AI Reel Architect" to "Architetto Reel IA",
        "AI Script Writer" to "Sceneggiatore IA",
        "Edit" to "Modifica",
        "Learn How It Works" to "Scopri Come Funziona",
        "Got It!" to "Capito!",
        "Write / Paste Reel Script" to "Scrivi o Incolla Script",
        "Generate with AI" to "Genera con IA",
        "Speech & Video Language" to "Lingua Voce e Video",
        "Primary Narrator Voice" to "Voce Narrante Principale",
        "Selected: " to "Selezionato: ",
        "Selected" to "Selezionato",
        "Male" to "Maschile",
        "Female" to "Femminile",
        "Child" to "Bambino",
        "Speech Speed: " to "Velocità Voce: ",
        "Speech Pitch: " to "Tonalità: ",
        "Preview Voice" to "Ascolta Voce",
        "Resolution" to "Risoluzione",
        "Background Soundtrack Overlay" to "Musica di Sottofondo",
        "Generate Video" to "Genera Video",
        "Skip & Generate Video" to "Salta e Genera Video",
        "Visual Timeline Editor" to "Editor Timeline",
        "Export" to "Esporta",
        "Scene Canvas" to "Tela della Scena",
        "Add Clip" to "Aggiungi Clip",
        "Subtitles" to "Sottotitoli",
        "50+ Filters" to "50+ Filtri",
        "Delete" to "Elimina",
        "Cancel" to "Annulla",
        "Save" to "Salva",
        "Copy" to "Copia",
        "Done" to "Fatto",
        "Yes" to "Sì",
        "No" to "No",
        "Share" to "Condividi",
        "Share Reel" to "Condividi Reel",
        "Search..." to "Cerca...",
        "Search" to "Cerca",
        "Clear" to "Pulisci",
        "Loading..." to "Caricamento...",
        "All Languages" to "Tutte le Lingue",
        "Popular ⭐" to "Popolari ⭐",
        "Indian Languages 🇮🇳" to "Lingue Indiane 🇮🇳",
        "Global 🌐" to "Lingue Globali 🌐",
        "Select Language" to "Seleziona Lingua",
        "Clear Cache" to "Cancella Cache",
        "Sign Out" to "Disconnetti",
        "Open in Studio" to "Apri in Studio",
        "Use Template" to "Usa Modello"
    )

    val PORTUGUESE_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GERADOR DE REELS IA",
        "REEL GENERATOR" to "Gerador de Reels",
        "Home" to "Início",
        "AI Tools" to "Ferramentas IA",
        "AI Chat" to "Chat IA",
        "My Library" to "Minha Biblioteca",
        "Projects" to "Projetos",
        "Saved Scripts" to "Roteiros Salvos",
        "Export History" to "Histórico de Exportação",
        "Templates" to "Modelos",
        "Premium" to "Premium",
        "Settings" to "Configurações",
        "App Settings" to "Configurações do App",
        "Back" to "Voltar",
        "Preferences" to "Preferências",
        "App Theme" to "Tema do Aplicativo",
        "App Interface Language" to "Idioma da Interface",
        "AI Video Generation Language" to "Idioma de Criação de Vídeo",
        "Storage & Local Cache" to "Armazenamento e Cache",
        "Clear Local Cache & Storage" to "Limpar Cache e Armazenamento",
        "Recent Projects" to "Projetos Recentes",
        "Create Reel" to "Criar Reel",
        "Create New Reel" to "Criar Novo Reel",
        "AI Reel Architect" to "Arquiteto de Reels IA",
        "AI Script Writer" to "Roteirista IA",
        "Edit" to "Editar",
        "Learn How It Works" to "Como Funciona",
        "Got It!" to "Entendi!",
        "Write / Paste Reel Script" to "Escrever ou Colar Roteiro",
        "Generate with AI" to "Gerar com IA",
        "Speech & Video Language" to "Idioma de Fala e Vídeo",
        "Primary Narrator Voice" to "Voz Principal",
        "Selected: " to "Selecionado: ",
        "Selected" to "Selecionado",
        "Male" to "Masculino",
        "Female" to "Feminino",
        "Child" to "Infantil",
        "Speech Speed: " to "Velocidade: ",
        "Speech Pitch: " to "Tom de Voz: ",
        "Preview Voice" to "Ouvir Voz",
        "Resolution" to "Resolução",
        "Background Soundtrack Overlay" to "Música de Fundo",
        "Generate Video" to "Gerar Vídeo",
        "Skip & Generate Video" to "Pular e Gerar Vídeo",
        "Visual Timeline Editor" to "Editor de Linha do Tempo",
        "Export" to "Exportar",
        "Scene Canvas" to "Tela de Cena",
        "Add Clip" to "Adicionar Clipe",
        "Subtitles" to "Legendas",
        "50+ Filters" to "50+ Filtros",
        "Delete" to "Excluir",
        "Cancel" to "Cancelar",
        "Save" to "Salvar",
        "Copy" to "Copiar",
        "Done" to "Concluído",
        "Yes" to "Sim",
        "No" to "Não",
        "Share" to "Compartilhar",
        "Share Reel" to "Compartilhar Reel",
        "Search..." to "Pesquisar...",
        "Search" to "Pesquisar",
        "Clear" to "Limpar",
        "Loading..." to "Carregando...",
        "All Languages" to "Todos os Idiomas",
        "Popular ⭐" to "Populares ⭐",
        "Indian Languages 🇮🇳" to "Idiomas Indianos 🇮🇳",
        "Global 🌐" to "Idiomas Globais 🌐",
        "Select Language" to "Selecionar Idioma",
        "Clear Cache" to "Limpar Cache",
        "Sign Out" to "Sair",
        "Open in Studio" to "Abrir no Studio",
        "Use Template" to "Usar Modelo"
    )

    val RUSSIAN_MAP = mapOf(
        "Yashora" to "Яшора",
        "AI REEL GENERATOR" to "ИИ ГЕНЕРАТОР REELS",
        "REEL GENERATOR" to "Генератор Reels",
        "Home" to "Главная",
        "AI Tools" to "Инструменты ИИ",
        "AI Chat" to "Чат с ИИ",
        "My Library" to "Моя Библиотека",
        "Projects" to "Проекты",
        "Saved Scripts" to "Сохранённые Сценарии",
        "Export History" to "История Экспорта",
        "Templates" to "Шаблоны",
        "Premium" to "Премиум",
        "Settings" to "Настройки",
        "App Settings" to "Настройки Приложения",
        "Back" to "Назад",
        "Preferences" to "Параметры",
        "App Theme" to "Тема Оформления",
        "App Interface Language" to "Язык Интерфейса",
        "AI Video Generation Language" to "Язык Генерации Видео",
        "Storage & Local Cache" to "Хранилище и Кэш",
        "Clear Local Cache & Storage" to "Очистить Кэш и Память",
        "Recent Projects" to "Недавние Проекты",
        "Create Reel" to "Создать Reel",
        "Create New Reel" to "Создать Новый Reel",
        "AI Reel Architect" to "ИИ Архитектор Reels",
        "AI Script Writer" to "ИИ Сценарист",
        "Edit" to "Редактировать",
        "Learn How It Works" to "Как Это Работает",
        "Got It!" to "Понятно!",
        "Write / Paste Reel Script" to "Написать или Вставить Сценарий",
        "Generate with AI" to "Создать с помощью ИИ",
        "Speech & Video Language" to "Язык Озвучки и Видео",
        "Primary Narrator Voice" to "Основной Голос",
        "Selected: " to "Выбрано: ",
        "Selected" to "Выбрано",
        "Male" to "Мужской",
        "Female" to "Женский",
        "Child" to "Детский",
        "Speech Speed: " to "Скорость Речи: ",
        "Speech Pitch: " to "Высота Голоса: ",
        "Preview Voice" to "Слушать Голос",
        "Resolution" to "Разрешение",
        "Background Soundtrack Overlay" to "Фоновая Музыка",
        "Generate Video" to "Создать Видео",
        "Skip & Generate Video" to "Пропустить и Создать",
        "Visual Timeline Editor" to "Редактор Таймлайна",
        "Export" to "Экспорт",
        "Scene Canvas" to "Холст Сцены",
        "Add Clip" to "Добавить Клип",
        "Subtitles" to "Субтитры",
        "50+ Filters" to "50+ Фильтров",
        "Delete" to "Удалить",
        "Cancel" to "Отмена",
        "Save" to "Сохранить",
        "Copy" to "Копировать",
        "Done" to "Готово",
        "Yes" to "Да",
        "No" to "Нет",
        "Share" to "Поделиться",
        "Share Reel" to "Поделиться Reel",
        "Search..." to "Поиск...",
        "Search" to "Поиск",
        "Clear" to "Очистить",
        "Loading..." to "Загрузка...",
        "All Languages" to "Все Языки",
        "Popular ⭐" to "Популярные ⭐",
        "Indian Languages 🇮🇳" to "Индийские Языки 🇮🇳",
        "Global 🌐" to "Мировые Языки 🌐",
        "Select Language" to "Выбрать Язык",
        "Clear Cache" to "Очистить Кэш",
        "Sign Out" to "Выйти",
        "Open in Studio" to "Открыть в Studio",
        "Use Template" to "Использовать Шаблон"
    )

    val UKRAINIAN_MAP = mapOf(
        "Yashora" to "Яшора",
        "AI REEL GENERATOR" to "ШІ ГЕНЕРАТОР REELS",
        "REEL GENERATOR" to "Генератор Reels",
        "Home" to "Головна",
        "AI Tools" to "Інструменти ШІ",
        "AI Chat" to "Чат із ШІ",
        "My Library" to "Моя Бібліотека",
        "Projects" to "Проєкти",
        "Saved Scripts" to "Збережені Сценарії",
        "Export History" to "Історія Експорту",
        "Templates" to "Шаблони",
        "Premium" to "Преміум",
        "Settings" to "Налаштування",
        "App Settings" to "Налаштування Додатка",
        "Back" to "Назад",
        "Preferences" to "Параметри",
        "App Theme" to "Тема Оформлення",
        "App Interface Language" to "Мова Інтерфейсу",
        "AI Video Generation Language" to "Мова Створення Відео",
        "Storage & Local Cache" to "Пам'ять та Кеш",
        "Clear Local Cache & Storage" to "Очистити Кеш і Пам'ять",
        "Recent Projects" to "Останні Проєкти",
        "Create Reel" to "Створити Reel",
        "Create New Reel" to "Створити Новий Reel",
        "AI Reel Architect" to "ШІ Архітектор Reels",
        "Edit" to "Редагувати",
        "Learn How It Works" to "Як Це Працює",
        "Got It!" to "Зрозуміло!",
        "Generate with AI" to "Згенерувати через ШІ",
        "Speech & Video Language" to "Мова Озвучення та Відео",
        "Primary Narrator Voice" to "Основний Голос",
        "Selected: " to "Обрано: ",
        "Selected" to "Обрано",
        "Male" to "Чоловічий",
        "Female" to "Жіночий",
        "Child" to "Дитячий",
        "Speech Speed: " to "Швидкість: ",
        "Speech Pitch: " to "Висота Голосу: ",
        "Preview Voice" to "Слухати Голос",
        "Resolution" to "Роздільна Здатність",
        "Background Soundtrack Overlay" to "Фонова Музика",
        "Generate Video" to "Згенерувати Відео",
        "Skip & Generate Video" to "Пропустити та Створити",
        "Visual Timeline Editor" to "Редактор Таймлайну",
        "Export" to "Експортувати",
        "Scene Canvas" to "Полотно Сцени",
        "Add Clip" to "Додати Кліп",
        "Subtitles" to "Субтитри",
        "50+ Filters" to "50+ Фільтрів",
        "Delete" to "Видалити",
        "Cancel" to "Скасувати",
        "Save" to "Зберегти",
        "Copy" to "Копіювати",
        "Done" to "Готово",
        "Yes" to "Так",
        "No" to "Ні",
        "Share" to "Поділитися",
        "Share Reel" to "Поділитися Reel",
        "Search..." to "Пошук...",
        "Search" to "Пошук",
        "Clear" to "Очистити",
        "Loading..." to "Завантаження...",
        "All Languages" to "Усі Мови",
        "Popular ⭐" to "Популярні ⭐",
        "Indian Languages 🇮🇳" to "Індійські Мови 🇮🇳",
        "Global 🌐" to "Світові Мови 🌐",
        "Select Language" to "Обрати Мову",
        "Clear Cache" to "Очистити Кеш",
        "Sign Out" to "Вийти",
        "Open in Studio" to "Відкрити в Studio",
        "Use Template" to "Використати Шаблон"
    )

    val POLISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GENERATOR REELS AI",
        "REEL GENERATOR" to "Generator Reels",
        "Home" to "Główna",
        "AI Tools" to "Narzędzia AI",
        "AI Chat" to "Czat AI",
        "My Library" to "Moja Biblioteka",
        "Projects" to "Projekty",
        "Saved Scripts" to "Zapisane Skrypty",
        "Export History" to "Historia Eksportu",
        "Templates" to "Szablony",
        "Premium" to "Premium",
        "Settings" to "Ustawienia",
        "App Settings" to "Ustawienia Aplikacji",
        "Back" to "Wstecz",
        "Preferences" to "Preferencje",
        "App Theme" to "Motyw Aplikacji",
        "App Interface Language" to "Język Interfejsu",
        "AI Video Generation Language" to "Język Tworzenia Wideo",
        "Storage & Local Cache" to "Pamięć i Pamięć Podręczna",
        "Clear Local Cache & Storage" to "Wyczyść Pamięć Podręczną",
        "Recent Projects" to "Ostatnie Projekty",
        "Create Reel" to "Utwórz Reel",
        "Create New Reel" to "Utwórz Nowy Reel",
        "AI Reel Architect" to "Architekt Reels AI",
        "Edit" to "Edytuj",
        "Learn How It Works" to "Jak To Działa",
        "Got It!" to "Rozumiem!",
        "Generate with AI" to "Generuj z AI",
        "Speech & Video Language" to "Język Głosu i Wideo",
        "Primary Narrator Voice" to "Główny Lektor",
        "Selected: " to "Wybrano: ",
        "Selected" to "Wybrano",
        "Male" to "Męski",
        "Female" to "Żeński",
        "Child" to "Dziecięcy",
        "Speech Speed: " to "Szybkość Mowy: ",
        "Speech Pitch: " to "Ton Głosu: ",
        "Preview Voice" to "Odsłuchaj Głos",
        "Resolution" to "Rozdzielczość",
        "Background Soundtrack Overlay" to "Muzyka w Tle",
        "Generate Video" to "Generuj Wideo",
        "Skip & Generate Video" to "Pomiń i Generuj",
        "Visual Timeline Editor" to "Edytor Osi Czasu",
        "Export" to "Eksportuj",
        "Scene Canvas" to "Płótno Sceny",
        "Add Clip" to "Dodaj Klip",
        "Subtitles" to "Napisy",
        "50+ Filters" to "50+ Filtrów",
        "Delete" to "Usuń",
        "Cancel" to "Anuluj",
        "Save" to "Zapisz",
        "Copy" to "Kopiuj",
        "Done" to "Gotowe",
        "Yes" to "Tak",
        "No" to "Nie",
        "Share" to "Udostępnij",
        "Share Reel" to "Udostępnij Reel",
        "Search..." to "Szukaj...",
        "Search" to "Szukaj",
        "Clear" to "Wyczyść",
        "Loading..." to "Ładowanie...",
        "All Languages" to "Wszystkie Języki",
        "Popular ⭐" to "Popularne ⭐",
        "Indian Languages 🇮🇳" to "Języki Indyjskie 🇮🇳",
        "Global 🌐" to "Języki Globalne 🌐",
        "Select Language" to "Wybierz Język",
        "Clear Cache" to "Wyczyść Pamięć Podręczną",
        "Sign Out" to "Wyloguj Się",
        "Open in Studio" to "Otwórz w Studio",
        "Use Template" to "Użyj Szablonu"
    )

    val DUTCH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "AI REEL GENERATOR",
        "REEL GENERATOR" to "Reel Generator",
        "Home" to "Start",
        "AI Tools" to "AI-Tools",
        "AI Chat" to "AI-Chat",
        "My Library" to "Mijn Bibliotheek",
        "Projects" to "Projecten",
        "Saved Scripts" to "Opgeslagen Scripts",
        "Export History" to "Exporthistorie",
        "Templates" to "Sjablonen",
        "Premium" to "Premium",
        "Settings" to "Instellingen",
        "App Settings" to "App-Instellingen",
        "Back" to "Terug",
        "Preferences" to "Voorkeuren",
        "App Theme" to "App-Thema",
        "App Interface Language" to "Interfacetaal",
        "AI Video Generation Language" to "Videogeneratietaal",
        "Storage & Local Cache" to "Opslag & Cache",
        "Clear Local Cache & Storage" to "Cache en Geheugen Wissen",
        "Recent Projects" to "Recente Projecten",
        "Create Reel" to "Reel Maken",
        "Create New Reel" to "Nieuwe Reel Maken",
        "AI Reel Architect" to "AI Reel Architect",
        "Edit" to "Bewerken",
        "Learn How It Works" to "Hoe Het Werkt",
        "Got It!" to "Begrepen!",
        "Generate with AI" to "Genereren met AI",
        "Speech & Video Language" to "Spraak- en Videotaal",
        "Primary Narrator Voice" to "Hoofdverteller Stem",
        "Selected: " to "Geselecteerd: ",
        "Selected" to "Geselecteerd",
        "Male" to "Mannelijk",
        "Female" to "Vrouwelijk",
        "Child" to "Kind",
        "Speech Speed: " to "Spraaksnelheid: ",
        "Speech Pitch: " to "Stemhoogte: ",
        "Preview Voice" to "Stem Beluisteren",
        "Resolution" to "Resolutie",
        "Background Soundtrack Overlay" to "Achtergrondmuziek",
        "Generate Video" to "Video Genereren",
        "Skip & Generate Video" to "Overslaan & Genereren",
        "Visual Timeline Editor" to "Tijdlijn Bewerker",
        "Export" to "Exporteren",
        "Scene Canvas" to "Scènedoek",
        "Add Clip" to "Clip Toevoegen",
        "Subtitles" to "Ondertitels",
        "50+ Filters" to "50+ Filters",
        "Delete" to "Verwijderen",
        "Cancel" to "Annuleren",
        "Save" to "Opslaan",
        "Copy" to "Kopiëren",
        "Done" to "Klaar",
        "Yes" to "Ja",
        "No" to "Nee",
        "Share" to "Delen",
        "Share Reel" to "Reel Delen",
        "Search..." to "Zoeken...",
        "Search" to "Zoeken",
        "Clear" to "Wissen",
        "Loading..." to "Laden...",
        "All Languages" to "Alle Talen",
        "Popular ⭐" to "Populair ⭐",
        "Indian Languages 🇮🇳" to "Indiase Talen 🇮🇳",
        "Global 🌐" to "Wereldwijde Talen 🌐",
        "Select Language" to "Selecteer Taal",
        "Clear Cache" to "Cache Wissen",
        "Sign Out" to "Uitloggen",
        "Open in Studio" to "Openen in Studio",
        "Use Template" to "Sjabloon Gebruiken"
    )

    val SWEDISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "AI REEL GENERATOR",
        "REEL GENERATOR" to "Reel Generator",
        "Home" to "Hem",
        "AI Tools" to "AI-Verktyg",
        "AI Chat" to "AI-Chatt",
        "My Library" to "Mitt Bibliotek",
        "Projects" to "Projekt",
        "Saved Scripts" to "Sparade Manus",
        "Export History" to "Exporthistorik",
        "Templates" to "Mallar",
        "Premium" to "Premium",
        "Settings" to "Inställningar",
        "App Settings" to "Appinställningar",
        "Back" to "Tillbaka",
        "Preferences" to "Inställningar",
        "App Theme" to "Apptema",
        "App Interface Language" to "Gränssnittsspråk",
        "AI Video Generation Language" to "Videoskapandespråk",
        "Storage & Local Cache" to "Lagring och Cache",
        "Clear Local Cache & Storage" to "Rensa Cache och Data",
        "Recent Projects" to "Senaste Projekt",
        "Create Reel" to "Skapa Reel",
        "Create New Reel" to "Skapa Ny Reel",
        "AI Reel Architect" to "AI Reel Arkitekt",
        "Edit" to "Redigera",
        "Learn How It Works" to "Hur Det Fungerar",
        "Got It!" to "Uppfattat!",
        "Generate with AI" to "Skapa med AI",
        "Speech & Video Language" to "Tal- och Videospråk",
        "Primary Narrator Voice" to "Huvudberättarröst",
        "Selected: " to "Vald: ",
        "Selected" to "Vald",
        "Male" to "Manlig",
        "Female" to "Kvinnlig",
        "Child" to "Barn",
        "Speech Speed: " to "Talhastighet: ",
        "Speech Pitch: " to "Tonhöjd: ",
        "Preview Voice" to "Provlyssna Röst",
        "Resolution" to "Upplösning",
        "Background Soundtrack Overlay" to "Bakgrundsmusik",
        "Generate Video" to "Skapa Video",
        "Skip & Generate Video" to "Hoppa över & Skapa",
        "Visual Timeline Editor" to "Tidslinjeredigerare",
        "Export" to "Exportera",
        "Scene Canvas" to "Scenduk",
        "Add Clip" to "Lägg till Klipp",
        "Subtitles" to "Undertexter",
        "50+ Filters" to "50+ Filter",
        "Delete" to "Ta Bort",
        "Cancel" to "Avbryt",
        "Save" to "Spara",
        "Copy" to "Kopiera",
        "Done" to "Klar",
        "Yes" to "Ja",
        "No" to "Nej",
        "Share" to "Dela",
        "Share Reel" to "Dela Reel",
        "Search..." to "Sök...",
        "Search" to "Sök",
        "Clear" to "Rensa",
        "Loading..." to "Laddar...",
        "All Languages" to "Alla Språk",
        "Popular ⭐" to "Populära ⭐",
        "Indian Languages 🇮🇳" to "Indiska Språk 🇮🇳",
        "Global 🌐" to "Globala Språk 🌐",
        "Select Language" to "Välj Språk",
        "Clear Cache" to "Rensa Cache",
        "Sign Out" to "Logga Ut",
        "Open in Studio" to "Öppna i Studio",
        "Use Template" to "Använd Mall"
    )

    val NORWEGIAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "AI REEL GENERATOR",
        "REEL GENERATOR" to "Reel Generator",
        "Home" to "Hjem",
        "AI Tools" to "AI-Verktøy",
        "AI Chat" to "AI-Chat",
        "My Library" to "Mitt Bibliotek",
        "Projects" to "Prosjekter",
        "Saved Scripts" to "Lagrede Manuskripter",
        "Export History" to "Eksporthistorikk",
        "Templates" to "Maler",
        "Premium" to "Premium",
        "Settings" to "Innstillinger",
        "App Settings" to "Appinnstillinger",
        "Back" to "Tilbake",
        "Preferences" to "Preferanser",
        "App Theme" to "Apptema",
        "App Interface Language" to "Grensesnittspråk",
        "AI Video Generation Language" to "Videoskapingsspråk",
        "Storage & Local Cache" to "Lagring og Hurtigbuffer",
        "Clear Local Cache & Storage" to "Tøm Hurtigbuffer og Lagring",
        "Recent Projects" to "Nylige Prosjekter",
        "Create Reel" to "Lag Reel",
        "Create New Reel" to "Lag Ny Reel",
        "AI Reel Architect" to "AI Reel Arkitekt",
        "Edit" to "Rediger",
        "Learn How It Works" to "Hvordan Det Fungerer",
        "Got It!" to "Skjønner!",
        "Generate with AI" to "Generer med AI",
        "Speech & Video Language" to "Tale- og Videospråk",
        "Primary Narrator Voice" to "Hovedforteller Stemme",
        "Selected: " to "Valgt: ",
        "Selected" to "Valgt",
        "Male" to "Mann",
        "Female" to "Kvinne",
        "Child" to "Barn",
        "Speech Speed: " to "Talehastighet: ",
        "Speech Pitch: " to "Tonehøyde: ",
        "Preview Voice" to "Lytt til Stemme",
        "Resolution" to "Oppløsning",
        "Background Soundtrack Overlay" to "Bakgrunnsmusikk",
        "Generate Video" to "Generer Video",
        "Skip & Generate Video" to "Hopp over & Generer",
        "Visual Timeline Editor" to "Tidslinjeredigering",
        "Export" to "Eksporter",
        "Scene Canvas" to "Sceneskisse",
        "Add Clip" to "Legg til Klipp",
        "Subtitles" to "Undertekster",
        "50+ Filters" to "50+ Filtre",
        "Delete" to "Slett",
        "Cancel" to "Avbryt",
        "Save" to "Lagre",
        "Copy" to "Kopier",
        "Done" to "Ferdig",
        "Yes" to "Ja",
        "No" to "Nei",
        "Share" to "Del",
        "Share Reel" to "Del Reel",
        "Search..." to "Søk...",
        "Search" to "Søk",
        "Clear" to "Tøm",
        "Loading..." to "Laster...",
        "All Languages" to "Alle Språk",
        "Popular ⭐" to "Populære ⭐",
        "Indian Languages 🇮🇳" to "Indiske Språk 🇮🇳",
        "Global 🌐" to "Globale Språk 🌐",
        "Select Language" to "Velg Språk",
        "Clear Cache" to "Tøm Hurtigbuffer",
        "Sign Out" to "Logg Ut",
        "Open in Studio" to "Åpne i Studio",
        "Use Template" to "Bruk Mal"
    )

    val FINNISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "TEKOÄLY REEL GENERAATTORI",
        "REEL GENERATOR" to "Reel-generaattori",
        "Home" to "Koti",
        "AI Tools" to "Tekoälytyökalut",
        "AI Chat" to "Tekoäly-chat",
        "My Library" to "Kirjastoni",
        "Projects" to "Projektit",
        "Saved Scripts" to "Tallennetut Käsikirjoitukset",
        "Export History" to "Vientihistoria",
        "Templates" to "Mallit",
        "Premium" to "Premium",
        "Settings" to "Asetukset",
        "App Settings" to "Sovelluksen Asetukset",
        "Back" to "Takaisin",
        "Preferences" to "Asetukset",
        "App Theme" to "Sovelluksen Teema",
        "App Interface Language" to "Käyttöliittymän Kieli",
        "AI Video Generation Language" to "Videon Luontikieli",
        "Storage & Local Cache" to "Tallennustila ja Välimuisti",
        "Clear Local Cache & Storage" to "Tyhjennä Välimuisti ja Tiedot",
        "Recent Projects" to "Viimeisimmät Projektit",
        "Create Reel" to "Luo Reel",
        "Create New Reel" to "Luo Uusi Reel",
        "AI Reel Architect" to "Tekoäly Reel-arkkitehti",
        "Edit" to "Muokkaa",
        "Learn How It Works" to "Kuinka Se Toimii",
        "Got It!" to "Selvä!",
        "Generate with AI" to "Luo Tekoälyllä",
        "Speech & Video Language" to "Puhe- ja Videokieli",
        "Primary Narrator Voice" to "Puhujan Ääni",
        "Selected: " to "Valittu: ",
        "Selected" to "Valittu",
        "Male" to "Mies",
        "Female" to "Nainen",
        "Child" to "Lapsi",
        "Speech Speed: " to "Puhenopeus: ",
        "Speech Pitch: " to "Äänenkorkeus: ",
        "Preview Voice" to "Kuuntele Ääni",
        "Resolution" to "Resoluutio",
        "Background Soundtrack Overlay" to "Taustamusiikki",
        "Generate Video" to "Luo Video",
        "Skip & Generate Video" to "Ohita ja Luo Video",
        "Visual Timeline Editor" to "Aikajanan Muokkain",
        "Export" to "Vie",
        "Scene Canvas" to "Kohtauskangas",
        "Add Clip" to "Lisää Leike",
        "Subtitles" to "Tekstitykset",
        "50+ Filters" to "50+ Suodatinta",
        "Delete" to "Poista",
        "Cancel" to "Peruuta",
        "Save" to "Tallenna",
        "Copy" to "Kopioi",
        "Done" to "Valmis",
        "Yes" to "Kyllä",
        "No" to "Ei",
        "Share" to "Jaa",
        "Share Reel" to "Jaa Reel",
        "Search..." to "Hae...",
        "Search" to "Haku",
        "Clear" to "Tyhjennä",
        "Loading..." to "Ladataan...",
        "All Languages" to "Kaikki Kielet",
        "Popular ⭐" to "Suositut ⭐",
        "Indian Languages 🇮🇳" to "Intialaiset Kielet 🇮🇳",
        "Global 🌐" to "Maailmanlaajuiset Kielet 🌐",
        "Select Language" to "Valitse Kieli",
        "Clear Cache" to "Tyhjennä Välimuisti",
        "Sign Out" to "Kirjaudu Ulos",
        "Open in Studio" to "Avaa Studiossa",
        "Use Template" to "Käytä Mallia"
    )

    val GREEK_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "ΓΕΝΝΗΤΡΙΑ REELS AI",
        "REEL GENERATOR" to "Γεννήτρια Reels",
        "Home" to "Αρχική",
        "AI Tools" to "Εργαλεία AI",
        "AI Chat" to "Συνομιλία AI",
        "My Library" to "Η Βιβλιοθήκη μου",
        "Projects" to "Έργα",
        "Saved Scripts" to "Αποθηκευμένα Σενάρια",
        "Export History" to "Ιστορικό Εξαγωγών",
        "Templates" to "Πρότυπα",
        "Premium" to "Premium",
        "Settings" to "Ρυθμίσεις",
        "App Settings" to "Ρυθμίσεις Εφαρμογής",
        "Back" to "Πίσω",
        "Preferences" to "Προτιμήσεις",
        "App Theme" to "Θέμα Εφαρμογής",
        "App Interface Language" to "Γλώσσα Διεπαφής",
        "AI Video Generation Language" to "Γλώσσα Δημιουργίας Βίντεο",
        "Storage & Local Cache" to "Αποθήκευση και Cache",
        "Clear Local Cache & Storage" to "Εκκαθάριση Cache & Δεδομένων",
        "Recent Projects" to "Πρόσφατα Έργα",
        "Create Reel" to "Δημιουργία Reel",
        "Create New Reel" to "Δημιουργία Νέου Reel",
        "AI Reel Architect" to "Αρχιτέκτονας Reels AI",
        "Edit" to "Επεξεργασία",
        "Learn How It Works" to "Πώς Λειτουργεί",
        "Got It!" to "Το Κατάλαβα!",
        "Generate with AI" to "Δημιουργία με AI",
        "Speech & Video Language" to "Γλώσσα Φωνής και Βίντεο",
        "Primary Narrator Voice" to "Κύρια Φωνή Αφηγητή",
        "Selected: " to "Επιλέχθηκε: ",
        "Selected" to "Επιλέχθηκε",
        "Male" to "Άνδρας",
        "Female" to "Γυναίκα",
        "Child" to "Παιδί",
        "Speech Speed: " to "Ταχύτητα Ομιλίας: ",
        "Speech Pitch: " to "Τόνος Φωνής: ",
        "Preview Voice" to "Προεπισκόπηση Φωνής",
        "Resolution" to "Ανάλυση",
        "Background Soundtrack Overlay" to "Μουσική Υποβάθρου",
        "Generate Video" to "Δημιουργία Βίντεο",
        "Skip & Generate Video" to "Παράκαμψη & Δημιουργία",
        "Visual Timeline Editor" to "Επεξεργαστής Χρονολογίου",
        "Export" to "Εξαγωγή",
        "Scene Canvas" to "Καμβάς Σκηνής",
        "Add Clip" to "Προσθήκη Κλιπ",
        "Subtitles" to "Υπότιτλοι",
        "50+ Filters" to "50+ Φίλτρα",
        "Delete" to "Διαγραφή",
        "Cancel" to "Ακύρωση",
        "Save" to "Αποθήκευση",
        "Copy" to "Αντιγραφή",
        "Done" to "Ολοκληρώθηκε",
        "Yes" to "Ναι",
        "No" to "Όχι",
        "Share" to "Κοινοποίηση",
        "Share Reel" to "Κοινοποίηση Reel",
        "Search..." to "Αναζήτηση...",
        "Search" to "Αναζήτηση",
        "Clear" to "Εκκαθάριση",
        "Loading..." to "Φόρτωση...",
        "All Languages" to "Όλες οι Γλώσσες",
        "Popular ⭐" to "Δημοφιλή ⭐",
        "Indian Languages 🇮🇳" to "Ινδικές Γλώσσες 🇮🇳",
        "Global 🌐" to "Παγκόσμιες Γλώσσες 🌐",
        "Select Language" to "Επιλογή Γλώσσας",
        "Clear Cache" to "Εκκαθάριση Cache",
        "Sign Out" to "Αποσύνδεση",
        "Open in Studio" to "Άνοιγμα στο Studio",
        "Use Template" to "Χρήση Προτύπου"
    )

    val ROMANIAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "GENERATOR REELS IA",
        "REEL GENERATOR" to "Generator Reels",
        "Home" to "Acasă",
        "AI Tools" to "Instrumente IA",
        "AI Chat" to "Chat IA",
        "My Library" to "Biblioteca Mea",
        "Projects" to "Proiecte",
        "Saved Scripts" to "Scenarii Salvate",
        "Export History" to "Istoric Export",
        "Templates" to "Șabloane",
        "Premium" to "Premium",
        "Settings" to "Setări",
        "App Settings" to "Setări Aplicație",
        "Back" to "Înapoi",
        "Preferences" to "Preferințe",
        "App Theme" to "Tema Aplicației",
        "App Interface Language" to "Limba Interfeței",
        "AI Video Generation Language" to "Limba de Generare Video",
        "Storage & Local Cache" to "Stocare și Cache",
        "Clear Local Cache & Storage" to "Ștergeți Cache și Stocare",
        "Recent Projects" to "Proiecte Recente",
        "Create Reel" to "Creează Reel",
        "Create New Reel" to "Creează Reel Nou",
        "AI Reel Architect" to "Arhitect Reels IA",
        "Edit" to "Editează",
        "Learn How It Works" to "Cum Funcționează",
        "Got It!" to "Am Înțeles!",
        "Generate with AI" to "Generează cu IA",
        "Speech & Video Language" to "Limba Vocii și a Videoclipului",
        "Primary Narrator Voice" to "Vocea Principală a Naratorului",
        "Selected: " to "Selectat: ",
        "Selected" to "Selectat",
        "Male" to "Bărbat",
        "Female" to "Femeie",
        "Child" to "Copil",
        "Speech Speed: " to "Viteza Vorbirii: ",
        "Speech Pitch: " to "Tonalitate Voce: ",
        "Preview Voice" to "Previzualizare Voce",
        "Resolution" to "Rezoluție",
        "Background Soundtrack Overlay" to "Muzică de Fundal",
        "Generate Video" to "Generează Video",
        "Skip & Generate Video" to "Omite și Generează",
        "Visual Timeline Editor" to "Editor Cronologie",
        "Export" to "Exportă",
        "Scene Canvas" to "Pânză Scenă",
        "Add Clip" to "Adaugă Clip",
        "Subtitles" to "Subtitrări",
        "50+ Filters" to "50+ Filtre",
        "Delete" to "Șterge",
        "Cancel" to "Anulează",
        "Save" to "Salvează",
        "Copy" to "Copiază",
        "Done" to "Gata",
        "Yes" to "Da",
        "No" to "Nu",
        "Share" to "Distribuie",
        "Share Reel" to "Distribuie Reel",
        "Search..." to "Caută...",
        "Search" to "Căutare",
        "Clear" to "Golește",
        "Loading..." to "Se încarcă...",
        "All Languages" to "Toate Limbile",
        "Popular ⭐" to "Populare ⭐",
        "Indian Languages 🇮🇳" to "Limbi Indiene 🇮🇳",
        "Global 🌐" to "Limbi Globale 🌐",
        "Select Language" to "Selectează Limba",
        "Clear Cache" to "Golește Cache-ul",
        "Sign Out" to "Deconectare",
        "Open in Studio" to "Deschide în Studio",
        "Use Template" to "Folosește Șablonul"
    )

    val HUNGARIAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "MI REEL GENERÁTOR",
        "REEL GENERATOR" to "Reel Generátor",
        "Home" to "Kezdőlap",
        "AI Tools" to "MI Eszközök",
        "AI Chat" to "MI Csevegés",
        "My Library" to "Könyvtáram",
        "Projects" to "Projektek",
        "Saved Scripts" to "Mentett Forgatókönyvek",
        "Export History" to "Exportálási Előzmények",
        "Templates" to "Sablonok",
        "Premium" to "Prémium",
        "Settings" to "Beállítások",
        "App Settings" to "Alkalmazás Beállítások",
        "Back" to "Vissza",
        "Preferences" to "Beállítások",
        "App Theme" to "Alkalmazás Téma",
        "App Interface Language" to "Felület Nyelve",
        "AI Video Generation Language" to "Videókészítés Nyelve",
        "Storage & Local Cache" to "Tárhely és Gyorsítótár",
        "Clear Local Cache & Storage" to "Gyorsítótár és Tárhely Törlése",
        "Recent Projects" to "Legutóbbi Projektek",
        "Create Reel" to "Reel Létrehozása",
        "Create New Reel" to "Új Reel Létrehozása",
        "AI Reel Architect" to "MI Reel Építész",
        "Edit" to "Szerkesztés",
        "Learn How It Works" to "Hogyan Működik",
        "Got It!" to "Értem!",
        "Generate with AI" to "Létrehozás MI-vel",
        "Speech & Video Language" to "Beszéd és Videó Nyelv",
        "Primary Narrator Voice" to "Fő Narrátor Hang",
        "Selected: " to "Kiválasztva: ",
        "Selected" to "Kiválasztva",
        "Male" to "Férfi",
        "Female" to "Nő",
        "Child" to "Gyermek",
        "Speech Speed: " to "Beszédsebesség: ",
        "Speech Pitch: " to "Hangmagasság: ",
        "Preview Voice" to "Hang Meghallgatása",
        "Resolution" to "Felbontás",
        "Background Soundtrack Overlay" to "Háttérzene",
        "Generate Video" to "Videó Generálása",
        "Skip & Generate Video" to "Kihagyás és Generálás",
        "Visual Timeline Editor" to "Idővonal Szerkesztő",
        "Export" to "Exportálás",
        "Scene Canvas" to "Jelenet Vászon",
        "Add Clip" to "Klip Hozzáadása",
        "Subtitles" to "Feliratok",
        "50+ Filters" to "50+ Szűrő",
        "Delete" to "Törlés",
        "Cancel" to "Mégse",
        "Save" to "Mentés",
        "Copy" to "Másolás",
        "Done" to "Kész",
        "Yes" to "Igen",
        "No" to "Nem",
        "Share" to "Megosztás",
        "Share Reel" to "Reel Megosztása",
        "Search..." to "Keresés...",
        "Search" to "Keresés",
        "Clear" to "Törlés",
        "Loading..." to "Betöltés...",
        "All Languages" to "Minden Nyelv",
        "Popular ⭐" to "Népszerű ⭐",
        "Indian Languages 🇮🇳" to "Indiai Nyelvek 🇮🇳",
        "Global 🌐" to "Globális Nyelvek 🌐",
        "Select Language" to "Nyelv Kiválasztása",
        "Clear Cache" to "Gyorsítótár Törlése",
        "Sign Out" to "Kijelentkezés",
        "Open in Studio" to "Megnyitás a Studio-ban",
        "Use Template" to "Sablon Használata"
    )

    val CZECH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "AI GENERÁTOR REELS",
        "REEL GENERATOR" to "Generátor Reels",
        "Home" to "Domů",
        "AI Tools" to "Nástroje AI",
        "AI Chat" to "AI Chat",
        "My Library" to "Moje Knihovna",
        "Projects" to "Projekty",
        "Saved Scripts" to "Uložené Scénáře",
        "Export History" to "Historie Exportu",
        "Templates" to "Šablony",
        "Premium" to "Premium",
        "Settings" to "Nastavení",
        "App Settings" to "Nastavení Aplikace",
        "Back" to "Zpět",
        "Preferences" to "Předvolby",
        "App Theme" to "Motiv Aplikace",
        "App Interface Language" to "Jazyk Rozhraní",
        "AI Video Generation Language" to "Jazyk Tvorby Videa",
        "Storage & Local Cache" to "Úložiště a Mezipaměť",
        "Clear Local Cache & Storage" to "Vymazat Mezipaměť a Data",
        "Recent Projects" to "Nedávné Projekty",
        "Create Reel" to "Vytvořit Reel",
        "Create New Reel" to "Vytvořit Nový Reel",
        "AI Reel Architect" to "AI Architekt Reels",
        "Edit" to "Upravit",
        "Learn How It Works" to "Jak To Funguje",
        "Got It!" to "Rozumím!",
        "Generate with AI" to "Generovat pomocí AI",
        "Speech & Video Language" to "Jazyk Hlasu a Videa",
        "Primary Narrator Voice" to "Hlavní Hlas Vypravěče",
        "Selected: " to "Vybráno: ",
        "Selected" to "Vybráno",
        "Male" to "Muž",
        "Female" to "Žena",
        "Child" to "Dítě",
        "Speech Speed: " to "Rychlost Řeči: ",
        "Speech Pitch: " to "Výška Hlasu: ",
        "Preview Voice" to "Přehrát Hlas",
        "Resolution" to "Rozlišení",
        "Background Soundtrack Overlay" to "Hudba na Pozadí",
        "Generate Video" to "Generovat Video",
        "Skip & Generate Video" to "Přeskočit a Vytvořit",
        "Visual Timeline Editor" to "Editor Časové Osy",
        "Export" to "Exportovat",
        "Scene Canvas" to "Plátno Scény",
        "Add Clip" to "Přidat Klip",
        "Subtitles" to "Titulky",
        "50+ Filters" to "50+ Filtrů",
        "Delete" to "Smazat",
        "Cancel" to "Zrušit",
        "Save" to "Uložit",
        "Copy" to "Kopírovat",
        "Done" to "Hotovo",
        "Yes" to "Ano",
        "No" to "Ne",
        "Share" to "Sdílet",
        "Share Reel" to "Sdílet Reel",
        "Search..." to "Hledat...",
        "Search" to "Hledat",
        "Clear" to "Vymazat",
        "Loading..." to "Načítání...",
        "All Languages" to "Všechny Jazyky",
        "Popular ⭐" to "Populární ⭐",
        "Indian Languages 🇮🇳" to "Indické Jazyky 🇮🇳",
        "Global 🌐" to "Globální Jazyky 🌐",
        "Select Language" to "Vyberte Jazyk",
        "Clear Cache" to "Vymazat Mezipaměť",
        "Sign Out" to "Odhlásit Se",
        "Open in Studio" to "Otevřít ve Studio",
        "Use Template" to "Použít Šablonu"
    )
}
