package com.ritvyom.yashoraReelgenerator.presentation.utils

/**
 * High-fidelity translation dictionaries for Indian and Subcontinent languages.
 * Covers full UI strings across Yashora Reel Generator.
 */
object LocalizationIndian {

    val HINDI_MAP = mapOf(
        "Yashora" to "यशोरा",
        "AI REEL GENERATOR" to "एआई रील जनरेटर",
        "REEL GENERATOR" to "रील जनरेटर",
        "Home" to "होम",
        "AI Tools" to "एआई टूल्स",
        "AI Chat" to "एआई चैट",
        "My Library" to "मेरी लाइब्रेरी",
        "Projects" to "प्रोजेक्ट्स",
        "Saved Scripts" to "सहेजी गई स्क्रिप्ट्स",
        "Export History" to "एक्सपोर्ट इतिहास",
        "Templates" to "टेम्पलेट्स",
        "Premium" to "प्रीमियम",
        "Settings" to "सेटिंग्स",
        "App Settings" to "ऐप सेटिंग्स",
        "Back" to "वापस",
        "Preferences" to "प्राथमिकताएं",
        "App Theme" to "ऐप थीम",
        "App Interface Language" to "ऐप इंटरफ़ेस भाषा",
        "AI Video Generation Language" to "एआई वीडियो जनरेशन भाषा",
        "Voice Engine & ElevenLabs (VoxEleven)" to "वॉयस इंजन और ElevenLabs",
        "AI Smart Source Matchmaker" to "एआई स्मार्ट सोर्स मैचर",
        "Service Status" to "सेवा स्थिति",
        "Service Health & Engine Status" to "सेवा स्थिति व लाइव इंजन स्वास्थ्य",
        "CURRENTLY ACTIVE GENERATION PIPELINE" to "वर्तमान में सक्रिय जनरेशन पाइपलाइन",
        "Script & Story Engine" to "स्क्रिप्ट व स्टोरी इंजन",
        "Video & Media Engine" to "वीडियो व मीडिया इंजन",
        "User-Connected API Keys (Tier 1)" to "यूज़र-कनेक्टेड API कीज़ (Tier 1)",
        "Global System Engines & Fallback (Tier 2 & 3)" to "ग्लोबल सिस्टम इंजन व बैकअप (Tier 2 व 3)",
        "Manage Keys" to "कीज़ प्रबंधित करें",
        "Refresh Health" to "स्वास्थ्य रीफ़्रेश करें",
        "Live AI Reel Studio" to "लाइव एआई रील स्टूडियो",
        "Currently In-Progress" to "वर्तमान में सक्रिय कार्य",
        "Completed Pipeline Tasks" to "पूर्ण हो चुका कार्य",
        "Upcoming Pipeline Queue" to "आगामी कार्य कतार",
        "AI Visual Framing & Scan" to "एआई विज़ुअल फ्रेमिंग व स्कैन",
        "Cancel Generation" to "जनरेशन रद्द करें",
        "Elapsed" to "बीता समय",
        "Remaining" to "बाकी समय",
        "Analyzing Media Frame..." to "मीडिया फ्रेम का विश्लेषण...",
        "Scripting" to "स्क्रिप्टिंग",
        "Image Fetching" to "इमेज व मीडिया फेचिंग",
        "Voice Synthesis" to "वॉयस सिंथेसिस",
        "Video Rendering" to "वीडियो रेंडरिंग",
        "GENERATION PIPELINE FLOW" to "जनरेशन पाइपलाइन फ्लो",
        "LIVE ACTIVE STAGE" to "लाइव सक्रिय चरण",
        "AI Script Architecture & Hook Formulation" to "एआई स्क्रिप्ट आर्किटेक्चर व हुक निर्माण",
        "Curating High-Res Cinematics & Visual Assets" to "हाई-रेज़ सिनेमैटिक्स व विज़ुअल एसेट्स",
        "Neural Voiceover & Emotion Modulation" to "न्यूरल वॉयसओवर व इमोशन मॉड्यूलेशन",
        "Master Video Composition & 1080p Export" to "मास्टर वीडियो कंपोज़िशन व 1080p एक्सपोर्ट",
        "DONE" to "पूर्ण",
        "ACTIVE" to "सक्रिय",
        "QUEUED" to "कतार में",
        "Processing in real-time..." to "रीयल-टाइम प्रोसेसिंग...",
        "Storage & Local Cache" to "स्टोरेज व लोकल कैश",
        "Clear Local Cache & Storage" to "कैश और स्टोरेज साफ़ करें",
        "Legal & About" to "कानूनी व परिचय",
        "Privacy Policy" to "गोपनीयता नीति",
        "Terms & Conditions" to "नियम और शर्तें",
        "About Yashora Reel Generator" to "यशोरा रील जनरेटर के बारे में",
        "Recent Projects" to "हाल के प्रोजेक्ट्स",
        "Create Reel" to "रील बनाएं",
        "Create New Reel" to "नई रील बनाएं",
        "AI Reel Architect" to "एआई रील आर्किटेक्ट",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "स्क्रिप्ट को तुरंत समृद्ध विज़ुअल स्टोरीबोर्ड में बदलें।",
        "AI Script Writer" to "एआई स्क्रिप्ट राइटर",
        "VoxEleven Voice" to "VoxEleven वॉयस",
        "Edit" to "एडिट",
        "Edit Studio" to "एडिट स्टूडियो",
        "Manual Studio" to "मैनुअल स्टूडियो",
        "Manual Studio Pro" to "मैनुअल स्टूडियो प्रो",
        "Learn How It Works" to "यह कैसे काम करता है जानें",
        "Got It!" to "समझ गया!",
        "Configure Reel Pipeline" to "रील पाइपलाइन कॉन्फ़िगर करें",
        "Write / Paste Reel Script" to "रील स्क्रिप्ट लिखें या पेस्ट करें",
        "Generate with AI" to "एआई से जनरेट करें",
        "Select Cinematic Visual Style" to "सिनेमैटिक विज़ुअल स्टाइल चुनें",
        "Select Video Narration Style" to "वीडियो वाचन शैली चुनें",
        "Speech & Video Language" to "वाणी और वीडियो भाषा",
        "Primary Narrator Voice" to "मुख्य वाचक आवाज़",
        "Category / Voice Presets" to "श्रेणी / आवाज़ प्रीसेट्स",
        "Selected: " to "चयनित: ",
        "Selected" to "चयनित",
        "Active" to "सक्रिय",
        "Completed" to "पूर्ण",
        "Rendered" to "तैयार",
        "Saved" to "सहेजा गया",
        "Male" to "पुरुष",
        "Female" to "महिला",
        "Child" to "बालक",
        "Speech Speed: " to "वाणी गति: ",
        "Speech Pitch: " to "वाणी पिच: ",
        "Preview Voice" to "आवाज़ पूर्वावलोकन",
        "Preview Voice Synths" to "सिंथ आवाज़ सुनें",
        "Resolution" to "रिज़ॉल्यूशन",
        "Video Framerate" to "वीडियो फ्रेमरेट",
        "Background Soundtrack Overlay" to "बैकग्राउंड साउंडट्रैक ओवरले",
        "Add smart rhythmic backing beats" to "लयबद्ध बैकग्राउंड बीट्स जोड़ें",
        "Generate Video" to "वीडियो जनरेट करें",
        "Skip & Generate Video" to "छोड़ें और वीडियो बनाएं",
        "Watch 1 Reward Ad to Start Generation" to "जनरेशन शुरू करने के लिए 1 विज्ञापन देखें",
        "Neural Speech & Language Engine" to "न्यूरल स्पीच और भाषा इंजन",
        "TTS Speech Engine" to "टीटीएस स्पीच इंजन",
        "Select TTS compiler engine provider" to "टीटीएस कंपाइलर इंजन प्रदाता चुनें",
        "This controls the spoken accents & subtitles" to "यह बोली और सबटाइटल को नियंत्रित करता है",
        "Reel Layout Canvas Properties" to "रील लेआउट कैनवास गुण",
        "Soundtrack & Audio Controls" to "साउंडट्रैक और ऑडियो नियंत्रण",
        "Visual Timeline Editor" to "विज़ुअल टाइमलाइन एडिटर",
        "Export" to "एक्सपोर्ट",
        "Scene Canvas" to "सीन कैनवास",
        "Add Clip" to "क्लिप जोड़ें",
        "Subtitles" to "सबटाइटल",
        "50+ Filters" to "50+ फ़िल्टर",
        "Overlays" to "ओवरले",
        "Transitions" to "ट्रांज़िशन",
        "AI Background" to "एआई बैकग्राउंड",
        "Split Clip" to "क्लिप विभाजित करें",
        "Add Sticker" to "स्टिकर जोड़ें",
        "Delete Scene" to "सीन हटाएं",
        "Scene" to "सीन",
        "Play" to "चलाएं",
        "Trim" to "काटें",
        "Trim ✂️" to "काटें ✂️",
        "Undo" to "पूर्ववत",
        "Redo" to "पुनः करें",
        "words" to "शब्द",
        "Delete" to "हटाएं",
        "Cancel" to "रद्द करें",
        "Save" to "सहेजें",
        "Copy" to "कॉपी करें",
        "Done" to "पूर्ण",
        "Yes" to "हाँ",
        "No" to "नहीं",
        "Yes, Cancel" to "हाँ, रद्द करें",
        "No, Continue" to "नहीं, जारी रखें",
        "Remove" to "हटाएं",
        "Replace" to "बदलें",
        "REPLACE" to "बदलें",
        "Replace Clip" to "क्लिप बदलें",
        "Replace Asset" to "मीडिया बदलें",
        "Replace Media" to "मीडिया बदलें",
        "Search & Replace Clip" to "सर्च करें और क्लिप बदलें",
        "Search Online Footage & Photos" to "ऑनलाइन वीडियो व फ़ोटो खोजें",
        "Phone Files & Gallery" to "फ़ोन फ़ाइलें व गैलरी",
        "Pick from Phone Gallery" to "फ़ोन गैलरी से चुनें",
        "Pick from Device Storage / Files" to "डिवाइस स्टोरेज से चुनें",
        "Search online footage or pick from device files" to "ऑनलाइन वीडियो खोजें या डिवाइस फ़ाइल से चुनें",
        "Search videos or photos..." to "वीडियो या फ़ोटो खोजें...",
        "Share" to "शेयर करें",
        "Share Reel" to "रील शेयर करें",
        "Share Video" to "वीडियो शेयर करें",
        "Search..." to "खोजें...",
        "Search" to "खोजें",
        "Clear" to "साफ़ करें",
        "No results found" to "कोई परिणाम नहीं मिला",
        "Loading..." to "लोड हो रहा है...",
        "Retry Connection" to "पुनः प्रयास करें",
        "AI Script Generator" to "एआई स्क्रिप्ट जनरेटर",
        "Your AI Generated Script" to "आपकी एआई जनरेटेड स्क्रिप्ट",
        "Saved Scripts History" to "सहेजी गई स्क्रिप्ट्स का इतिहास",
        "Regenerate" to "पुनः जनरेट करें",
        "Regenerate Script Variant" to "नया स्क्रिप्ट वेरिएंट बनाएं",
        "Send to Video Generator" to "वीडियो जनरेटर में भेजें",
        "Write Another Script" to "दूसरी स्क्रिप्ट लिखें",
        "Script Title" to "स्क्रिप्ट शीर्षक",
        "Script Body" to "स्क्रिप्ट बॉडी",
        "Change Script Language" to "स्क्रिप्ट भाषा बदलें",
        "No saved scripts found." to "कोई सहेजी गई स्क्रिप्ट नहीं मिली।",
        "Saved Audio Library" to "सहेजी गई ऑडियो लाइब्रेरी",
        "Generate Voice Clip" to "वॉयस क्लिप बनाएं",
        "Delete Voice Clip?" to "वॉयस क्लिप हटाएं?",
        "Clear All" to "सभी साफ़ करें",
        "Favorites" to "पसंदीदा",
        "No Project Drafts Found" to "कोई प्रोजेक्ट ड्राफ्ट नहीं मिला",
        "No Rendered History" to "कोई एक्सपोर्ट इतिहास नहीं है",
        "Delete Project draft?" to "प्रोजेक्ट ड्राफ्ट हटाएं?",
        "Cancel Generation?" to "जनरेशन रद्द करें?",
        "Cancel Export?" to "एक्सपोर्ट रद्द करें?",
        "Cancel Script Generation?" to "स्क्रिप्ट जनरेशन रद्द करें?",
        "Cancel Download?" to "डाउनलोड रद्द करें?",
        "Downloading Template" to "टेम्पलेट डाउनलोड हो रहा है",
        "Downloading Template..." to "टेम्पलेट डाउनलोड हो रहा है...",
        "Template download cancelled" to "टेम्पलेट डाउनलोड रद्द हुआ",
        "Run in Background" to "बैकग्राउंड में चलाएं",
        "Background enabled" to "बैकग्राउंड सक्षम",
        "Download continuing in background..." to "डाउनलोड बैकग्राउंड में जारी है...",
        "Template loaded into Studio!" to "टेम्पलेट स्टूडियो में लोड हो गया!",
        "Template downloaded! Ready to edit in Studio." to "टेम्पलेट डाउनलोड हुआ! एडिट करने के लिए तैयार।",
        "Light" to "लाइट",
        "Dark" to "डार्क",
        "System" to "सिस्टम डिफ़ॉल्ट",
        "Cyberpunk" to "साइबरपंक",
        "AMOLED Black" to "अमोलेड ब्लैक",
        "Neon" to "नियॉन",
        "Purple" to "पर्पल",
        "Blue" to "ब्लू",
        "Green" to "ग्रीन",
        "Orange" to "ऑरेंज",
        "Red" to "रेड",
        "All Languages" to "सभी भाषाएँ",
        "Popular ⭐" to "लोकप्रिय ⭐",
        "Indian Languages 🇮🇳" to "भारतीय भाषाएँ 🇮🇳",
        "Global 🌐" to "वैश्विक 🌐",
        "Select Language" to "भाषा चुनें",
        "languages available" to "भाषाएं उपलब्ध",
        "Search language (e.g. Hindi, Spanish)..." to "भाषा खोजें (उदा. हिंदी, स्पैनिश)...",
        "No languages match" to "कोई मेल खाती भाषा नहीं मिली",
        "Confirm Cache Clear" to "कैश साफ़ करने की पुष्टि करें",
        "Cache & Storage cleared successfully!" to "कैश और स्टोरेज सफलतापूर्वक साफ़ किया गया!",
        "Clear Cache" to "कैश साफ़ करें",
        "Sign in to backup and sync" to "बैकअप और सिंक के लिए साइन इन करें",
        "Creator Connected" to "क्रिएटर कनेक्टेड",
        "Sign Out" to "साइन आउट करें",
        "Tap to manage account" to "खाता प्रबंधित करने के लिए टैप करें",
        "Open in Studio" to "स्टूडियो में खोलें",
        "Use Template" to "टेम्पलेट उपयोग करें",
        "Trending Presets" to "ट्रेंडिंग प्रीसेट्स",
        "Community Pool 🌐" to "कम्युनिटी पूल 🌐",
        "Join Yashora Community" to "यशोरा कम्युनिटी से जुड़ें",
        "Multi-Layer Audio Timeline" to "मल्टी-लेयर ऑडियो टाइमलाइन",
        "Voiceover Track" to "वॉयसओवर ट्रैक",
        "Music Track (BGM)" to "म्यूजिक ट्रैक (BGM)",
        "SFX & Sound Effects Track" to "साउंड इफेक्ट्स ट्रैक",
        "More Options" to "अधिक विकल्प",
        "Edit Script & Config" to "स्क्रिप्ट और कॉन्फ़िग संपादित करें",
        "Refresh Backdrops" to "बैकड्रॉप्स ताज़ा करें",
        "Watermark Settings" to "वाटरमार्क सेटिंग्स",
        "No Internet Connection" to "इंटरनेट कनेक्शन नहीं है"
    )

    val HINGLISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "AI REEL GENERATOR" to "AI REEL GENERATOR",
        "REEL GENERATOR" to "Reel Generator",
        "Home" to "Home",
        "AI Tools" to "AI Tools",
        "AI Chat" to "AI Chat",
        "My Library" to "My Library",
        "Projects" to "Projects",
        "Saved Scripts" to "Saved Scripts",
        "Export History" to "Export History",
        "Templates" to "Templates",
        "Premium" to "Premium",
        "Settings" to "Settings",
        "App Settings" to "App Settings",
        "Back" to "Wapas",
        "Preferences" to "Preferences",
        "App Theme" to "App Theme",
        "App Interface Language" to "App Interface Language",
        "AI Video Generation Language" to "Video Generation Language",
        "Voice Engine & ElevenLabs (VoxEleven)" to "Voice Engine & ElevenLabs",
        "AI Smart Source Matchmaker" to "AI Smart Matchmaker",
        "Storage & Local Cache" to "Storage & Cache",
        "Clear Local Cache & Storage" to "Cache aur Storage Saaf Karein",
        "Legal & About" to "Legal & About",
        "Privacy Policy" to "Privacy Policy",
        "Terms & Conditions" to "Terms & Conditions",
        "About Yashora Reel Generator" to "About Yashora",
        "Recent Projects" to "Haal ke Projects",
        "Create Reel" to "Reel Banayein",
        "Create New Reel" to "Nayi Reel Banayein",
        "AI Reel Architect" to "AI Reel Architect",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "Scripts ko visual storyboards me convert karein.",
        "AI Script Writer" to "AI Script Writer",
        "VoxEleven Voice" to "VoxEleven Voice",
        "Edit" to "Edit Karein",
        "Edit Studio" to "Edit Studio",
        "Manual Studio" to "Manual Studio",
        "Manual Studio Pro" to "Manual Studio Pro",
        "Learn How It Works" to "Kaise kaam karta hai janein",
        "Got It!" to "Samajh gaya!",
        "Configure Reel Pipeline" to "Pipeline Configure Karein",
        "Write / Paste Reel Script" to "Script Likhein ya Paste Karein",
        "Generate with AI" to "AI Se Generate Karein",
        "Select Cinematic Visual Style" to "Visual Style Chunein",
        "Select Video Narration Style" to "Narration Style Chunein",
        "Speech & Video Language" to "Voice & Video Language",
        "Primary Narrator Voice" to "Main Voice Chunein",
        "Category / Voice Presets" to "Category / Voice Presets",
        "Selected: " to "Chuna gaya: ",
        "Selected" to "Chuna gaya",
        "Active" to "Active",
        "Completed" to "Complete ho gaya",
        "Rendered" to "Render ho gaya",
        "Saved" to "Save ho gaya",
        "Male" to "Purush Voice",
        "Female" to "Mahila Voice",
        "Child" to "Bachhe ki Voice",
        "Speech Speed: " to "Speed: ",
        "Speech Pitch: " to "Pitch: ",
        "Preview Voice" to "Voice Suniye",
        "Preview Voice Synths" to "Preview Suniye",
        "Resolution" to "Resolution",
        "Video Framerate" to "Video Framerate",
        "Background Soundtrack Overlay" to "Background Music",
        "Add smart rhythmic backing beats" to "Smart backing beats jodein",
        "Generate Video" to "Video Banayein",
        "Skip & Generate Video" to "Skip karke Video Banayein",
        "Watch 1 Reward Ad to Start Generation" to "Video banane ke liye 1 Ad dekhein",
        "Visual Timeline Editor" to "Timeline Editor",
        "Export" to "Export Karein",
        "Scene Canvas" to "Scene Canvas",
        "Add Clip" to "Clip Jodein",
        "Subtitles" to "Subtitles",
        "50+ Filters" to "50+ Filters",
        "Overlays" to "Overlays",
        "Transitions" to "Transitions",
        "AI Background" to "AI Background",
        "Split Clip" to "Clip Kaatein",
        "Add Sticker" to "Sticker Jodein",
        "Delete Scene" to "Scene Hatayein",
        "Scene" to "Scene",
        "Play" to "Play Karein",
        "Trim" to "Trim Karein",
        "Trim ✂️" to "Trim Karein ✂️",
        "Undo" to "Undo",
        "Redo" to "Redo",
        "words" to "shabd",
        "Delete" to "Delete Karein",
        "Cancel" to "Cancel Karein",
        "Save" to "Save Karein",
        "Copy" to "Copy Karein",
        "Done" to "Ho Gaya",
        "Yes" to "Haan",
        "No" to "Nahi",
        "Yes, Cancel" to "Haan, Cancel Karein",
        "No, Continue" to "Nahi, Chalne Dein",
        "Remove" to "Hatayein",
        "Replace" to "Badlein",
        "REPLACE" to "Badlein",
        "Replace Clip" to "Clip Badlein",
        "Replace Asset" to "Media Badlein",
        "Replace Media" to "Media Badlein",
        "Share" to "Share Karein",
        "Share Reel" to "Reel Share Karein",
        "Share Video" to "Video Share Karein",
        "Search..." to "Khojein...",
        "Search" to "Search",
        "Clear" to "Clear Karein",
        "No results found" to "Koi result nahi mila",
        "Loading..." to "Load ho raha hai...",
        "Retry Connection" to "Dobara koshish karein",
        "AI Script Generator" to "AI Script Generator",
        "Your AI Generated Script" to "Aapki AI Script",
        "Saved Scripts History" to "Saved Scripts History",
        "Regenerate" to "Dobara Banayein",
        "Send to Video Generator" to "Video Generator me Bhejein",
        "Write Another Script" to "Dusri Script Likhein",
        "All Languages" to "Saari Bhashayein",
        "Popular ⭐" to "Popular ⭐",
        "Indian Languages 🇮🇳" to "Indian Languages 🇮🇳",
        "Global 🌐" to "Global Languages 🌐",
        "Select Language" to "Language Chunein",
        "languages available" to "bhashayein uplabdh",
        "Search language (e.g. Hindi, Spanish)..." to "Language search karein...",
        "No languages match" to "Koi match nahi mila",
        "Confirm Cache Clear" to "Cache saaf karein?",
        "Cache & Storage cleared successfully!" to "Cache safalta se clear ho gaya!",
        "Clear Cache" to "Cache Clear Karein",
        "Sign in to backup and sync" to "Backup ke liye Sign In karein",
        "Creator Connected" to "Creator Connected",
        "Sign Out" to "Sign Out Karein",
        "Open in Studio" to "Studio me Kholein",
        "Use Template" to "Template Use Karein"
    )

    val BENGALI_MAP = mapOf(
        "Yashora" to "যশোরা",
        "AI REEL GENERATOR" to "এআই রিল জেনারেটর",
        "REEL GENERATOR" to "রিল জেনারেটর",
        "Home" to "হোম",
        "AI Tools" to "এআই টুলস",
        "AI Chat" to "এআই চ্যাট",
        "My Library" to "আমার লাইব্রেরি",
        "Projects" to "প্রজেক্টস",
        "Saved Scripts" to "সংরক্ষিত স্ক্রিপ্ট",
        "Export History" to "রপ্তানি ইতিহাস",
        "Templates" to "টেমপ্লেট",
        "Premium" to "প্রিমিয়াম",
        "Settings" to "সেটিংস",
        "App Settings" to "অ্যাপ সেটিংস",
        "Back" to "ফিরে যান",
        "Preferences" to "পছন্দসমূহ",
        "App Theme" to "অ্যাপ থিম",
        "App Interface Language" to "অ্যাপের ভাষা",
        "AI Video Generation Language" to "ভিডিও তৈরির ভাষা",
        "Voice Engine & ElevenLabs (VoxEleven)" to "ভয়েস ইঞ্জিন এবং ইলেভেনল্যাবস",
        "Storage & Local Cache" to "স্টোরেজ ও ক্যাশ",
        "Clear Local Cache & Storage" to "ক্যাশ ও স্টোরেজ মুছুন",
        "Legal & About" to "আইনি ও পরিচিতি",
        "Privacy Policy" to "গোপনীয়তা নীতি",
        "Terms & Conditions" to "শর্তাবলী",
        "About Yashora Reel Generator" to "যশোরা সম্পর্কে",
        "Recent Projects" to "সাম্প্রতিক প্রজেক্ট",
        "Create Reel" to "রিল তৈরি করুন",
        "Create New Reel" to "নতুন রিল তৈরি করুন",
        "AI Reel Architect" to "এআই রিল আর্কিটেক্ট",
        "AI Script Writer" to "এআই স্ক্রিপ্ট লেখক",
        "VoxEleven Voice" to "ভক্সইলেভেন ভয়েস",
        "Edit" to "সম্পাদনা",
        "Edit Studio" to "এডিট স্টুডিও",
        "Manual Studio" to "ম্যানুয়াল স্টুডিও",
        "Learn How It Works" to "এটি কীভাবে কাজ করে জানুন",
        "Got It!" to "বুঝেছি!",
        "Configure Reel Pipeline" to "রিল পাইপলাইন সেটআপ",
        "Write / Paste Reel Script" to "স্ক্রিপ্ট লিখুন বা পেস্ট করুন",
        "Generate with AI" to "এআই দিয়ে তৈরি করুন",
        "Speech & Video Language" to "কথা ও ভিডিওর ভাষা",
        "Primary Narrator Voice" to "মূল কথকের কণ্ঠ",
        "Selected: " to "নির্বাচিত: ",
        "Selected" to "নির্বাচিত",
        "Active" to "সক্রিয়",
        "Completed" to "সম্পন্ন",
        "Rendered" to "রেন্ডার হয়েছে",
        "Saved" to "সংরক্ষিত",
        "Male" to "পুরুষ",
        "Female" to "মহিলা",
        "Child" to "শিশু",
        "Speech Speed: " to "কথার গতি: ",
        "Speech Pitch: " to "কথার সুর: ",
        "Preview Voice" to "কণ্ঠ শুনুন",
        "Resolution" to "রেজোলিউশন",
        "Video Framerate" to "ভিডিও ফ্রেমরেট",
        "Background Soundtrack Overlay" to "ব্যাকগ্রাউন্ড মিউজিক",
        "Generate Video" to "ভিডিও তৈরি করুন",
        "Skip & Generate Video" to "এড়িয়ে যান ও তৈরি করুন",
        "Visual Timeline Editor" to "টাইমলাইন সম্পাদক",
        "Export" to "রপ্তানি করুন",
        "Scene Canvas" to "দৃশ্য ক্যানভাস",
        "Add Clip" to "ক্লিপ যোগ করুন",
        "Subtitles" to "সাবটাইটেল",
        "50+ Filters" to "৫০+ ফিল্টার",
        "Overlays" to "ওভারলে",
        "Transitions" to "ট্রানজিশন",
        "AI Background" to "এআই ব্যাকগ্রাউন্ড",
        "Delete" to "মুছুন",
        "Cancel" to "বাতিল",
        "Save" to "সংরক্ষণ করুন",
        "Copy" to "কপি করুন",
        "Done" to "সম্পন্ন",
        "Yes" to "হ্যাঁ",
        "No" to "না",
        "Share" to "শেয়ার করুন",
        "Share Reel" to "রিল শেয়ার করুন",
        "Search..." to "অনুসন্ধান...",
        "Search" to "খুঁজুন",
        "Clear" to "সাফ করুন",
        "No results found" to "কোনো ফলাফল পাওয়া যায়নি",
        "Loading..." to "লোড হচ্ছে...",
        "AI Script Generator" to "এআই স্ক্রিপ্ট জেনারেটর",
        "Your AI Generated Script" to "আপনার তৈরি স্ক্রিপ্ট",
        "Regenerate" to "পুনরায় তৈরি করুন",
        "Send to Video Generator" to "ভিডিও মেকারে পাঠান",
        "Write Another Script" to "অন্য স্ক্রিপ্ট লিখুন",
        "All Languages" to "সকল ভাষা",
        "Popular ⭐" to "জনপ্রিয় ⭐",
        "Indian Languages 🇮🇳" to "ভারতীয় ভাষা 🇮🇳",
        "Global 🌐" to "আন্তর্জাতিক 🌐",
        "Select Language" to "ভাষা নির্বাচন করুন",
        "Clear Cache" to "ক্যাশ মুছুন",
        "Sign Out" to "সাইন আউট",
        "Open in Studio" to "স্টুডিওতে খুলুন",
        "Use Template" to "টেমপ্লেট ব্যবহার করুন"
    )

    val MARATHI_MAP = mapOf(
        "Yashora" to "यशोरा",
        "AI REEL GENERATOR" to "एआय रील जनरेटर",
        "REEL GENERATOR" to "रील जनरेटर",
        "Home" to "होम",
        "AI Tools" to "एआय टूल्स",
        "AI Chat" to "एआय चॅट",
        "My Library" to "माझी लायब्ररी",
        "Projects" to "प्रकल्प",
        "Saved Scripts" to "जतन केलेल्या स्क्रिप्ट्स",
        "Export History" to "एक्सपोर्ट इतिहास",
        "Templates" to "टेम्पलेट्स",
        "Premium" to "प्रीमियम",
        "Settings" to "सेटिंग्ज",
        "App Settings" to "अ‍ॅप सेटिंग्ज",
        "Back" to "मागे",
        "Preferences" to "प्राधान्ये",
        "App Theme" to "अ‍ॅप थीम",
        "App Interface Language" to "अ‍ॅप भाषा",
        "AI Video Generation Language" to "व्हिडिओ निर्मिती भाषा",
        "Voice Engine & ElevenLabs (VoxEleven)" to "व्हॉइस इंजिन आणि ElevenLabs",
        "Storage & Local Cache" to "स्टोरेज आणि कॅश",
        "Clear Local Cache & Storage" to "कॅश आणि स्टोरेज साफ करा",
        "Legal & About" to "कायदेशीर माहिती",
        "Privacy Policy" to "गोपनीयता धोरण",
        "Terms & Conditions" to "नियम आणि अटी",
        "Recent Projects" to "अलीकडील प्रकल्प",
        "Create Reel" to "रील तयार करा",
        "Create New Reel" to "नवीन रील बनवा",
        "AI Reel Architect" to "एआय रील आर्किटेक्ट",
        "AI Script Writer" to "एआय स्क्रिप्ट लेखक",
        "Edit" to "संपादित करा",
        "Learn How It Works" to "हे कसे कार्य करते ते शिका",
        "Got It!" to "समजले!",
        "Write / Paste Reel Script" to "स्क्रिप्ट लिहा किंवा पेस्ट करा",
        "Generate with AI" to "एआय सह तयार करा",
        "Speech & Video Language" to "आवाज आणि व्हिडिओ भाषा",
        "Primary Narrator Voice" to "मुख्य निवेदक आवाज",
        "Selected: " to "निवडलेले: ",
        "Selected" to "निवडलेले",
        "Male" to "पुरुष",
        "Female" to "स्त्री",
        "Child" to "मुलगा/मुलगी",
        "Speech Speed: " to "आवाजाचा वेग: ",
        "Speech Pitch: " to "आवाजाचा स्तर: ",
        "Preview Voice" to "आवाज ऐका",
        "Resolution" to "रिझोल्यूशन",
        "Background Soundtrack Overlay" to "पार्श्वसंगीत",
        "Generate Video" to "व्हिडिओ तयार करा",
        "Skip & Generate Video" to "वगळा आणि व्हिडिओ बनवा",
        "Visual Timeline Editor" to "टाइमलाइन संपादक",
        "Export" to "एक्सपोर्ट करा",
        "Scene Canvas" to "सीन कॅनव्हास",
        "Add Clip" to "क्लिप जोडा",
        "Subtitles" to "उपशीर्षके",
        "50+ Filters" to "50+ फिल्टर्स",
        "Delete" to "हटवा",
        "Cancel" to "रद्द करा",
        "Save" to "जतन करा",
        "Copy" to "कॉपी करा",
        "Done" to "पूर्ण",
        "Yes" to "होय",
        "No" to "नाही",
        "Share" to "शेअर करा",
        "Share Reel" to "रील शेअर करा",
        "Search..." to "शोधा...",
        "Search" to "शोधा",
        "Clear" to "साफ करा",
        "Loading..." to "लोड होत आहे...",
        "All Languages" to "सर्व भाषा",
        "Popular ⭐" to "लोकप्रिय ⭐",
        "Indian Languages 🇮🇳" to "भारतीय भाषा 🇮🇳",
        "Global 🌐" to "जागतिक 🌐",
        "Select Language" to "भाषा निवडा",
        "Clear Cache" to "कॅश साफ करा",
        "Sign Out" to "साइन आउट",
        "Open in Studio" to "स्टुडिओमध्ये उघडा",
        "Use Template" to "टेम्पलेट वापरा"
    )

    val TELUGU_MAP = mapOf(
        "Yashora" to "యశోర",
        "AI REEL GENERATOR" to "AI రీల్ జనరేటర్",
        "REEL GENERATOR" to "రీల్ జనరేటర్",
        "Home" to "హోమ్",
        "AI Tools" to "AI టూల్స్",
        "AI Chat" to "AI చాట్",
        "My Library" to "నా లైబ్రరీ",
        "Projects" to "ప్రాజెక్ట్‌లు",
        "Saved Scripts" to "సేవ్ చేసిన స్క్రిప్ట్‌లు",
        "Export History" to "ఎగుమతి చరిత్ర",
        "Templates" to "టెంప్లేట్లు",
        "Premium" to "ప్రీమియం",
        "Settings" to "సెట్టింగ్‌లు",
        "App Settings" to "యాప్ సెట్టింగ్‌లు",
        "Back" to "వెనుకకు",
        "Preferences" to "ప్రాధాన్యతలు",
        "App Theme" to "యాప్ థీమ్",
        "App Interface Language" to "యాప్ ఇంటర్‌ఫేస్ భాష",
        "AI Video Generation Language" to "వీడియో తయారీ భాష",
        "Voice Engine & ElevenLabs (VoxEleven)" to "వాయిస్ ఇంజిన్ & ElevenLabs",
        "Storage & Local Cache" to "నిల్వ & కాష్",
        "Clear Local Cache & Storage" to "కాష్ మరియు నిల్వను క్లియర్ చేయండి",
        "Legal & About" to "చట్టపరమైన సమాచారం",
        "Privacy Policy" to "గోప్యతా విధానం",
        "Terms & Conditions" to "నిబంధనలు & షరతులు",
        "Recent Projects" to "ఇటీవలి ప్రాజెక్ట్‌లు",
        "Create Reel" to "రీల్ సృష్టించండి",
        "Create New Reel" to "కొత్త రీల్ చేయండి",
        "AI Reel Architect" to "AI రీల్ ఆర్కిటెక్ట్",
        "AI Script Writer" to "AI స్క్రిప్ట్ రైటర్",
        "Edit" to "సవరించండి",
        "Learn How It Works" to "ఇది ఎలా పనిచేస్తుందో తెలుసుకోండి",
        "Got It!" to "అర్థమైంది!",
        "Write / Paste Reel Script" to "స్క్రిప్ట్ రాయండి లేదా పేస్ట్ చేయండి",
        "Generate with AI" to "AI తో రూపొందించండి",
        "Speech & Video Language" to "వాయిస్ & వీడియో భాష",
        "Primary Narrator Voice" to "ప్రధాన వ్యాఖ్యాత స్వరం",
        "Selected: " to "ఎంపిక చేయబడింది: ",
        "Selected" to "ఎంచుకోబడింది",
        "Male" to "పురుషుడు",
        "Female" to "స్త్రీ",
        "Child" to "పిల్లలు",
        "Speech Speed: " to "వాయిస్ వేగం: ",
        "Speech Pitch: " to "వాయిస్ పిచ్: ",
        "Preview Voice" to "స్వరాన్ని వినండి",
        "Resolution" to "రిజల్యూషన్",
        "Background Soundtrack Overlay" to "నేపథ్య సంగీతం",
        "Generate Video" to "వీడియోను రూపొందించండి",
        "Skip & Generate Video" to "దాటవేసి వీడియో చేయండి",
        "Visual Timeline Editor" to "టైమ్‌లైన్ ఎడిటర్",
        "Export" to "ఎగుమతి చేయండి",
        "Scene Canvas" to "సీన్ కాన్వాస్",
        "Add Clip" to "క్లిప్ జోడించండి",
        "Subtitles" to "సబ్‌టైటిల్స్",
        "50+ Filters" to "50+ ఫిల్టర్లు",
        "Delete" to "తొలగించు",
        "Cancel" to "రద్దు చేయి",
        "Save" to "భద్రపరుచు",
        "Copy" to "కాపీ చేయి",
        "Done" to "పూర్తయింది",
        "Yes" to "అవును",
        "No" to "కాదు",
        "Share" to "భాగస్వామ్యం చేయండి",
        "Share Reel" to "రీల్ షేర్ చేయండి",
        "Search..." to "శోధించండి...",
        "Search" to "శోధన",
        "Clear" to "క్లియర్",
        "Loading..." to "లోడ్ అవుతోంది...",
        "All Languages" to "అన్ని భాషలు",
        "Popular ⭐" to "జనాదరణ పొందినవి ⭐",
        "Indian Languages 🇮🇳" to "భారతీయ భాషలు 🇮🇳",
        "Global 🌐" to "ప్రపంచ భాషలు 🌐",
        "Select Language" to "భాషను ఎంచుకోండి",
        "Clear Cache" to "కాష్ క్లియర్ చేయండి",
        "Sign Out" to "సైన్ అవుట్",
        "Open in Studio" to "స్టూడియోలో తెరవండి",
        "Use Template" to "టెంప్లేట్ వాడండి"
    )

    val TAMIL_MAP = mapOf(
        "Yashora" to "யஷோரா",
        "AI REEL GENERATOR" to "AI ரீல் ஜெனரேட்டர்",
        "REEL GENERATOR" to "ரீல் ஜெனரேட்டர்",
        "Home" to "முகப்பு",
        "AI Tools" to "AI கருவிகள்",
        "AI Chat" to "AI சாட்",
        "My Library" to "என் நூலகம்",
        "Projects" to "திட்டங்கள்",
        "Saved Scripts" to "சேமிக்கப்பட்ட ஸ்கிரிப்டுகள்",
        "Export History" to "ஏற்றுமதி வரலாறு",
        "Templates" to "டெம்ப்ளேட்டுகள்",
        "Premium" to "பிரீமியம்",
        "Settings" to "அமைப்புகள்",
        "App Settings" to "செயலி அமைப்புகள்",
        "Back" to "பின்னே செல்",
        "Preferences" to "விருப்பங்கள்",
        "App Theme" to "செயலி தீம்",
        "App Interface Language" to "பயன்பாட்டு மொழி",
        "AI Video Generation Language" to "வீடியோ தயாரிப்பு மொழி",
        "Voice Engine & ElevenLabs (VoxEleven)" to "குரல் என்ஜின் & ElevenLabs",
        "Storage & Local Cache" to "சேமிப்பகம் மற்றும் கேச்",
        "Clear Local Cache & Storage" to "கேச் மற்றும் நினைவகத்தை அழிக்கவும்",
        "Legal & About" to "சட்டம் & தகவல்",
        "Privacy Policy" to "தனியுரிமைக் கொள்கை",
        "Terms & Conditions" to "விதிமுறைகள் & நிபந்தனைகள்",
        "Recent Projects" to "சமீபத்திய திட்டங்கள்",
        "Create Reel" to "ரீல் உருவாக்கு",
        "Create New Reel" to "புதிய ரீல் உருவாக்கு",
        "AI Reel Architect" to "AI ரீல் ஆர்க்கிடெக்ட்",
        "AI Script Writer" to "AI ஸ்கிரிப்ட் எழுத்தாளர்",
        "Edit" to "திருத்து",
        "Learn How It Works" to "இது எவ்வாறு செயல்படுகிறது என அறியவும்",
        "Got It!" to "புரிந்தது!",
        "Write / Paste Reel Script" to "ஸ்கிரிப்ட் எழுதவும் அல்லது ஒட்டவும்",
        "Generate with AI" to "AI மூலம் உருவாக்கு",
        "Speech & Video Language" to "பேச்சு & வீடியோ மொழி",
        "Primary Narrator Voice" to "முதன்மை குரல்",
        "Selected: " to "தேர்ந்தெடுக்கப்பட்டது: ",
        "Selected" to "தேர்ந்தெடுக்கப்பட்டது",
        "Male" to "ஆண்",
        "Female" to "பெண்",
        "Child" to "குழந்தை",
        "Speech Speed: " to "குரல் வேகம்: ",
        "Speech Pitch: " to "குரல் சுருதி: ",
        "Preview Voice" to "குரலைக் கேட்கவும்",
        "Resolution" to "தெளிவுத்திறன்",
        "Background Soundtrack Overlay" to "பின்னணி இசை",
        "Generate Video" to "வீடியோவை உருவாக்கு",
        "Skip & Generate Video" to "தவிர்த்து வீடியோ உருவாக்கு",
        "Visual Timeline Editor" to "டைம்லைன் எடிட்டர்",
        "Export" to "ஏற்றுமதி செய்",
        "Scene Canvas" to "காட்சி கேன்வாஸ்",
        "Add Clip" to "கிளிப் சேர்",
        "Subtitles" to "துணைத்தலைப்புகள்",
        "50+ Filters" to "50+ வடிகட்டிகள்",
        "Delete" to "நீக்கு",
        "Cancel" to "ரத்து செய்",
        "Save" to "சேமி",
        "Copy" to "நகலெடு",
        "Done" to "முடிந்தது",
        "Yes" to "ஆம்",
        "No" to "இல்லை",
        "Share" to "பகிர்",
        "Share Reel" to "ரீல் பகிரவும்",
        "Search..." to "தேடு...",
        "Search" to "தேடுக",
        "Clear" to "அழி",
        "Loading..." to "ஏற்றுகிறது...",
        "All Languages" to "அனைத்து மொழிகள்",
        "Popular ⭐" to "பிரபலமானவை ⭐",
        "Indian Languages 🇮🇳" to "இந்திய மொழிகள் 🇮🇳",
        "Global 🌐" to "உலகளாவிய மொழிகள் 🌐",
        "Select Language" to "மொழியைத் தேர்ந்தெடுக்கவும்",
        "Clear Cache" to "கேச் அழிக்கவும்",
        "Sign Out" to "வெளியேறு",
        "Open in Studio" to "ஸ்டுடியோவில் திறக்கவும்",
        "Use Template" to "டெம்ப்ளேட்டைப் பயன்படுத்து"
    )

    val GUJARATI_MAP = mapOf(
        "Yashora" to "યશોરા",
        "AI REEL GENERATOR" to "AI રીલ જનરેટર",
        "REEL GENERATOR" to "રીલ જનરેટર",
        "Home" to "હોમ",
        "AI Tools" to "AI ટૂલ્સ",
        "AI Chat" to "AI ચેટ",
        "My Library" to "મારી લાઇબ્રેરી",
        "Projects" to "પ્રોજેક્ટ્સ",
        "Saved Scripts" to "સાચવેલી સ્ક્રિપ્ટો",
        "Export History" to "નિકાસ ઇતિહાસ",
        "Templates" to "ટેમ્પલેટો",
        "Premium" to "પ્રીમિયમ",
        "Settings" to "સેટિંગ્સ",
        "App Settings" to "એપ સેટિંગ્સ",
        "Back" to "પાછા જાઓ",
        "Preferences" to "પસંદગીઓ",
        "App Theme" to "એપ થીમ",
        "App Interface Language" to "એપ ભાષા",
        "AI Video Generation Language" to "વિડિઓ નિર્માણ ભાષા",
        "Voice Engine & ElevenLabs (VoxEleven)" to "વોઇસ એન્જિન અને ElevenLabs",
        "Storage & Local Cache" to "સ્ટોરેજ અને કેશ",
        "Clear Local Cache & Storage" to "કેશ અને સ્ટોરેજ સાફ કરો",
        "Recent Projects" to "તાજેતરના પ્રોજેક્ટ્સ",
        "Create Reel" to "રીલ બનાવો",
        "Create New Reel" to "નવી રીલ બનાવો",
        "AI Reel Architect" to "AI રીલ આર્કિટેક્ટ",
        "AI Script Writer" to "AI સ્ક્રિપ્ટ રાઇટર",
        "Edit" to "સંપાદિત કરો",
        "Learn How It Works" to "આ કેવી રીતે કાર્ય કરે છે તે જાણો",
        "Got It!" to "સમજાઈ ગયું!",
        "Write / Paste Reel Script" to "સ્ક્રિપ્ટ લખો અથવા પેસ્ટ કરો",
        "Generate with AI" to "AI વડે બનાવો",
        "Speech & Video Language" to "વાણી અને વિડિઓ ભાષા",
        "Primary Narrator Voice" to "મુખ્ય અવાજ",
        "Selected: " to "પસંદ કરેલ: ",
        "Selected" to "પસંદ કરેલ",
        "Male" to "પુરુષ",
        "Female" to "સ્ત્રી",
        "Child" to "બાળક",
        "Speech Speed: " to "વાણીની ગતિ: ",
        "Speech Pitch: " to "વાણીનો સૂર: ",
        "Preview Voice" to "અવાજ સાંભળો",
        "Resolution" to "રિઝોલ્યુશન",
        "Background Soundtrack Overlay" to "બેકગ્રાઉન્ડ સંગીત",
        "Generate Video" to "વિડિઓ બનાવો",
        "Skip & Generate Video" to "છોડો અને વિડિઓ બનાવો",
        "Visual Timeline Editor" to "ટાઇમલાઇન એડિટર",
        "Export" to "નિકાસ કરો",
        "Scene Canvas" to "સીન કેનવાસ",
        "Add Clip" to "ક્લિપ ઉમેરો",
        "Subtitles" to "સબટાઈટલ",
        "50+ Filters" to "50+ ફિલ્ટર્સ",
        "Delete" to "કાઢી નાખો",
        "Cancel" to "રદ કરો",
        "Save" to "સાચવો",
        "Copy" to "કૉપિ કરો",
        "Done" to "પૂર્ણ",
        "Yes" to "હા",
        "No" to "ના",
        "Share" to "શેર કરો",
        "Share Reel" to "રીલ શેર કરો",
        "Search..." to "શોધો...",
        "Search" to "શોધ",
        "Clear" to "સાફ કરો",
        "Loading..." to "લોડ થઈ રહ્યું છે...",
        "All Languages" to "તમામ ભાષાઓ",
        "Popular ⭐" to "લોકપ્રિય ⭐",
        "Indian Languages 🇮🇳" to "ભારતીય ભાષાઓ 🇮🇳",
        "Global 🌐" to "વૈશ્વિક 🌐",
        "Select Language" to "ભાષા પસંદ કરો",
        "Clear Cache" to "કેશ સાફ કરો",
        "Sign Out" to "સાઇન આઉટ",
        "Open in Studio" to "સ્ટુડિયોમાં ખોલો",
        "Use Template" to "ટેમ્પલેટ વાપરો"
    )

    val URDU_MAP = mapOf(
        "Yashora" to "یشورا",
        "AI REEL GENERATOR" to "اے آئی ریل جنریٹر",
        "REEL GENERATOR" to "ریل جنریٹر",
        "Home" to "ہوم",
        "AI Tools" to "اے آئی ٹولز",
        "AI Chat" to "اے آئی چیٹ",
        "My Library" to "میری لائبریری",
        "Projects" to "پروجیکٹس",
        "Saved Scripts" to "محفوظ شدہ اسکرپٹس",
        "Export History" to "ایکسپورٹ تاریخ",
        "Templates" to "ٹیمپلیٹس",
        "Premium" to "پریمیم",
        "Settings" to "ترتیبات",
        "App Settings" to "ایپ کی ترتیبات",
        "Back" to "واپس",
        "Preferences" to "ترجیحات",
        "App Theme" to "ایپ تھیم",
        "App Interface Language" to "ایپ کی زبان",
        "AI Video Generation Language" to "ویڈیو جنریشن کی زبان",
        "Voice Engine & ElevenLabs (VoxEleven)" to "وائس انجن اور ElevenLabs",
        "Storage & Local Cache" to "اسٹوریج اور کیش",
        "Clear Local Cache & Storage" to "کیش اور اسٹوریج صاف کریں",
        "Recent Projects" to "حالیہ پروجیکٹس",
        "Create Reel" to "ریل بنائیں",
        "Create New Reel" to "نئی ریل بنائیں",
        "AI Reel Architect" to "اے آئی ریل آرکیٹیکٹ",
        "AI Script Writer" to "اے آئی اسکرپٹ رائٹر",
        "Edit" to "ترمیم کریں",
        "Learn How It Works" to "یہ کیسے کام کرتا ہے جانیں",
        "Got It!" to "سمجھ آ گیا!",
        "Write / Paste Reel Script" to "اسکرپٹ لکھیں یا پیسٹ کریں",
        "Generate with AI" to "اے آئی سے بنائیں",
        "Speech & Video Language" to "آواز اور ویڈیو کی زبان",
        "Primary Narrator Voice" to "مرکزی آواز",
        "Selected: " to "منتخب کردہ: ",
        "Selected" to "منتخب",
        "Male" to "مردانہ آواز",
        "Female" to "زنانی آواز",
        "Child" to "بچے کی آواز",
        "Speech Speed: " to "آواز کی رفتار: ",
        "Speech Pitch: " to "آواز کا سُر: ",
        "Preview Voice" to "آواز سنیں",
        "Resolution" to "ریزولیوشن",
        "Background Soundtrack Overlay" to "پس منظر کی موسیقی",
        "Generate Video" to "ویڈیو بنائیں",
        "Skip & Generate Video" to "چھوڑیں اور ویڈیو بنائیں",
        "Visual Timeline Editor" to "ٹائم لائن ایڈیٹر",
        "Export" to "ایکسپورٹ کریں",
        "Scene Canvas" to "منظر کینوس",
        "Add Clip" to "کلپ شامل کریں",
        "Subtitles" to "سب ٹائٹلز",
        "50+ Filters" to "50+ فلٹرز",
        "Delete" to "حذف کریں",
        "Cancel" to "منسوخ کریں",
        "Save" to "محفوظ کریں",
        "Copy" to "کاپی کریں",
        "Done" to "مکمل",
        "Yes" to "ہاں",
        "No" to "نہیں",
        "Share" to "شیئر کریں",
        "Share Reel" to "ریل شیئر کریں",
        "Search..." to "تلاش کریں...",
        "Search" to "تلاش",
        "Clear" to "صاف کریں",
        "Loading..." to "لوڈ ہو رہا ہے...",
        "All Languages" to "تمام زبانیں",
        "Popular ⭐" to "مقبول ⭐",
        "Indian Languages 🇮🇳" to "ہندوستانی زبانیں 🇮🇳",
        "Global 🌐" to "عالمی زبانیں 🌐",
        "Select Language" to "زبان منتخب کریں",
        "Clear Cache" to "کیش صاف کریں",
        "Sign Out" to "سائن آؤٹ",
        "Open in Studio" to "اسٹوڈیو میں کھولیں",
        "Use Template" to "ٹیمپلیٹ استعمال کریں"
    )

    val KANNADA_MAP = mapOf(
        "Yashora" to "ಯಶೋರ",
        "AI REEL GENERATOR" to "AI ರೀಲ್ ಜನರೇಟರ್",
        "REEL GENERATOR" to "ರೀಲ್ ಜನರೇಟರ್",
        "Home" to "ಮುಖಪುಟ",
        "AI Tools" to "AI ಪರಿಕರಗಳು",
        "AI Chat" to "AI ಚಾಟ್",
        "My Library" to "ನನ್ನ ಗ್ರಂಥಾಲಯ",
        "Projects" to "ಯೋಜನೆಗಳು",
        "Saved Scripts" to "ಉಳಿಸಿದ ಸ್ಕ್ರಿಪ್ಟ್‌ಗಳು",
        "Export History" to "ರಫ್ತು ಇತಿಹಾಸ",
        "Templates" to "ಟೆಂಪ್ಲೇಟ್‌ಗಳು",
        "Premium" to "ಪ್ರೀಮಿಯಂ",
        "Settings" to "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "App Settings" to "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "Back" to "ಹಿಂದಕ್ಕೆ",
        "Preferences" to "ಆದ್ಯತೆಗಳು",
        "App Theme" to "ಅಪ್ಲಿಕೇಶನ್ ಥೀಮ್",
        "App Interface Language" to "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
        "AI Video Generation Language" to "ವೀಡಿಯೊ ರಚನೆ ಭಾಷೆ",
        "Storage & Local Cache" to "ಸಂಗ್ರಹಣೆ ಮತ್ತು ಕ್ಯಾಶ್",
        "Clear Local Cache & Storage" to "ಕ್ಯಾಶ್ ಮತ್ತು ಸಂಗ್ರಹಣೆಯನ್ನು ತೆರವುಗೊಳಿಸಿ",
        "Recent Projects" to "ಇತ್ತೀಚಿನ ಯೋಜನೆಗಳು",
        "Create Reel" to "ರೀಲ್ ರಚಿಸಿ",
        "Create New Reel" to "ಹೊಸ ರೀಲ್ ಮಾಡಿ",
        "AI Reel Architect" to "AI ರೀಲ್ ಆರ್ಕಿಟೆಕ್ಟ್",
        "AI Script Writer" to "AI ಸ್ಕ್ರಿಪ್ಟ್ ಬರಹಗಾರ",
        "Edit" to "ಸಂಪಾದಿಸಿ",
        "Learn How It Works" to "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ತಿಳಿಯಿರಿ",
        "Got It!" to "ತಿಳಿಯಿತು!",
        "Write / Paste Reel Script" to "ಸ್ಕ್ರಿಪ್ಟ್ ಬರೆಯಿರಿ ಅಥವಾ ಅಂಟಿಸಿ",
        "Generate with AI" to "AI ನೊಂದಿಗೆ ರಚಿಸಿ",
        "Speech & Video Language" to "ಧ್ವನಿ ಮತ್ತು ವೀಡಿಯೊ ಭಾಷೆ",
        "Primary Narrator Voice" to "ಮುಖ್ಯ ನಿರೂಪಕ ಧ್ವನಿ",
        "Selected: " to "ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ: ",
        "Selected" to "ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ",
        "Male" to "ಪುರುಷ",
        "Female" to "ಮಹಿಳೆ",
        "Child" to "ಮಗು",
        "Speech Speed: " to "ಧ್ವನಿ ವೇಗ: ",
        "Speech Pitch: " to "ಧ್ವನಿ ಶ್ರುತಿ: ",
        "Preview Voice" to "ಧ್ವನಿ ಆಲಿಸಿ",
        "Resolution" to "ರೆಸಲ್ಯೂಶನ್",
        "Background Soundtrack Overlay" to "ಹಿನ್ನೆಲೆ ಸಂಗೀತ",
        "Generate Video" to "ವೀಡಿಯೊ ರಚಿಸಿ",
        "Skip & Generate Video" to "ಬಿಟ್ಟುಬಿಡಿ ಮತ್ತು ವೀಡಿಯೊ ರಚಿಸಿ",
        "Visual Timeline Editor" to "ಟೈಮ್‌ಲೈನ್ ಸಂಪಾದಕ",
        "Export" to "ರಫ್ತು ಮಾಡಿ",
        "Scene Canvas" to "ದೃಶ್ಯ ಕ್ಯಾನ್ವಾಸ್",
        "Add Clip" to "ಕ್ಲಿಪ್ ಸೇರಿಸಿ",
        "Subtitles" to "ಉಪಶೀರ್ಷಿಕೆಗಳು",
        "50+ Filters" to "50+ ಫಿಲ್ಟರ್‌ಗಳು",
        "Delete" to "ಅಳಿಸಿ",
        "Cancel" to "ರದ್ದುಮಾಡಿ",
        "Save" to "ಉಳಿಸಿ",
        "Copy" to "ನಕಲಿಸಿ",
        "Done" to "ಮುಗಿದಿದೆ",
        "Yes" to "ಹೌದು",
        "No" to "ಇಲ್ಲ",
        "Share" to "ಹಂಚಿಕೊಳ್ಳಿ",
        "Share Reel" to "ರೀಲ್ ಹಂಚಿಕೊಳ್ಳಿ",
        "Search..." to "ಹುಡುಕಿ...",
        "Search" to "ಹುಡುಕಾಟ",
        "Clear" to "ತೆರವುಗೊಳಿಸಿ",
        "Loading..." to "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        "All Languages" to "ಎಲ್ಲಾ ಭಾಷೆಗಳು",
        "Popular ⭐" to "ಜನಪ್ರಿಯ ⭐",
        "Indian Languages 🇮🇳" to "ಭಾರತೀಯ ಭಾಷೆಗಳು 🇮🇳",
        "Global 🌐" to "ಜಾಗತಿಕ ಭಾಷೆಗಳು 🌐",
        "Select Language" to "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "Clear Cache" to "ಕ್ಯಾಶ್ ತೆರವುಗೊಳಿಸಿ",
        "Sign Out" to "ಸೈನ್ ಔಟ್",
        "Open in Studio" to "ಸ್ಟುಡಿಯೋದಲ್ಲಿ ತೆರೆಯಿರಿ",
        "Use Template" to "ಟೆಂಪ್ಲೇಟ್ ಬಳಸಿ"
    )

    val MALAYALAM_MAP = mapOf(
        "Yashora" to "യശോറ",
        "AI REEL GENERATOR" to "AI റീൽ ജനറേറ്റർ",
        "REEL GENERATOR" to "റീൽ ജനറേറ്റർ",
        "Home" to "ഹോം",
        "AI Tools" to "AI ടൂളുകൾ",
        "AI Chat" to "AI ചാറ്റ്",
        "My Library" to "എന്റെ ലൈബ്രറി",
        "Projects" to "പ്രോജക്ടുകൾ",
        "Saved Scripts" to "സേവ് ചെയ്ത സ്ക്രിപ്റ്റുകൾ",
        "Export History" to "എക്സ്പോർട്ട് ചരിത്രം",
        "Templates" to "ടെംപ്ലേറ്റുകൾ",
        "Premium" to "പ്രീമിയം",
        "Settings" to "ക്രമീകരണങ്ങൾ",
        "App Settings" to "ആപ്പ് ക്രമീകരണങ്ങൾ",
        "Back" to "തിരികെ",
        "Preferences" to "മുൻഗണനകൾ",
        "App Theme" to "ആപ്പ് തീം",
        "App Interface Language" to "ആപ്പ് ഭാഷ",
        "AI Video Generation Language" to "വീഡിയോ നിർമ്മാണ ഭാഷ",
        "Storage & Local Cache" to "സംഭരണവും കാഷെയും",
        "Clear Local Cache & Storage" to "കാഷെയും സംഭരണവും മായ്‌ക്കുക",
        "Recent Projects" to "സമീപകാല പ്രോജക്ടുകൾ",
        "Create Reel" to "റീൽ നിർമ്മിക്കുക",
        "Create New Reel" to "പുതിയ റീൽ ഉണ്ടാക്കുക",
        "AI Reel Architect" to "AI റീൽ ആർക്കിടെക്റ്റ്",
        "AI Script Writer" to "AI സ്ക്രിപ്റ്റ് എഴുത്തുകാരൻ",
        "Edit" to "എഡിറ്റ് ചെയ്യുക",
        "Learn How It Works" to "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നുവെന്ന് അറിയുക",
        "Got It!" to "മനസ്സിലായി!",
        "Write / Paste Reel Script" to "സ്ക്രിപ്റ്റ് എഴുതുക അല്ലെങ്കിൽ ഒട്ടിക്കുക",
        "Generate with AI" to "AI ഉപയോഗിച്ച് നിർമ്മിക്കുക",
        "Speech & Video Language" to "ശബ്ദവും വീഡിയോ ഭാഷയും",
        "Primary Narrator Voice" to "പ്രധാന ശബ്ദം",
        "Selected: " to "തിരഞ്ഞെടുത്തത്: ",
        "Selected" to "തിരഞ്ഞെടുത്തു",
        "Male" to "പുരുഷൻ",
        "Female" to "സ്ത്രീ",
        "Child" to "കുട്ടി",
        "Speech Speed: " to "ശബ്ദ വേഗത: ",
        "Speech Pitch: " to "ശബ്ദ പിച്ച്: ",
        "Preview Voice" to "ശബ്ദം കേൾക്കുക",
        "Resolution" to "റെസല്യൂഷൻ",
        "Background Soundtrack Overlay" to "പശ്ചാത്തല സംഗീതം",
        "Generate Video" to "വീഡിയോ നിർമ്മിക്കുക",
        "Skip & Generate Video" to "ഒഴിവാക്കി വീഡിയോ ഉണ്ടാക്കുക",
        "Visual Timeline Editor" to "ടൈംലൈൻ എഡിറ്റർ",
        "Export" to "എക്സ്പോർട്ട് ചെയ്യുക",
        "Scene Canvas" to "സീൻ ക്യാൻവാസ്",
        "Add Clip" to "ക്ലിപ്പ് ചേർക്കുക",
        "Subtitles" to "സബ്‌ടൈറ്റിലുകൾ",
        "50+ Filters" to "50+ ഫിൽട്ടറുകൾ",
        "Delete" to "ഡിലീറ്റ് ചെയ്യുക",
        "Cancel" to "റദ്ദാക്കുക",
        "Save" to "സേവ് ചെയ്യുക",
        "Copy" to "കോപ്പി ചെയ്യുക",
        "Done" to "പൂർത്തിയായി",
        "Yes" to "അതെ",
        "No" to "അല്ല",
        "Share" to "പങ്കിടുക",
        "Share Reel" to "റീൽ പങ്കിടുക",
        "Search..." to "തിരയുക...",
        "Search" to "തിരയുക",
        "Clear" to "മായ്ക്കുക",
        "Loading..." to "ലോഡ് ചെയ്യുന്നു...",
        "All Languages" to "എല്ലാ ഭാഷകളും",
        "Popular ⭐" to "ജനപ്രിയം ⭐",
        "Indian Languages 🇮🇳" to "ഇന്ത്യൻ ഭാഷകൾ 🇮🇳",
        "Global 🌐" to "ആഗോള ഭാഷകൾ 🌐",
        "Select Language" to "ഭാഷ തിരഞ്ഞെടുക്കുക",
        "Clear Cache" to "കാഷെ മായ്ക്കുക",
        "Sign Out" to "സൈൻ ഔട്ട്",
        "Open in Studio" to "സ്റ്റുഡിയോയിൽ തുറക്കുക",
        "Use Template" to "ടെംപ്ലേറ്റ് ഉപയോഗിക്കുക"
    )

    val PUNJABI_MAP = mapOf(
        "Yashora" to "ਯਸ਼ੋਰਾ",
        "AI REEL GENERATOR" to "AI ਰੀਲ ਜਨਰੇਟਰ",
        "REEL GENERATOR" to "ਰੀਲ ਜਨਰੇਟਰ",
        "Home" to "ਹੋਮ",
        "AI Tools" to "AI ਟੂਲਸ",
        "AI Chat" to "AI ਚੈਟ",
        "My Library" to "ਮੇਰੀ ਲਾਇਬ੍ਰੇਰੀ",
        "Projects" to "ਪ੍ਰੋਜੈਕਟਸ",
        "Saved Scripts" to "ਸੰਭਾਲੀਆਂ ਸਕ੍ਰਿਪਟਾਂ",
        "Export History" to "ਐਕਸਪੋਰਟ ਇਤਿਹਾਸ",
        "Templates" to "ਟੈਂਪਲੇਟਸ",
        "Premium" to "ਪ੍ਰੀਮੀਅਮ",
        "Settings" to "ਸੈਟਿੰਗਾਂ",
        "App Settings" to "ਐਪ ਸੈਟਿੰਗਾਂ",
        "Back" to "ਪਿੱਛੇ",
        "Preferences" to "ਤਰਜੀਹਾਂ",
        "App Theme" to "ਐਪ ਥੀਮ",
        "App Interface Language" to "ਐਪ ਦੀ ਭਾਸ਼ਾ",
        "AI Video Generation Language" to "ਵੀਡੀਓ ਬਣਾਉਣ ਦੀ ਭਾਸ਼ਾ",
        "Storage & Local Cache" to "ਸਟੋਰੇਜ ਅਤੇ ਕੈਸ਼",
        "Clear Local Cache & Storage" to "ਕੈਸ਼ ਅਤੇ ਸਟੋਰੇਜ ਸਾਫ਼ ਕਰੋ",
        "Recent Projects" to "ਹਾਲੀਆ ਪ੍ਰੋਜੈਕਟ",
        "Create Reel" to "ਰੀਲ ਬਣਾਓ",
        "Create New Reel" to "ਨਵੀਂ ਰੀਲ ਬਣਾਓ",
        "AI Reel Architect" to "AI ਰੀਲ ਆਰਕੀਟੈਕਟ",
        "AI Script Writer" to "AI ਸਕ੍ਰਿਪਟ ਲੇਖਕ",
        "Edit" to "ਸੰਪਾਦਿਤ ਕਰੋ",
        "Learn How It Works" to "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ ਸਿੱਖੋ",
        "Got It!" to "ਸਮਝ ਗਿਆ!",
        "Write / Paste Reel Script" to "ਸਕ੍ਰਿਪਟ ਲਿਖੋ ਜਾਂ ਪੇਸਟ ਕਰੋ",
        "Generate with AI" to "AI ਨਾਲ ਬਣਾਓ",
        "Speech & Video Language" to "ਆਵਾਜ਼ ਅਤੇ ਵੀਡੀਓ ਭਾਸ਼ਾ",
        "Primary Narrator Voice" to "ਮੁੱਖ ਆਵਾਜ਼",
        "Selected: " to "ਚੁਣਿਆ ਗਿਆ: ",
        "Selected" to "ਚੁਣਿਆ ਗਿਆ",
        "Male" to "ਪੁਰਸ਼",
        "Female" to "ਮਹਿਲਾ",
        "Child" to "ਬੱਚਾ",
        "Speech Speed: " to "ਆਵਾਜ਼ ਦੀ ਗਤੀ: ",
        "Speech Pitch: " to "ਆਵਾਜ਼ ਦਾ ਸੁਰ: ",
        "Preview Voice" to "ਆਵਾਜ਼ ਸੁਣੋ",
        "Resolution" to "ਰੈਜ਼ੋਲਿਊਸ਼ਨ",
        "Background Soundtrack Overlay" to "ਬੈਕਗ੍ਰਾਊਂਡ ਸੰਗੀਤ",
        "Generate Video" to "ਵੀਡੀਓ ਬਣਾਓ",
        "Skip & Generate Video" to "ਛੱਡੋ ਅਤੇ ਵੀਡੀਓ ਬਣਾਓ",
        "Visual Timeline Editor" to "ਟਾਈਮਲਾਈਨ ਸੰਪਾਦਕ",
        "Export" to "ਐਕਸਪੋਰਟ ਕਰੋ",
        "Scene Canvas" to "ਸੀਨ ਕੈਨਵਸ",
        "Add Clip" to "ਕਲਿੱਪ ਜੋੜੋ",
        "Subtitles" to "ਸਬਟਾਈਟਲ",
        "50+ Filters" to "50+ ਫਿਲਟਰ",
        "Delete" to "ਮਿਟਾਓ",
        "Cancel" to "ਰੱਦ ਕਰੋ",
        "Save" to "ਸੰਭਾਲੋ",
        "Copy" to "ਕਾਪੀ ਕਰੋ",
        "Done" to "ਹੋ ਗਿਆ",
        "Yes" to "ਹਾਂ",
        "No" to "ਨਹੀਂ",
        "Share" to "ਸਾਂਝਾ ਕਰੋ",
        "Share Reel" to "ਰੀਲ ਸ਼ੇਅਰ ਕਰੋ",
        "Search..." to "ਖੋਜੋ...",
        "Search" to "ਖੋਜ",
        "Clear" to "ਸਾਫ਼ ਕਰੋ",
        "Loading..." to "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
        "All Languages" to "ਸਾਰੀਆਂ ਭਾਸ਼ਾਵਾਂ",
        "Popular ⭐" to "ਪ੍ਰਸਿੱਧ ⭐",
        "Indian Languages 🇮🇳" to "ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ 🇮🇳",
        "Global 🌐" to "ਗਲੋਬਲ ਭਾਸ਼ਾਵਾਂ 🌐",
        "Select Language" to "ਭਾਸ਼ਾ ਚੁਣੋ",
        "Clear Cache" to "ਕੈਸ਼ ਸਾਫ਼ ਕਰੋ",
        "Sign Out" to "ਸਾਈਨ ਆਉਟ",
        "Open in Studio" to "ਸਟੂਡੀਓ ਵਿੱਚ ਖੋਲ੍ਹੋ",
        "Use Template" to "ਟੈਂਪਲੇਟ ਵਰਤੋ"
    )

    val ODIA_MAP = mapOf(
        "Yashora" to "ଯଶୋରା",
        "AI REEL GENERATOR" to "AI ରୀଲ୍ ଜେନେରେଟର୍",
        "REEL GENERATOR" to "ରୀଲ୍ ଜେନେରେଟର୍",
        "Home" to "ହୋମ୍",
        "AI Tools" to "AI ଉପକରଣ",
        "AI Chat" to "AI ଚାଟ୍",
        "My Library" to "ମୋ ଲାଇବ୍ରେରୀ",
        "Projects" to "ପ୍ରୋଜେକ୍ଟସ୍",
        "Saved Scripts" to "ସଂରକ୍ଷିତ ସ୍କ୍ରିପ୍ଟସ୍",
        "Export History" to "ରପ୍ତାନି ଇତିହାସ",
        "Templates" to "ଟେମ୍ପଲେଟ୍ସ",
        "Premium" to "ପ୍ରିମିୟମ୍",
        "Settings" to "ସେଟିଙ୍ଗ୍ସ",
        "App Settings" to "ଆପ୍ ସେଟିଙ୍ଗ୍ସ",
        "Back" to "ପଛକୁ ଯାଆନ୍ତୁ",
        "Preferences" to "ପସନ୍ଦ",
        "App Theme" to "ଆପ୍ ଥିମ୍",
        "App Interface Language" to "ଆପ୍ ଭାଷା",
        "AI Video Generation Language" to "ଭିଡିଓ ତିଆରି ଭାଷା",
        "Storage & Local Cache" to "ଷ୍ଟୋରେଜ୍ ଏବଂ କ୍ୟାଶ୍",
        "Clear Local Cache & Storage" to "କ୍ୟାଶ୍ ଏବଂ ଷ୍ଟୋରେଜ୍ ସଫା କରନ୍ତୁ",
        "Recent Projects" to "ସାମ୍ପ୍ରତିକ ପ୍ରୋଜେକ୍ଟସ୍",
        "Create Reel" to "ରୀଲ୍ ତିଆରି କରନ୍ତୁ",
        "Create New Reel" to "ନୂତନ ରୀଲ୍ କରନ୍ତୁ",
        "AI Reel Architect" to "AI ରୀଲ୍ ଆର୍କିଟେକ୍ଟ",
        "Edit" to "ଏଡିଟ୍ କରନ୍ତୁ",
        "Learn How It Works" to "ଏହା କିପରି କାମ କରେ ଜାଣନ୍ତୁ",
        "Got It!" to "ବୁଝିଗଲି!",
        "Generate with AI" to "AI ସହିତ ତିଆରି କରନ୍ତୁ",
        "Speech & Video Language" to "ଭଏସ୍ ଏବଂ ଭିଡିଓ ଭାଷା",
        "Primary Narrator Voice" to "ମୁଖ୍ୟ ସ୍ୱର",
        "Selected: " to "ମନୋନୀତ: ",
        "Selected" to "ମନୋନୀତ",
        "Male" to "ପୁରୁଷ",
        "Female" to "ମହିଳା",
        "Child" to "ଶିଶୁ",
        "Speech Speed: " to "ସ୍ୱର ଗତି: ",
        "Speech Pitch: " to "ସ୍ୱର ସ୍ତର: ",
        "Preview Voice" to "ସ୍ୱର ଶୁଣନ୍ତୁ",
        "Resolution" to "ରିଜୋଲ୍ୟୁସନ୍",
        "Background Soundtrack Overlay" to "ପୃଷ୍ଠଭୂମି ସଙ୍ଗୀତ",
        "Generate Video" to "ଭିଡିଓ ତିଆରି କରନ୍ତୁ",
        "Skip & Generate Video" to "ଛାଡ଼ି ଭିଡିଓ ତିଆରି କରନ୍ତୁ",
        "Visual Timeline Editor" to "ଟାଇମଲାଇନ୍ ଏଡିଟର୍",
        "Export" to "ରପ୍ତାନି କରନ୍ତୁ",
        "Scene Canvas" to "ଦୃଶ୍ୟ କାନଭାସ୍",
        "Add Clip" to "କ୍ଲିପ୍ ଯୋଡ଼ନ୍ତୁ",
        "Subtitles" to "ସବଟାଇଟଲ୍ସ",
        "50+ Filters" to "50+ ଫିଲ୍ଟର୍",
        "Delete" to "ଡିଲିଟ୍ କରନ୍ତୁ",
        "Cancel" to "ବାତିଲ୍ କରନ୍ତୁ",
        "Save" to "ସେଭ୍ କରନ୍ତୁ",
        "Copy" to "କପି କରନ୍ତୁ",
        "Done" to "ସମ୍ପୂର୍ଣ୍ଣ",
        "Yes" to "ହଁ",
        "No" to "ନା",
        "Share" to "ସେୟାର୍ କରନ୍ତୁ",
        "Share Reel" to "ରୀଲ୍ ସେୟାର୍ କରନ୍ତୁ",
        "Search..." to "ଖୋଜନ୍ତୁ...",
        "Search" to "ସନ୍ଧାନ",
        "Clear" to "ସଫା କରନ୍ତୁ",
        "Loading..." to "ଲୋଡ୍ ହେଉଛି...",
        "All Languages" to "ସମସ୍ତ ଭାଷା",
        "Popular ⭐" to "ଲୋକପ୍ରିୟ ⭐",
        "Indian Languages 🇮🇳" to "ଭାରତୀୟ ଭାଷା 🇮🇳",
        "Global 🌐" to "ବିଶ୍ୱସ୍ତରୀୟ 🌐",
        "Select Language" to "ଭାଷା ବାଛନ୍ତୁ",
        "Clear Cache" to "କ୍ୟାଶ୍ ସଫା କରନ୍ତୁ",
        "Sign Out" to "ସାଇନ୍ ଆଉଟ୍",
        "Open in Studio" to "ଷ୍ଟୁଡିଓରେ ଖୋଲନ୍ତୁ",
        "Use Template" to "ଟେମ୍ପଲେଟ୍ ବ୍ୟବହାର କରନ୍ତୁ"
    )

    val ASSAMESE_MAP = mapOf(
        "Yashora" to "যশোৰা",
        "AI REEL GENERATOR" to "AI ৰীল জেনেৰেটৰ",
        "REEL GENERATOR" to "ৰীল জেনেৰেটৰ",
        "Home" to "ঘৰ",
        "AI Tools" to "AI সঁজুলি",
        "AI Chat" to "AI চেট",
        "My Library" to "মোৰ লাইব্ৰেৰী",
        "Projects" to "প্ৰকল্প",
        "Saved Scripts" to "সংৰক্ষিত স্ক্ৰিপ্ট",
        "Export History" to "ৰপ্তানি ইতিহাস",
        "Templates" to "টেমপ্লেট",
        "Premium" to "প্ৰিমিয়াম",
        "Settings" to "ছেটিংছ",
        "App Settings" to "এপ্লিকেচন ছেটিংছ",
        "Back" to "উভতি যাওক",
        "Preferences" to "পছন্দসমূহ",
        "App Theme" to "এপ থিম",
        "App Interface Language" to "এপ ভাষা",
        "AI Video Generation Language" to "ভিডিঅ' নিৰ্মাণৰ ভাষা",
        "Storage & Local Cache" to "ষ্ট'ৰেজ আৰু কেশ্ব",
        "Clear Local Cache & Storage" to "কেশ্ব আৰু ষ্ট'ৰেজ পৰিষ্কাৰ কৰক",
        "Recent Projects" to "শেহতীয়া প্ৰকল্প",
        "Create Reel" to "ৰীল বনাওক",
        "Create New Reel" to "নতুন ৰীল বনাওক",
        "AI Reel Architect" to "AI ৰীল আৰ্কিটেক্ট",
        "Edit" to "সম্পাদনা কৰক",
        "Learn How It Works" to "ই কেনেকৈ কাম কৰে জানক",
        "Got It!" to "বুজি পালোঁ!",
        "Generate with AI" to "AI ৰ সৈতে বনাওক",
        "Speech & Video Language" to "কণ্ঠ আৰু ভিডিঅ' ভাষা",
        "Primary Narrator Voice" to "মুখ্য কণ্ঠ",
        "Selected: " to "নিৰ্বাচিত: ",
        "Selected" to "নিৰ্বাচিত",
        "Male" to "পুৰুষ",
        "Female" to "মহিলা",
        "Child" to "শিশু",
        "Speech Speed: " to "কণ্ঠৰ গতি: ",
        "Speech Pitch: " to "কণ্ঠৰ স্তৰ: ",
        "Preview Voice" to "কণ্ঠ শুনক",
        "Resolution" to "ৰিজলিউশ্বন",
        "Background Soundtrack Overlay" to "পৃষ্ঠভূমি সংগীত",
        "Generate Video" to "ভিডিঅ' বনাওক",
        "Skip & Generate Video" to "এৰাই চলি ভিডিঅ' বনাওক",
        "Visual Timeline Editor" to "টাইমলাইন সম্পাদক",
        "Export" to "ৰপ্তানি কৰক",
        "Scene Canvas" to "দৃশ্য কেনভাছ",
        "Add Clip" to "ক্লিপ যোগ কৰক",
        "Subtitles" to "উপশীৰ্ষক",
        "50+ Filters" to "50+ ফিল্টাৰ",
        "Delete" to "মচি পেলাওক",
        "Cancel" to "বাতিল কৰক",
        "Save" to "সংৰক্ষণ কৰক",
        "Copy" to "কপি কৰক",
        "Done" to "সম্পূৰ্ণ হ'ল",
        "Yes" to "হয়",
        "No" to "নহয়",
        "Share" to "শ্বেয়াৰ কৰক",
        "Share Reel" to "ৰীল শ্বেয়াৰ কৰক",
        "Search..." to "সন্ধান কৰক...",
        "Search" to "সন্ধান",
        "Clear" to "পৰিষ্কাৰ কৰক",
        "Loading..." to "লোড হৈ আছে...",
        "All Languages" to "সকলো ভাষা",
        "Popular ⭐" to "জনপ্ৰিয় ⭐",
        "Indian Languages 🇮🇳" to "ভাৰতীয় ভাষা 🇮🇳",
        "Global 🌐" to "গোলকীয় ভাষা 🌐",
        "Select Language" to "ভাষা বাছক",
        "Clear Cache" to "কেশ্ব মচক",
        "Sign Out" to "ছাইন আউট",
        "Open in Studio" to "ষ্টুডিঅ'ত খোলক",
        "Use Template" to "টেমপ্লেট ব্যৱহাৰ কৰক"
    )

    val NEPALI_MAP = mapOf(
        "Yashora" to "यशोरा",
        "AI REEL GENERATOR" to "एआई रील जेनेरेटर",
        "REEL GENERATOR" to "रील जेनेरेटर",
        "Home" to "गृहपृष्ठ",
        "AI Tools" to "एआई औजारहरू",
        "AI Chat" to "एआई च्याट",
        "My Library" to "मेरो पुस्तकालय",
        "Projects" to "परियोजनाहरू",
        "Saved Scripts" to "बचत गरिएका लिपिहरू",
        "Export History" to "निर्यात इतिहास",
        "Templates" to "ढाँचाहरू",
        "Premium" to "प्रिमियम",
        "Settings" to "सेटिङहरू",
        "App Settings" to "एप सेटिङहरू",
        "Back" to "पछाडि",
        "Preferences" to "प्राथमिकताहरू",
        "App Theme" to "एप विषयवस्तु",
        "App Interface Language" to "एप भाषा",
        "AI Video Generation Language" to "भिडियो निर्माण भाषा",
        "Storage & Local Cache" to "भण्डारण र क्यास",
        "Clear Local Cache & Storage" to "क्यास र भण्डारण खाली गर्नुहोस्",
        "Recent Projects" to "हालका परियोजनाहरू",
        "Create Reel" to "रील सिर्जना गर्नुहोस्",
        "Create New Reel" to "नयाँ रील बनाउनुहोस्",
        "AI Reel Architect" to "एआई रील आर्किटेक्ट",
        "AI Script Writer" to "एआई लिपि लेखक",
        "Edit" to "सम्पादन गर्नुहोस्",
        "Learn How It Works" to "यसले कसरी काम गर्छ सिक्नुहोस्",
        "Got It!" to "बुझियो!",
        "Write / Paste Reel Script" to "लिपि लेख्नुहोस् वा टाँस्नुहोस्",
        "Generate with AI" to "एआई मार्फत बनाउनुहोस्",
        "Speech & Video Language" to "आवाज र भिडियो भाषा",
        "Primary Narrator Voice" to "मुख्य वाचक आवाज",
        "Selected: " to "चयन गरिएको: ",
        "Selected" to "चयन गरियो",
        "Male" to "पुरुष",
        "Female" to "महिला",
        "Child" to "बालक",
        "Speech Speed: " to "आवाज गति: ",
        "Speech Pitch: " to "आवाज पिच: ",
        "Preview Voice" to "आवाज सुन्नुहोस्",
        "Resolution" to "रिजोल्युसन",
        "Background Soundtrack Overlay" to "पृष्ठभूमि संगीत",
        "Generate Video" to "भिडियो सिर्जना गर्नुहोस्",
        "Skip & Generate Video" to "छोड्नुहोस् र भिडियो बनाउनुहोस्",
        "Visual Timeline Editor" to "समयरेखा सम्पादक",
        "Export" to "निर्यात गर्नुहोस्",
        "Scene Canvas" to "दृश्य क्याનभास",
        "Add Clip" to "क्लिप थप्नुहोस्",
        "Subtitles" to "उपशीर्षकहरू",
        "50+ Filters" to "५०+ फिल्टरहरू",
        "Delete" to "मेटाउनुहोस्",
        "Cancel" to "रद्द गर्नुहोस्",
        "Save" to "बचत गर्नुहोस्",
        "Copy" to "प्रतिलिपि गर्नुहोस्",
        "Done" to "सम्पन्न भयो",
        "Yes" to "हो",
        "No" to "होइन",
        "Share" to "साझा गर्नुहोस्",
        "Share Reel" to "रील साझा गर्नुहोस्",
        "Search..." to "खोज्नुहोस्...",
        "Search" to "खोज",
        "Clear" to "खाली गर्नुहोस्",
        "Loading..." to "लोड हुँदैछ...",
        "All Languages" to "सबै भाषाहरू",
        "Popular ⭐" to "लोकप्रिय ⭐",
        "Indian Languages 🇮🇳" to "भारतीय भाषाहरू 🇮🇳",
        "Global 🌐" to "विश्वव्यापी भाषाहरू 🌐",
        "Select Language" to "भाषा छान्नुहोस्",
        "Clear Cache" to "क्यास खाली गर्नुहोस्",
        "Sign Out" to "साइन आउट",
        "Open in Studio" to "स्टुडियोमा खोल्नुहोस्",
        "Use Template" to "ढाँचा प्रयोग गर्नुहोस्"
    )

    val SINHALA_MAP = mapOf(
        "Yashora" to "යශෝරා",
        "AI REEL GENERATOR" to "AI රීල් උත්පාදක",
        "REEL GENERATOR" to "රීල් උත්පාදක",
        "Home" to "මුල් පිටුව",
        "AI Tools" to "AI මෙවලම්",
        "AI Chat" to "AI චැට්",
        "My Library" to "මගේ පුස්තකාලය",
        "Projects" to "ව්‍යාපෘති",
        "Saved Scripts" to "සුරකින ලද පිටපත්",
        "Export History" to "අපනයන ඉතිහාසය",
        "Templates" to "ආකෘති",
        "Premium" to "ප්‍රිමියම්",
        "Settings" to "සැකසුම්",
        "App Settings" to "යෙදුම් සැකසුම්",
        "Back" to "ආපසු",
        "Preferences" to "අභිරුචි",
        "App Theme" to "යෙදුම් තේමාව",
        "App Interface Language" to "යෙදුම් භාෂාව",
        "AI Video Generation Language" to "වීඩියෝ උත්පාදන භාෂාව",
        "Storage & Local Cache" to "ගබඩාව සහ කැචය",
        "Clear Local Cache & Storage" to "කැචය සහ ගබඩාව හිස් කරන්න",
        "Recent Projects" to "මෑත ව්‍යාපෘති",
        "Create Reel" to "රීල් සාදන්න",
        "Create New Reel" to "නව රීල් එකක් සාදන්න",
        "AI Reel Architect" to "AI රීල් ගෘහ නිර්මාණ ශිල්පියා",
        "AI Script Writer" to "AI පිටපත් රචකයා",
        "Edit" to "සංස්කරණය",
        "Learn How It Works" to "එය ක්‍රියා කරන ආකාරය ඉගෙන ගන්න",
        "Got It!" to "තේරුණා!",
        "Write / Paste Reel Script" to "පිටපත ලියන්න හෝ අලවන්න",
        "Generate with AI" to "AI මඟින් සාදන්න",
        "Speech & Video Language" to "හඬ සහ වීඩියෝ භාෂාව",
        "Primary Narrator Voice" to "ප්‍රධාන කථක හඬ",
        "Selected: " to "තෝරාගත්: ",
        "Selected" to "තෝරාගන්නා ලදී",
        "Male" to "පිරිමි",
        "Female" to "ගැහැණු",
        "Child" to "ළමා",
        "Speech Speed: " to "කථන වේගය: ",
        "Speech Pitch: " to "කථන තාරතාව: ",
        "Preview Voice" to "හඬ පෙරදසුන",
        "Resolution" to "විභේදනය",
        "Background Soundtrack Overlay" to "පසුබිම් සංගීතය",
        "Generate Video" to "වීඩියෝව සාදන්න",
        "Skip & Generate Video" to "මඟ හැර වීඩියෝව සාදන්න",
        "Visual Timeline Editor" to "කාලරේඛා සංස්කාරකය",
        "Export" to "අපනයනය කරන්න",
        "Scene Canvas" to "දර්ශන කැන්වසය",
        "Add Clip" to "ක්ලිප් එකක් එක් කරන්න",
        "Subtitles" to "උපසිරැසි",
        "50+ Filters" to "50+ පෙරහන්",
        "Delete" to "මකන්න",
        "Cancel" to "අවලංගු කරන්න",
        "Save" to "සුරකින්න",
        "Copy" to "පිටපත් කරන්න",
        "Done" to "අවසන්",
        "Yes" to "ඔව්",
        "No" to "නැත",
        "Share" to "බෙදාගන්න",
        "Share Reel" to "රීල් බෙදාගන්න",
        "Search..." to "සොයන්න...",
        "Search" to "සොයන්න",
        "Clear" to "හිස් කරන්න",
        "Loading..." to "පූරණය වෙමින්...",
        "All Languages" to "සියලුම භාෂා",
        "Popular ⭐" to "ජනප්‍රිය ⭐",
        "Indian Languages 🇮🇳" to "ඉන්දියානු භාෂා 🇮🇳",
        "Global 🌐" to "ගෝලීය භාෂා 🌐",
        "Select Language" to "භාෂාව තෝරන්න",
        "Clear Cache" to "කැචය හිස් කරන්න",
        "Sign Out" to "ඉවත් වන්න",
        "Open in Studio" to "ස්ටුඩියෝවේ විවෘත කරන්න",
        "Use Template" to "ආකෘතිය භාවිතා කරන්න"
    )
}
