package com.ritvyom.yashoraReelgenerator.presentation.utils

/**
 * A beautiful, rich, dynamic localization helper for translating 
 * hardcoded English strings into Hindi and all 15 other languages 
 * dynamically in Compose.
 */
object Localization {
    
    private val HINDI_MAP = mapOf(
        "Yashora" to "यशोरा",
        "REEL GENERATOR" to "रील जनरेटर",
        "Your script is fully processed with no artificial word count ceiling!" to "आपकी स्क्रिप्ट को बिना किसी शब्द सीमा के पूरी तरह से संसाधित किया जाता है!",
        "words" to "शब्द",
        "Configure Reel Pipeline" to "रील पाइपलाइन कॉन्फ़िगर करें",
        "Write / Paste Reel Script" to "रील स्क्रिप्ट लिखें / पेस्ट करें",
        "Enter or paste your script here. The AI will segment it into scenes, narrate compiling voices, and generate visual prompts automatically..." to "यहां अपनी स्क्रिप्ट दर्ज करें या पेस्ट करें। एआई इसे दृश्यों में विभाजित करेगा, वर्णन करने वाली आवाजों को संकलित करेगा, और स्वचालित रूप से विजुअल संकेत उत्पन्न करेगा...",
        "Select Video Narration Style" to "वीडियो नरेशन शैली चुनें",
        "Warm storybook textures and soft focuses" to "गर्म कहानी साझा करने वाली बनावट और सॉफ्ट फोकस",
        "Speech & Video Language" to "भाषण और वीडियो भाषा",
        "This controls the spoken accents & subtitles" to "यह बोली जाने वाली लहजे और उपशीर्षक को नियंत्रित करता है",
        "Primary Narrator Voice" to "प्राथमिक नैरेटर आवाज",
        "Category / Voice Presets" to "कैटेगरी / वॉयस प्रीसेट्स",
        "Pick a category to auto-tune perfect matching voice & backing tracks:" to "एक कैटेगरी चुनें जो आवाज और बैकग्राउंड ट्रैक को स्वचालित रूप से परफेक्ट ट्यून कर देगी:",
        "Motivation" to "मोटिवेशन",
        "News & Facts" to "खबरें और फैक्ट्स",
        "Kids Story" to "बच्चों की कहानियां",
        "Elderly Wisdom" to "बुजुर्ग सीख / विचार",
        "Emotional Drama" to "भावनात्मक नाटक / कहानी",
        "Peaceful Zen" to "शांतिपूर्ण ध्यान / आध्यात्मिक",
        "Selected: " to "चयनित: ",
        "Male" to "पुरुष",
        "Female" to "महिला",
        "Child" to "बच्चा",
        "Speech Speed: " to "भाषण गति: ",
        "Speech Pitch: " to "भाषण पिच: ",
        "Preview Voice Synths" to "आवाज संकलन का पूर्वावलोकन करें",
        "Select Aspect Ratio" to "पहलू अनुपात चुनें",
        "Select Output Settings" to "आउटपुट सेटिंग्स चुनें",
        "Resolution" to "रिज़ॉल्यूशन",
        "Video Framerate" to "वीडियो फ्रेमरेट",
        "Background Soundtrack Overlay" to "पृष्ठभूमि संगीत ओवरले",
        "Add smart rhythmic backing beats" to "स्मार्ट लयबद्ध पृष्ठभूमि बीट्स जोड़ें",
        "Music Level: " to "संगीत स्तर: ",
        "Voice Level: " to "आवाज स्तर: ",
        "Generate Video" to "वीडियो बनाएं",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "स्क्रिप्ट्स को तुरंत कस्टम न्यूरल मॉडल के साथ समृद्ध विजुअल स्टोरीबोर्ड में बदलें।",
        "Create Reel" to "रील बनाएं",
        "AI Reel Architect" to "एआई रील आर्किटेक्ट",
        "Recent Projects" to "हाल के प्रोजेक्ट्स",
        "💡 Tip: Chhote/Purane device par video jaldi save karne ke liye 720p ya 480p select karein! (Selecting 720p/480p saves video up to 4x faster on older devices)" to "💡 संकेत: छोटे/पुराने डिवाइस पर वीडियो जल्दी सेव करने के लिए 720p या 480p चुनें! (720p/480p चुनने से पुराने डिवाइसेज पर वीडियो 4 गुना तेजी से सेव होता है)",
        "Run in Background" to "बैकग्राउंड में चलाएं",
        "Saving Video in Background..." to "बैकग्राउंड में वीडियो सेव हो रहा है...",
        "Export Complete" to "एक्सपोर्ट पूरा हुआ",
        "Your video has been successfully saved to Movies/Yashora!" to "आपका वीडियो सफलतापूर्वक Movies/Yashora में सेव हो गया है!",
        "Export History" to "एक्सपोर्ट इतिहास",
        "No Project Drafts Found" to "कोई प्रोजेक्ट ड्राफ्ट नहीं मिला",
        "Click 'Create Reel' at the bottom right corner to start breaking down scripts" to "स्क्रिप्ट शुरू करने के लिए नीचे दाईं ओर 'रील बनाएं' पर क्लिक करें",
        "No Rendered History" to "कोई रेंडर किया गया इतिहास नहीं है",
        "Once you configure storyboards and export them, generated MP4 entries will persist here" to "एक बार जब आप स्टोरीबोर्ड कॉन्फ़िगर और एक्सपोर्ट कर लेते हैं, तो उत्पन्न MP4 प्रविष्टियां यहां दिखाई देंगी",
        "Delete Project draft?" to "प्रोजेक्ट ड्राफ्ट हटाएं?",
        "Are you sure you want to delete" to "क्या आप वाकई हटाना चाहते हैं",
        "permanently? This action cannot be undone." to "स्थायी रूप से? इस क्रिया को पूर्ववत नहीं किया जा सकता है।",
        "Delete" to "हटाएं",
        "Cancel" to "रद्द करें",
        "Cancel Process?" to "प्रक्रिया रद्द करें?",
        "Cancel Generation?" to "जनरेशन रद्द करें?",
        "Cancel Export?" to "एक्सपोर्ट रद्द करें?",
        "Cancel Script Generation?" to "स्क्रिप्ट जनरेशन रद्द करें?",
        "Generating AI Script with Gemini..." to "जेमिनी के साथ एआई स्क्रिप्ट जेनरेट की जा रही है...",
        "Connecting to Gemini 1.5 Flash Model" to "जेमिनी 1.5 फ्लैश मॉडल से कनेक्ट हो रहा है",
        "Analyzing Topic & Style Context" to "विषय और शैली संदर्भ का विश्लेषण",
        "Drafting Hook & Scene Narration" to "हुक और दृश्य विवरण तैयार करना",
        "Formatting Scene Timestamps & Visual Prompts" to "दृश्य समयरेखा और दृश्य संकेतों को प्रारूपित करना",
        "Cancel Process" to "प्रक्रिया रद्द करें",
        "Are you sure you want to cancel the process? All progress will be lost." to "क्या आप वाकई प्रक्रिया रद्द करना चाहते हैं? आपकी सभी प्रगति खो जाएगी।",
        "Are you sure you want to cancel exporting the video?" to "क्या आप वाकई वीडियो एक्सपोर्ट रद्द करना चाहते हैं?",
        "Are you sure you want to cancel script generation?" to "क्या आप वाकई स्क्रिप्ट जनरेशन रद्द करना चाहते हैं?",
        "Yes, Cancel" to "हाँ, रद्द करें",
        "No, Continue" to "नहीं, जारी रखें",
        "Yes" to "हाँ",
        "No" to "नहीं",
        "VividStock Prime" to "विविडस्टॉक प्राइम",
        "Professional-grade realistic stock imagery engine" to "व्यावसायिक स्तर का वास्तविक स्टॉक इमेजरी इंजन",
        "Genesis Synthetix" to "जेनेसिस सिंथेटिक्स",
        "Neural AI design and styled custom vector asset creator" to "न्यूरल एआई डिज़ाइन और स्टाइल कस्टम वेक्टर एसेट क्रिएटर",
        "Atlas Historical" to "एटलस हिस्टोरिकल",
        "Elite curated cultural archives and historical visual database" to "अभिजात वर्ग द्वारा क्यूरेट किया गया सांस्कृतिक और ऐतिहासिक दृश्य डेटाबेस",
        "Kawaii Art Vault" to "कावई आर्ट वॉल्ट",
        "Expressive hand-drawn animated concept artwork and motion segments" to "अभिव्यंजक हाथ से खींचा गया एनिमेटेड कलाकृति और गति खंड",
        "NeoManga Catalog" to "नियोमैंगा कैटलॉग",
        "Curation database for thematic illustrated character references" to "विषयगत सचित्र चरित्र संदर्भों के लिए क्यूरेशन डेटाबेस",
        "Horizon Scenic" to "होराइजन सीनिक",
        "Ultra-fast delivery engine for natural backgrounds and scenery backdrops" to "प्राकृतिक पृष्ठभूमि और दृश्यों के लिए अल्ट्रा-फास्ट डिलीवरी इंजन",
        "Chronos Chronicle" to "क्रोनोस क्रॉनिकल",
        "Search millions of verified open-source historical documents, vintage media, and archives" to "लाखों सत्यापित ओपन-सोर्स ऐतिहासिक दस्तावेजों, विंटेज मीडिया और अभिलेखागार खोजें",
        "Lumina Snapshot" to "लुमिना स्नैपशॉट",
        "Dynamic tag-tailored premium photography database for creative layouts" to "रचनात्मक लेआउट के लिए गतिशील टैग-अनुकूलित प्रीमियम फोटोग्राफी डेटाबेस",
        "PopMotion GIF" to "पॉपमोशन जिफ",
        "Instant search of popular pop-culture loops and animated segments" to "लोकप्रिय पॉप-संस्कृति लूप और एनिमेटेड खंडों की त्वरित खोज",
        "OmniShield Fallback" to "ओम्नीशील्ड फॉलबैक",
        "Ultra-secure fallback system, automatically escalating visual delivery" to "अल्ट्रा-सुरक्षित फॉलबैक सिस्टम, स्वचालित रूप से विजुअल डिलीवरी को एस्केलेट करता है",
        "Cosmos DeepSpace" to "कॉस्मॉस डीपस्पेस",
        "Deep-space cosmic cinematic imagery, science archives, and cosmology footage" to "डीप-स्पेस ब्रह्मांडीय सिनेमाई इमेजरी, विज्ञान अभिलेखागार और ब्रह्मांड विज्ञान फुटेज",
        "Extract script segments and fetch real-time stock media matching Prime Vivid, Aura Cinematics, and Lumina Stock to simulate a live slideshow!" to "इंटरैक्टिव लाइव स्लाइड शो का अनुकरण करने के लिए प्राइम विविड, ऑरा सिनेमैटिक्स और लुमिना स्टॉक से मेल खाने वाले रीयल-टाइम मीडिया को फेच करें!",
        "Prime Vivid" to "प्राइम विविड",
        "Aura Cinematics" to "ऑरा सिनेमैटिक्स",
        "Lumina Stock" to "लुमिना स्टॉक",
        "Remove Export Entry?" to "एक्सपोर्ट प्रविष्टि हटाएं?",
        "This will delete the history log for" to "यह इतिहास लॉग को हटा देगा",
        "It does not delete physical MP4 off device storage." to "यह डिवाइस स्टोरेज से मूल MP4 को नहीं हटाता है।",
        "Remove" to "हटाएं",
        "Share" to "शेयर करें",
        "Share Reel" to "रील शेयर करें",
        "Share Video" to "वीडियो शेयर करें",
        "Sharing video or media file..." to "वीडियो या मीडिया फ़ाइल शेयर की जा रही है...",
        "Storage Permission Required" to "स्टोरेज की अनुमति आवश्यक है",
        "Yashora Reel Generator needs permission to access files & storage to save high-quality rendered videos directly into your gallery (Movies/Yashora) and to read imported files safely." to "यशोरा रील जनरेटर को आपके डिवाइस गैलरी (Movies/Yashora) में उच्च गुणवत्ता वाले रेंडर किए गए वीडियो को सहेजने और इम्पोर्ट की गई फ़ाइलों को सुरक्षित रूप से पढ़ने के लिए स्टोरेज अनुमति की आवश्यकता है।",
        "Please enable files/media access in Settings with just one click below." to "कृपया नीचे केवल एक क्लिक के साथ सेटिंग्स में जाकर फ़ाइलें/मीडिया अनुमति को चालू करें।",
        "Open App Settings" to "ऐप सेटिंग्स खोलें",
        "No Internet Connection" to "कोई इंटरनेट कनेक्शन नहीं",
        "Yashora Reel Generator requires an active internet connection to load premium styles, voices, and generate rich video background assets safely. Ads are also required to keep the generation engine free." to "यशोरा रील जनरेटर को प्रीमियम स्टाइल, आवाज लोड करने और सुरक्षित रूप से समृद्ध वीडियो पृष्ठभूमि संपत्तियों को उत्पन्न करने के लिए एक सक्रिय इंटरनेट कनेक्शन की आवश्यकता है। जनरेशन इंजन को मुफ्त रखने के लिए विज्ञापन भी आवश्यक हैं।",
        "Please enable Wi-Fi or cellular data and try again." to "कृपया वाई-फाई या सेलुलर डेटा चालू करें और पुनः प्रयास करें।",
        "Got It" to "समझ गया",
        "App Settings" to "ऐप सेटिंग्स",
        "Back" to "पीछे",
        "Preferences" to "प्राथमिकताएं",
        "Settings" to "सेटिंग्स",
        "App Theme" to "ऐप थीम",
        "App Interface Language" to "ऐप इंटरफ़ेस भाषा",
        "AI Video Generation Language" to "एआई वीडियो जनरेशन भाषा",
        "Legal & About" to "कानूनी और जानकारी",
        "Privacy Policy" to "गोपनीयता नीति",
        "How we protect, save and manage your credentials" to "हम आपके क्रेडेंशियल्स को कैसे सुरक्षित और प्रबंधित करते हैं",
        "Terms & Conditions" to "नियम और शर्तें",
        "Agreement governing AI reel pipeline software usage" to "एआई रील पाइपलाइन सॉफ्टवेयर उपयोग को नियंत्रित करने वाला समझौता",
        "About Yashora Reel Generator" to "यशोरा रील जनरेटर के बारे में",
        "App version, framework and technologies used" to "ऐप संस्करण, फ्रेमवर्क और प्रयुक्त तकनीकें",
        "YASHORA TECHNOLOGIES" to "यशोरा टेक्नोलॉजीज",
        "Version 1.0.4 (Production Ready)" to "संस्करण 1.0.4 (उत्पादन के लिए तैयार)",
        "Select Theme Selection" to "थीम चयन चुनें",
        "Select Language" to "भाषा चुनें",
        "English" to "अंग्रेजी",
        "Hindi" to "हिंदी",
        "Arabic" to "अरबी",
        "Urdu" to "उर्दू",
        "Bengali" to "बंगाली",
        "Tamil" to "तमिल",
        "Telugu" to "तेलुगु",
        "Japanese" to "जापानी",
        "Chinese" to "चीनी",
        "Korean" to "कोरियाई",
        "German" to "जर्मन",
        "French" to "फ्रेंच",
        "Spanish" to "स्पैनिश",
        "Portuguese" to "पुर्तगाली",
        "Russian" to "रूसी",
        "Turkish" to "तुर्की",
        "Visual Timeline Editor" to "विजुअल टाइमलाइन संपादक",
        "Export" to "एक्सपोर्ट",
        "Empty Track Buffer" to "खाली ट्रैक बफर",
        "Preview Voice" to "आवाज पूर्वावलोकन",
        "Chronological Video Track Timeline" to "कालानुक्रमिक वीडियो ट्रैक टाइमलाइन",
        "Add Clip" to "क्लिप जोड़ें",
        "Subtitles" to "उपशीर्षक",
        "50+ Filters" to "50+ फिल्टर्स",
        "Overlays" to "ओवरले",
        "Transitions" to "संक्रमण",
        "AI Background" to "एआई पृष्ठभूमि",
        "Edit Subtitle Text" to "उपशीर्षक पाठ संपादित करें",
        "Split Clip" to "क्लिप विभाजित करें",
        "Add Sticker" to "स्टिकर जोड़ें",
        "Select Color Filter (Applied on canvas live)" to "कलर फ़िल्टर चुनें (कैनवास पर लाइव लागू किया गया)",
        "Add Animated Text Overlay" to "एनिमेटेड टेक्स्ट ओवरले जोड़ें",
        "Select Subtitle Font Style" to "उपशीर्षक फ़ॉन्ट शैली चुनें",
        "Select Overlay Text Accent Color" to "ओवरले टेक्स्ट रंग चुनें",
        "Select Clip Transition Output" to "क्लिप ट्रांजिशन आउटपुट चुनें",
        "AI Visual Scene Generator" to "एआई विजुअल सीन जनरेटर",
        "Configure the specific storyboard scenic guidance for this clip. AI will use this semantic target instruction to dynamically structure custom professional backplates." to "इस क्लिप के लिए विशिष्ट स्टोरीबोर्ड दृश्य मार्गदर्शन कॉन्फ़िगर करें। एआई कस्टम पेशेवर बैकप्लेट बनाने के लिए इस निर्देश का उपयोग करेगा।",
        "Quick Preset Elements" to "त्वरित प्रीसेट तत्व",
        "Generating AI Backplate..." to "एआई बैकप्लेट जनरेट कर रहा है...",
        "Regenerate Background with AI" to "एआई के साथ पृष्ठभूमि पुनर्जीवित करें",
        "Configure tracks details above" to "ऊपर ट्रैक विवरण कॉन्फ़िगर करें",
        "Select Stickers overlay" to "स्टिकर ओवरले चुनें",
        "Close" to "बंद करें",
        "Import Media Assets Preset" to "मीडिया एसेट प्रीसेट आयात करें",
        "Yashora Pipeline Engine" to "यशोरा पाइपलाइन इंजन",
        "COMPILING AI ASSET PACKS" to "एआई एसेट पैक्स को कंपाइल किया जा रहा है",
        "Rendered" to "कम्पाइल किया गया",
        "AdMob Rewards claims: Active" to "एडमब रिवार्ड्स दावे: सक्रिय",
        "Preparing neural video rendering context..." to "न्यूरल वीडियो रेंडरिंग संदर्भ तैयार किया जा रहा है...",
        "Injecting sound design and backing tracks..." to "ध्वनि डिज़ाइन और बैकग्राउंड ट्रैक इंजेक्ट किए जा रहे हैं...",
        "Assembling storyboard elements seamlessly..." to "स्टोरीबोर्ड तत्वों को सहजता से जोड़ा जा रहा है...",
        "Finalizing high definition MP4 stream container..." to "उच्च रिज़ॉल्यूशन MP4 स्ट्रीम कंटेनर को अंतिम रूप दिया जा रहा है...",
        "Video pipeline successfully compiled!" to "वीडियो पाइपलाइन सफलतापूर्वक कंपाइल हो गई!",
        "Initializing video compilation pipeline..." to "वीडियो संकलन पाइपलाइन प्रारंभ की जा रही है...",
        "Analyzing timeline pacing and scene boundaries..." to "टाइमलाइन पेसिंग और दृश्य सीमाओं का विश्लेषण किया जा रहा है...",
        "Baking high-contrast cinematic color LUTs..." to "सिनेमैटिक रंग एलयूटी तैयार किया जा रहा है...",
        "Applying premium edge blending and transitions..." to "प्रीमियम ट्रांजिशन और ब्लेंडिंग लागू की जा रही है...",
        "Synthesizing natural synthetic voiceovers..." to "प्राकृतिक कृत्रिम आवाज (वॉइसओवर) तैयार की जा रही है...",
        "Aligning voice speed and script syllables..." to "आवाज की गति और स्क्रिप्ट अक्षरों को संरेखित किया जा रहा है...",
        "Applying adaptive volume ducking filters..." to "अनुकूलनशील वॉल्यूम डकिंग फिल्टर लागू किए जा रहे हैं...",
        "Generating localized subtitle overlays and fonts..." to "स्थानीयकृत उपशीर्षक ओवरले और फोंट उत्पन्न किए जा रहे हैं...",
        "Baking video frames in hardware graphics pipeline..." to "हार्डवेयर ग्राफिक्स पाइपलाइन में वीडियो फ्रेम रेंडर किए जा रहे हैं...",
        "Saving high-fidelity reel to device storage..." to "डिवाइस स्टोरेज में रील को सहेजा जा रहा है...",
        "About Yashora Reel Gen" to "यशोरा रील जनरेटर के बारे में",
        "Rendering Final Output File" to "अंतिम आउटपुट फ़ाइल रेंडर की जा रही है",
        "Multiplexing tracks, speech frames & LUTs..." to "ट्रैक, भाषण फ्रेम और एलयूटी को मल्टीप्लेक्स किया जा रहा है...",
        "Scene Clip Duration:" to "दृश्य क्लिप अवधि:",
        "Seconds" to "सेकंड",
        "s" to "से.",
        "[Splitted Clip] New Segment" to "[विभाजित क्लिप] नया खंड",
        "Sci-Fi Nebula System" to "Sci-Fi नेबुला सिस्टम",
        "Vibrant Cyberpunk Street" to "वाइब्रेंट साइबरपंक स्ट्रीट",
        "Golden Tropical Sunset" to "सुनहरा उष्णकटिबंधीय सूर्यास्त",
        "Anime Dojo Practice" to "एनीमे डोजो अभ्यास",
        "Monochrome Hand Sketches" to "मोनोक्रोम हाथ के रेखाचित्र",
        "Cinematic Drone Mountain" to "सिनेमैटिक ड्रोन माउंटेन",
        "Imported" to "आयात किया गया",
        "clip successfully." to "क्लिप सफलतापूर्वक।",
        "Imported visual matching" to "आयातित विजुअल मेल खा रहा है",
        "Captivating epic cinematography overlay preset representing" to "आकर्षक महाकाव्य सिनेमैटोग्राफी ओवरले प्रीसेट का प्रतिनिधित्व",
        "Visual:" to "विजुअल:",
        "Video export complete. File saved to downloads directory." to "वीडियो एक्सपोर्ट पूरा हुआ। फ़ाइल डाउनलोड निर्देशिका में सहेजी गई।",
        "E.g., Cinematic futuristic skyline at sunset, 4k ultra-detailed..." to "उदा., सूर्यास्त के समय सिनेमाई भविष्य का क्षितिज, 4k अति-विस्तृत...",
        "Cinematic Hollywood UltraHD, golden sunset lighting, majestic composition" to "सिनेमाई हॉलीवुड अल्ट्राएचडी, सुनहरी सूर्यास्त प्रकाश व्यवस्था, आलीशान रचना",
        "Vibrant modern anime aesthetic skyline brush painting" to "वाइब्रेंट आधुनिक एनीमे सौंदर्यपूर्ण क्षितिज ब्रश पेंटिंग",
        "Sci-Fi cyberpunk metropolis streets glowing, wet reflections, purple neon" to "Sci-Fi साइबरपंक महानगर की सड़कें चमक रही हैं, गीले प्रतिबिंब, बैंगनी नियॉन",
        "Vintage monochrome ink sketches, master detailed textures" to "विंटेज मोनोक्रोम स्याही के रेखाचित्र, विस्तृत बनावट",
        "Breathtaking drone footage above snowcapped mountains" to "बर्फ से ढकी पहाड़ियों के ऊपर लुभावनी ड्रोन फुटेज",
        "Normal" to "सामान्य",
        "Cinematic Glow" to "सिनेमेटिक ग्लो",
        "Cyberpunk Neon" to "साइबरपंक नियॉन",
        "Vintage Monochrome" to "विंटेज मोनोक्रोम",
        "Warm Dream" to "वार्म ड्रीम",
        "TikTok Style" to "टिकटॉक शैली",
        "Vintage Retro" to "विंटेज रेट्रो",
        "Bold Impact" to "बोल्ड इम्पैक्ट",
        "Futuristic Tech" to "भविष्य की तकनीक",
        "Cyber Neon" to "साइबर नियॉन",
        "Radioactive" to "रेडियोएक्टिव",
        "Hot Pink" to "हॉट पिंक",
        "Yellow" to "पीला",
        "White" to "सफ़ेद",
        "None" to "कोई नहीं",
        "Fade Dissolve" to "फ़ेड डिसोल्व",
        "Slide Left" to "बायें स्लाइड करें",
        "Cross Zoom" to "क्रॉस ज़ूम",
        "Glitch Warp" to "ग्लिच वार्प",
        "Whip Pan" to "व्हिप पैन"
    )

    private val SPANISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "GENERADOR DE REELS",
        "Recent Projects" to "Proyectos Recientes",
        "Export History" to "Historial de Exportaciones",
        "Configure Reel Pipeline" to "Configurar Canal de Reels",
        "Write / Paste Reel Script" to "Escribir / Pegar Guion",
        "Select Video Narration Style" to "Estilo de Narración de Video",
        "Speech & Video Language" to "Idioma de Voz y Video",
        "Primary Narrator Voice" to "Voz del Narrador Principal",
        "Selected: " to "Seleccionado: ",
        "Male" to "Masculino",
        "Female" to "Femenino",
        "Child" to "Infantil",
        "Speech Speed: " to "Velocidad de Voz: ",
        "Speech Pitch: " to "Tono de Voz: ",
        "Preview Voice Synths" to "Previsualizar Voz Sintetizada",
        "Select Aspect Ratio" to "Relación de Aspecto",
        "Select Output Settings" to "Ajustes de Salida",
        "Resolution" to "Resolución",
        "Video Framerate" to "Fotogramas de Video",
        "Background Soundtrack Overlay" to "Fondo de Música",
        "Add smart rhythmic backing beats" to "Añadir ritmos rítmicos inteligentes",
        "Generate Video" to "Generar Video",
        "Create Reel" to "Crear Reel",
        "AI Reel Architect" to "Arquitecto de Reels de IA",
        "No Project Drafts Found" to "No se Encontraron Borradores",
        "No Rendered History" to "Sin Historial Renderizado",
        "Delete" to "Eliminar",
        "Cancel" to "Cancelar",
        "Remove" to "Eliminar",
        "Close" to "Cerrar",
        "App Settings" to "Ajustes de la App",
        "Preferences" to "Preferencias",
        "App Theme" to "Tema de la App",
        "App Interface Language" to "Idioma de la Interfaz",
        "AI Video Generation Language" to "Idioma de Generación de IA",
        "Legal & About" to "Legal y Acerca de",
        "Privacy Policy" to "Política de Privacidad",
        "Terms & Conditions" to "Términos y Condiciones",
        "About Yashora Reel Generator" to "Acerca del Generador Yashora",
        "YASHORA TECHNOLOGIES" to "TECNOLOGÍAS YASHORA",
        "Version 1.0.4 (Production Ready)" to "Versión 1.0.4 (Listo para Producción)",
        "Visual Timeline Editor" to "Editor de Línea Temporal",
        "Export" to "Exportar",
        "Empty Track Buffer" to "Búfer de Pista Vacío",
        "Chronological Video Track Timeline" to "Línea de Tiempo de Video",
        "Add Clip" to "Añadir Clip",
        "Subtitles" to "Subtítulos",
        "50+ Filters" to "50+ Filtros",
        "Overlays" to "Superposiciones",
        "Transitions" to "Transiciones",
        "AI Background" to "Fondo de IA",
        "Edit Subtitle Text" to "Editar Subtítulos",
        "Split Clip" to "Dividir Clip",
        "Add Sticker" to "Añadir Pegatina",
        "Rendering Final Output File" to "Renderizando Archivo de Salida Final",
        "Multiplexing tracks, speech frames & LUTs..." to "Multiplexando pistas, voz y LUTs...",
        "Seconds" to "Segundos",
        "s" to "s"
    )

    private val FRENCH_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "GÉNÉRATEUR DE REELS",
        "Recent Projects" to "Projets Récents",
        "Export History" to "Historique d'Exportation",
        "Configure Reel Pipeline" to "Configurer le Pipeline de Reels",
        "Write / Paste Reel Script" to "Écrire / Coller le Script",
        "Select Video Narration Style" to "Style de Narration",
        "Speech & Video Language" to "Langue de Parole & Vidéo",
        "Primary Narrator Voice" to "Voix du Narrateur Principal",
        "Selected: " to "Sélectionné: ",
        "Male" to "Homme",
        "Female" to "Femme",
        "Child" to "Enfant",
        "Speech Speed: " to "Vitesse de Parole: ",
        "Speech Pitch: " to "Hauteur de Parole: ",
        "Preview Voice Synths" to "Prévisualiser Syntrhèse Vocale",
        "Select Aspect Ratio" to "Ratio d'Aspect",
        "Select Output Settings" to "Paramètres de Sortie",
        "Resolution" to "Résolution",
        "Video Framerate" to "Fréquence d'Images",
        "Background Soundtrack Overlay" to "Bande Sonore de Fond",
        "Generate Video" to "Générer la Vidéo",
        "Create Reel" to "Créer un Reel",
        "AI Reel Architect" to "Architecte de Reels IA",
        "No Project Drafts Found" to "Aucun Projet Trouvé",
        "No Rendered History" to "Aucun Historique",
        "Delete" to "Supprimer",
        "Cancel" to "Annuler",
        "Remove" to "Enlever",
        "Close" to "Fermer",
        "App Settings" to "Paramètres de l'Application",
        "Preferences" to "Préférences",
        "App Theme" to "Thème de l'App",
        "App Interface Language" to "Langue de l'Interface",
        "AI Video Generation Language" to "Langue de Génération IA",
        "Legal & About" to "Légal & À Propos",
        "Privacy Policy" to "Politique de Confidentialité",
        "Terms & Conditions" to "Conditions Générales",
        "About Yashora Reel Generator" to "À Propos du Générateur Yashora",
        "YASHORA TECHNOLOGIES" to "YASHORA TECHNOLOGIES",
        "Version 1.0.4 (Production Ready)" to "Version 1.0.4 (Prêt pour la Prod)",
        "Visual Timeline Editor" to "Éditeur Visuel",
        "Export" to "Exporter",
        "Empty Track Buffer" to "Buffer de Piste Vide",
        "Chronological Video Track Timeline" to "Chronologie des Séquences",
        "Add Clip" to "Ajouter Séquence",
        "Subtitles" to "Sous-titres",
        "50+ Filters" to "50+ Filtres",
        "Overlays" to "Superpositions",
        "Transitions" to "Transitions",
        "AI Background" to "Arrière-plan IA",
        "Edit Subtitle Text" to "Éditer le Sous-titre",
        "Split Clip" to "Scinder le Clip",
        "Add Sticker" to "Ajouter un Sticker",
        "Rendering Final Output File" to "Rendu du Fichier Final",
        "Multiplexing tracks, speech frames & LUTs..." to "Multiplexage des pistes, voix & LUTs...",
        "Seconds" to "Secondes",
        "s" to "s"
    )

    private val GERMAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "REEL-GENERATOR",
        "Recent Projects" to "Letzte Projekte",
        "Export History" to "Export-Verlauf",
        "Configure Reel Pipeline" to "Reel-Pipeline Konfigurieren",
        "Write / Paste Reel Script" to "Skript Schreiben / Einfügen",
        "Select Video Narration Style" to "Sprecher-Stil Wählen",
        "Speech & Video Language" to "Sprache und Audio",
        "Primary Narrator Voice" to "Hauptsprechergesetz",
        "Selected: " to "Ausgewählt: ",
        "Male" to "Männlich",
        "Female" to "Weiblich",
        "Child" to "Kind",
        "Speech Speed: " to "Sprechgeschwindigkeit: ",
        "Speech Pitch: " to "Tonhöhe: ",
        "Preview Voice Synths" to "Stimmenvorschau",
        "Select Aspect Ratio" to "Seitenverhältnis",
        "Select Output Settings" to "Ausgabeeinstellungen",
        "Resolution" to "Auflösung",
        "Video Framerate" to "Bildrate",
        "Background Soundtrack Overlay" to "Hintergrundmusik",
        "Generate Video" to "Video Generieren",
        "Create Reel" to "Reel Erstellen",
        "AI Reel Architect" to "KI Reel-Architekt",
        "No Project Drafts Found" to "Keine Entwürfe Gefunden",
        "No Rendered History" to "Kein Export-Verlauf",
        "Delete" to "Löschen",
        "Cancel" to "Abbrechen",
        "Remove" to "Entfernen",
        "Close" to "Schließen",
        "App Settings" to "Optionen",
        "Preferences" to "Einstellungen",
        "App Theme" to "App-Design",
        "App Interface Language" to "Sprache der Benutzeroberfläche",
        "AI Video Generation Language" to "KI-Generierungssprache",
        "Legal & About" to "Rechtliches & Info",
        "Privacy Policy" to "Datenschutz",
        "Terms & Conditions" to "Nutzungsbedingungen",
        "About Yashora Reel Generator" to "Über Yashora Reel-Generator",
        "YASHORA TECHNOLOGIES" to "YASHORA TECHNOLOGIES",
        "Version 1.0.4 (Production Ready)" to "Version 1.0.4 (Bereit für Prod)",
        "Visual Timeline Editor" to "Visueller Editor",
        "Export" to "Exportieren",
        "Empty Track Buffer" to "Spuren-Puffer ist Leer",
        "Chronological Video Track Timeline" to "Chronologische Timeline",
        "Add Clip" to "Clip Hinzufügen",
        "Subtitles" to "Untertitel",
        "50+ Filters" to "50+ Filter",
        "Overlays" to "Overlays",
        "Transitions" to "Übergänge",
        "AI Background" to "KI-Hintergrund",
        "Edit Subtitle Text" to "Untertitel Bearbeiten",
        "Split Clip" to "Clip Teilen",
        "Add Sticker" to "Sticker Hinzufügen",
        "Rendering Final Output File" to "Rendern der Ausgabedatei",
        "Multiplexing tracks, speech frames & LUTs..." to "Multiplexen der Spuren, Stimmen & LUTs...",
        "Seconds" to "Sekunden",
        "s" to "s"
    )

    private val ARABIC_MAP = mapOf(
        "Yashora" to "ياشورا",
        "REEL GENERATOR" to "مولد الفيديوهات القصيرة",
        "Recent Projects" to "المشاريع الأخيرة",
        "Export History" to "سجل التصدير",
        "Configure Reel Pipeline" to "إعداد خط ريلز",
        "Write / Paste Reel Script" to "كتابة / لصق النص",
        "Select Video Narration Style" to "اختر أسلوب السرد",
        "Speech & Video Language" to "لغة الصوت والفيديو",
        "Primary Narrator Voice" to "صوت المعلق الرئيسي",
        "Selected: " to "المحدد: ",
        "Male" to "ذكر",
        "Female" to "أنثى",
        "Child" to "طفل",
        "Speech Speed: " to "سرعة الكلام: ",
        "Speech Pitch: " to "طبقة الصوت: ",
        "Preview Voice Synths" to "معاينة الصوت الاصطناعي",
        "Select Aspect Ratio" to "نسبة العرض إلى الارتفاع",
        "Select Output Settings" to "إعدادات الإخراج",
        "Resolution" to "الدقة",
        "Video Framerate" to "معدل الإطارات",
        "Background Soundtrack Overlay" to "الموسيقى الخلفية",
        "Generate Video" to "إنشاء الفيديو",
        "Create Reel" to "إنشاء ريل",
        "AI Reel Architect" to "مهندس ريلز بالذكاء الاصطناعي",
        "No Project Drafts Found" to "لم يتم العثور على مسودات",
        "No Rendered History" to "لا يوجد سجل تصدير",
        "Delete" to "حذف",
        "Cancel" to "إلغاء",
        "Remove" to "إزالة",
        "Close" to "إغلاق",
        "App Settings" to "إعدادات التطبيق",
        "Preferences" to "التفضيلات",
        "App Theme" to "سمة التطبيق",
        "App Interface Language" to "لغة الواجهة",
        "AI Video Generation Language" to "لغة التوليد بالذكاء الاصطناعي",
        "Legal & About" to "قانوني ومعلومات",
        "Privacy Policy" to "سياسة الخصوصية",
        "Terms & Conditions" to "الشروط والأحكام",
        "About Yashora Reel Generator" to "حول مولد ياشورا ريل",
        "YASHORA TECHNOLOGIES" to "ياشورا للتكنولوجيا",
        "Version 1.0.4 (Production Ready)" to "إصدار 1.0.4 (جاهز للإنتاج)",
        "Visual Timeline Editor" to "محرر المخطط الزمني",
        "Export" to "تصدير",
        "Empty Track Buffer" to "مسار الفيديو فارغ",
        "Chronological Video Track Timeline" to "مخطط الفيديو الزمني",
        "Add Clip" to "إضافة مقطع",
        "Subtitles" to "الترجمة المصاحبة",
        "50+ Filters" to "+٥٠ فلتر",
        "Overlays" to "التراكبات",
        "Transitions" to "الانتقالات",
        "AI Background" to "خلفية الذكاء الاصطناعي",
        "Edit Subtitle Text" to "تعديل النص",
        "Split Clip" to "تقسيم المقطع",
        "Add Sticker" to "إضافة ملصق",
        "Rendering Final Output File" to "رسم ملف الإخراج النهائي",
        "Multiplexing tracks, speech frames & LUTs..." to "دمج المسارات والإطارات الفنية...",
        "Seconds" to "ثواني",
        "s" to "ث"
    )

    private val CHINESE_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "短视频生成器",
        "Recent Projects" to "最近的项目",
        "Export History" to "导出历史纪录",
        "Configure Reel Pipeline" to "配置短视频管道",
        "Write / Paste Reel Script" to "编写或粘贴脚本",
        "Select Video Narration Style" to "选择视频朗读风格",
        "Speech & Video Language" to "语音与视频语言",
        "Primary Narrator Voice" to "主讲人声音",
        "Selected: " to "已选择: ",
        "Male" to "男声",
        "Female" to "女声",
        "Child" to "童声",
        "Speech Speed: " to "语速: ",
        "Speech Pitch: " to "音高: ",
        "Preview Voice Synths" to "预览合成声音",
        "Select Aspect Ratio" to "选择视频比例",
        "Select Output Settings" to "输出设置",
        "Resolution" to "分辨率",
        "Video Framerate" to "视频帧率",
        "Background Soundtrack Overlay" to "配乐叠加",
        "Generate Video" to "生成视频",
        "Create Reel" to "创建短视频",
        "AI Reel Architect" to "AI短视频架构师",
        "No Project Drafts Found" to "没有找到草稿",
        "No Rendered History" to "无导出记录",
        "Delete" to "删除",
        "Cancel" to "取消",
        "Remove" to "移除",
        "Close" to "关闭",
        "App Settings" to "应用设置",
        "Preferences" to "用户偏好",
        "App Theme" to "应用主题",
        "App Interface Language" to "应用界面语言",
        "AI Video Generation Language" to "人工智能视频语言",
        "Legal & About" to "法律与关于",
        "Privacy Policy" to "隐私政策",
        "Terms & Conditions" to "用户条款",
        "About Yashora Reel Generator" to "关于 Yashora 短视频生成器",
        "YASHORA TECHNOLOGIES" to "Yashora 科技",
        "Version 1.0.4 (Production Ready)" to "版本 1.0.4 (生产版本)",
        "Visual Timeline Editor" to "可视化时间轴编辑器",
        "Export" to "导出",
        "Empty Track Buffer" to "空轨道缓存",
        "Chronological Video Track Timeline" to "视频画幅时间轴",
        "Add Clip" to "添加视频夹",
        "Subtitles" to "字幕",
        "50+ Filters" to "50+ 滤镜",
        "Overlays" to "叠加文字",
        "Transitions" to "过渡效果",
        "AI Background" to "智能背景生成",
        "Edit Subtitle Text" to "编辑字幕文本",
        "Split Clip" to "裁剪分段",
        "Add Sticker" to "添加贴纸",
        "Rendering Final Output File" to "渲染最终输出文件",
        "Multiplexing tracks, speech frames & LUTs..." to "合成音轨、视频帧与滤镜中...",
        "Seconds" to "秒",
        "s" to "秒"
    )

    private val JAPANESE_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "リールジェネレータ",
        "Recent Projects" to "最近のプロジェクト",
        "Export History" to "エクスポート履歴",
        "Configure Reel Pipeline" to "パイプライン構成",
        "Write / Paste Reel Script" to "スクリプトを作成・貼り付け",
        "Select Video Narration Style" to "ナレーションスタイル選択",
        "Speech & Video Language" to "音声とビデオ言語",
        "Primary Narrator Voice" to "メインナレーター音声",
        "Selected: " to "選択済み: ",
        "Male" to "男性",
        "Female" to "女性",
        "Child" to "子供",
        "Speech Speed: " to "話速: ",
        "Speech Pitch: " to "ピッチ: ",
        "Preview Voice Synths" to "音声をプレビュー",
        "Select Aspect Ratio" to "アスペクト比選択",
        "Select Output Settings" to "出力設定",
        "Resolution" to "解像度",
        "Video Framerate" to "フレームレート",
        "Background Soundtrack Overlay" to "BGMオーバーレイ",
        "Generate Video" to "ビデオ生成",
        "Create Reel" to "リールを作成",
        "AI Reel Architect" to "AIリールデザイナー",
        "No Project Drafts Found" to "下書きが見つかりませんでした",
        "No Rendered History" to "保存されたビデオはありません",
        "Delete" to "削除",
        "Cancel" to "キャンセル",
        "Remove" to "削除",
        "Close" to "閉じる",
        "App Settings" to "アプリ設定",
        "Preferences" to "環境設定",
        "App Theme" to "アプリテーマ",
        "App Interface Language" to "アプリインターフェース言語",
        "AI Video Generation Language" to "AIビデオ生成言語",
        "Legal & About" to "法規・概要",
        "Privacy Policy" to "プライバシーポリシー",
        "Terms & Conditions" to "利用規約",
        "About Yashora Reel Generator" to "Yashoraについて",
        "YASHORA TECHNOLOGIES" to "Yashoraテクノロジーズ",
        "Version 1.0.4 (Production Ready)" to "バージョン 1.0.4 (製品版)",
        "Visual Timeline Editor" to "見取り時間枠エディタ",
        "Export" to "エクスポート",
        "Empty Track Buffer" to "トラックが空です",
        "Chronological Video Track Timeline" to "タイムライン",
        "Add Clip" to "クリップ追加",
        "Subtitles" to "字幕",
        "50+ Filters" to "50+ フィルタ",
        "Overlays" to "オーバーレイ",
        "Transitions" to "トランジション",
        "AI Background" to "AI背景生成",
        "Edit Subtitle Text" to "字幕編集",
        "Split Clip" to "クリップ分割",
        "Add Sticker" to "ステッカー挿入",
        "Rendering Final Output File" to "最終出力ファイルをレンダリング中",
        "Multiplexing tracks, speech frames & LUTs..." to "トラック、音声、LUTのマルチプレクシング中...",
        "Seconds" to "秒",
        "s" to "秒"
    )

    private val PORTUGUESE_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "GERADOR DE REELS",
        "Recent Projects" to "Projetos Recentes",
        "Export History" to "Histórico de Exportação",
        "Configure Reel Pipeline" to "Configurar Canal de Reels",
        "Write / Paste Reel Script" to "Escrever / Colar Guião",
        "Select Video Narration Style" to "Estilo de Narração",
        "Speech & Video Language" to "Idioma de Voz e Vídeo",
        "Primary Narrator Voice" to "Voz do Narrador Principal",
        "Selected: " to "Selecionado: ",
        "Male" to "Masculino",
        "Female" to "Feminino",
        "Child" to "Criança",
        "Speech Speed: " to "Velocidade de Fala: ",
        "Speech Pitch: " to "Tom de Voz: ",
        "Preview Voice Synths" to "Pré-visualizar Voz Sintetizada",
        "Select Aspect Ratio" to "Proporção de Tela",
        "Select Output Settings" to "Configurações de Saída",
        "Resolution" to "Resolução",
        "Video Framerate" to "Taxa de Quadros",
        "Background Soundtrack Overlay" to "Música de Fundo",
        "Generate Video" to "Gerar Vídeo",
        "Create Reel" to "Criar Reel",
        "AI Reel Architect" to "Arquiteto de Reels de IA",
        "No Project Drafts Found" to "Nenhum Rascunho Encontrado",
        "No Rendered History" to "Sem Históricos de Exportação",
        "Delete" to "Excluir",
        "Cancel" to "Cancelar",
        "Remove" to "Remover",
        "Close" to "Fechar",
        "App Settings" to "Definições do App",
        "Preferences" to "Preferências",
        "App Theme" to "Tema do App",
        "App Interface Language" to "Idioma da Interface",
        "AI Video Generation Language" to "Idioma de Geração da IA",
        "Legal & About" to "Legal e Sobre",
        "Privacy Policy" to "Política de Privacidade",
        "Terms & Conditions" to "Termos e Condições",
        "About Yashora Reel Generator" to "Sobre Gerador Yashora",
        "YASHORA TECHNOLOGIES" to "TECNOLOGIAS YASHORA",
        "Version 1.0.4 (Production Ready)" to "Versão 1.0.4 (Pronto para Uso)",
        "Visual Timeline Editor" to "Editor Visual",
        "Export" to "Exportar",
        "Empty Track Buffer" to "Buffer de Linha de Trilha Vazio",
        "Chronological Video Track Timeline" to "Linha do Tempo Cronológica",
        "Add Clip" to "Adicionar Clipe",
        "Subtitles" to "Legendas",
        "50+ Filters" to "Mais de 50 Filtros",
        "Overlays" to "Superposições",
        "Transitions" to "Transições",
        "AI Background" to "Fundo de IA",
        "Edit Subtitle Text" to "Editar Legenda",
        "Split Clip" to "Dividir Clipe",
        "Add Sticker" to "Adicionar Autocolante",
        "Rendering Final Output File" to "Renderizando Arquivo Final",
        "Multiplexing tracks, speech frames & LUTs..." to "Multiplexando faixas de áudio, voz e LUTs...",
        "Seconds" to "Segundos",
        "s" to "s"
    )

    private val RUSSIAN_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "ГЕНЕРАТОР REELS",
        "Recent Projects" to "Недавние проекты",
        "Export History" to "История экспорта",
        "Configure Reel Pipeline" to "Настроить генерацию",
        "Write / Paste Reel Script" to "Написать / Вставить игровой сценарий",
        "Select Video Narration Style" to "Стиль озвучки",
        "Speech & Video Language" to "Язык субтитров и звука",
        "Primary Narrator Voice" to "Основной голос",
        "Selected: " to "Выбран: ",
        "Male" to "Мужской",
        "Female" to "Женский",
        "Child" to "Детский",
        "Speech Speed: " to "Скорость речи: ",
        "Speech Pitch: " to "Высота голоса: ",
        "Preview Voice Synths" to "Прослушать голос",
        "Select Aspect Ratio" to "Формат кадра",
        "Select Output Settings" to "Настройки видео",
        "Resolution" to "Разрешение",
        "Video Framerate" to "Частота кадров",
        "Background Soundtrack Overlay" to "Фоновая музыка",
        "Generate Video" to "Создать видео",
        "Create Reel" to "Создать Reel",
        "AI Reel Architect" to "AI конструктор Reels",
        "No Project Drafts Found" to "Черновиков не найдено",
        "No Rendered History" to "История экспорта пуста",
        "Delete" to "Удалить",
        "Cancel" to "Отмена",
        "Remove" to "Исключить",
        "Close" to "Закрыть",
        "App Settings" to "Настройки приложения",
        "Preferences" to "Параметры",
        "App Theme" to "Тема оформления",
        "App Interface Language" to "Язык интерфейса",
        "AI Video Generation Language" to "Язык ИИ для генерации",
        "Legal & About" to "Юридическая информация",
        "Privacy Policy" to "Политика конфиденциальности",
        "Terms & Conditions" to "Условия использования",
        "About Yashora Reel Generator" to "О Yashora Reel",
        "YASHORA TECHNOLOGIES" to "Yashora технологии",
        "Version 1.0.4 (Production Ready)" to "Версия 1.0.4 (Релиз)",
        "Visual Timeline Editor" to "Визуальный редактор",
        "Export" to "Экспорт",
        "Empty Track Buffer" to "Буфер кадров пуст",
        "Chronological Video Track Timeline" to "Временная шкала",
        "Add Clip" to "Добавить клип",
        "Subtitles" to "Субтитры",
        "50+ Filters" to "50+ Фильтров",
        "Overlays" to "Оверлеи",
        "Transitions" to "Переходы",
        "AI Background" to "ИИ Фон",
        "Edit Subtitle Text" to "Изменить текст субтитров",
        "Split Clip" to "Разделить кадр",
        "Add Sticker" to "Добавить стикер",
        "Rendering Final Output File" to "Рендеринг финального файла",
        "Multiplexing tracks, speech frames & LUTs..." to "Сведение дорожек, речи и эффектов...",
        "Seconds" to "секунд",
        "s" to "с"
    )

    private val TURKISH_MAP = mapOf(
        "Yashora" to "Yashora",
        "REEL GENERATOR" to "REEL OLUŞTURUCU",
        "Recent Projects" to "Son Projeler",
        "Export History" to "Dışa Aktarma Geçmişi",
        "Configure Reel Pipeline" to "Reel Sürecini Yapılandır",
        "Write / Paste Reel Script" to "Senaryo Yaz veya Yapıştır",
        "Select Video Narration Style" to "Seslendirme Stilini Seç",
        "Speech & Video Language" to "Seslendirme ve Video Dili",
        "Primary Narrator Voice" to "Birincil Anlatıcı Sesi",
        "Selected: " to "Seçilen: ",
        "Male" to "Erkek",
        "Female" to "Kadın",
        "Child" to "Çocuk",
        "Speech Speed: " to "Konuşma Hızı: ",
        "Speech Pitch: " to "Ses Tonu (Pitch): ",
        "Preview Voice Synths" to "Sesi Önizle",
        "Select Aspect Ratio" to "En-Boy Oranı Seç",
        "Select Output Settings" to "Çıktı Ayarları",
        "Resolution" to "Çözünürlük",
        "Video Framerate" to "Video Kare Hızı (FPS)",
        "Background Soundtrack Overlay" to "Halka Müzik Ekleme",
        "Generate Video" to "Videoyu Oluştur",
        "Create Reel" to "Reel Oluştur",
        "AI Reel Architect" to "AI Video Mimarı",
        "No Project Drafts Found" to "Taslak Bulunamadı",
        "No Rendered History" to "Aktarılmış Video Yok",
        "Delete" to "Sil",
        "Cancel" to "İptal",
        "Remove" to "Kaldır",
        "Close" to "Kapat",
        "App Settings" to "Uygulama Ayarları",
        "Preferences" to "Tercihler",
        "App Theme" to "Uygulama Teması",
        "App Interface Language" to "Uygulama Arayüz Dili",
        "AI Video Generation Language" to "Yapay Zeka Video Dili",
        "Legal & About" to "Yasal ve Hakkında",
        "Privacy Policy" to "Gizlilik Politikası",
        "Terms & Conditions" to "Kullanım Koşulları",
        "About Yashora Reel Generator" to "Yashora Hakkında",
        "YASHORA TECHNOLOGIES" to "YASHORA TEKNOLOJİLERİ",
        "Version 1.0.4 (Production Ready)" to "Sürüm 1.0.4 (Yayına Hazır)",
        "Visual Timeline Editor" to "Görsel Zaman Tüneli Düzenleyici",
        "Export" to "Dışa Aktar",
        "Empty Track Buffer" to "İçerik Bulunmuyor",
        "Chronological Video Track Timeline" to "Kronolojik Video Akışı",
        "Add Clip" to "Klip Ekle",
        "Subtitles" to "Alt Yazılar",
        "50+ Filters" to "50+ Filtre",
        "Overlays" to "Yer Paylaşımları",
        "Transitions" to "Geçişler",
        "AI Background" to "Yapay Zeka Arka Planı",
        "Edit Subtitle Text" to "Alt Yazıyı Düzenle",
        "Split Clip" to "Klibi Böl",
        "Add Sticker" to "Çıkartma Ekle",
        "Rendering Final Output File" to "Son Dosya Kaydediliyor",
        "Multiplexing tracks, speech frames & LUTs..." to "Ses, efekt ve şablonlar birleştiriliyor...",
        "Seconds" to "Saniye",
        "s" to "sn"
    )

    private val URDU_MAP = mapOf(
        "Yashora" to "یشورا",
        "REEL GENERATOR" to "ریل جنیریٹر",
        "Configure Reel Pipeline" to "ریل پائپ لائن تشکیل دیں",
        "Write / Paste Reel Script" to "ریل اسکرپٹ لکھیں / پیسٹ کریں",
        "Enter or paste your script here. The AI will segment it into scenes, narrate compiling voices, and generate visual prompts automatically..." to "اپنا اسکرپٹ یہاں درج یا پیسٹ کریں۔ AI اسے مناظر میں تقسیم کرے گا، آواز وضع کرے گا، اور خودکار طور پر تصویری اشارے تیار کرے گا...",
        "Select Video Narration Style" to "ویڈیو بیانیہ کا انداز منتخب کریں",
        "Warm storybook textures and soft focuses" to "گرم کہانی کہانی ساخت اور نرم فوکس",
        "Speech & Video Language" to "گفتگو اور ویڈیو زبان",
        "This controls the spoken accents & subtitles" to "یہ بولی جانے والی لہجے اور سب ٹائٹلز کو کنٹرول کرتا ہے",
        "Primary Narrator Voice" to "بنیادی بیانیہ آواز",
        "Selected: " to "منتخب کردہ: ",
        "Male" to "مرد",
        "Female" to "عورت",
        "Child" to "بچہ",
        "Speech Speed: " to "آواز کی رفتار: ",
        "Speech Pitch: " to "آواز کا پچ: ",
        "Preview Voice Synths" to "آواز کا نمونہ سنیں",
        "Select Aspect Ratio" to "امتیازی تناسب منتخب کریں",
        "Select Output Settings" to "آؤٹ پٹ ترتیبات منتخب کریں",
        "Resolution" to "ریزولیوشن",
        "Video Framerate" to "ویڈیو فریم ریٹ",
        "Background Soundtrack Overlay" to "بیک گراؤنڈ ساؤنڈ ٹریک اوورلے",
        "Add smart rhythmic backing beats" to "اسمارٹ تال پس منظر بیٹس شامل کریں",
        "Music Level: " to "موسیقی کی سطح: ",
        "Voice Level: " to "آواز کی سطح: ",
        "Generate Video" to "ویڈیو تیار کریں",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "اسکرپٹ کو اپنی مرضی کے مطابق نیورل ماڈلز کے ساتھ لچکدار بصری اسٹوری بورڈز میں فوری تبدیل کریں۔",
        "Create Reel" to "ریل بنائیں",
        "AI Reel Architect" to "اے آئی رీల آرکیٹیکٹ",
        "Recent Projects" to "حالیہ پروجیکٹس",
        "Export History" to "ایکسپورٹ کی سرگزشت",
        "No Project Drafts Found" to "کوئی پروجیکٹ ڈرافٹ نہیں ملا",
        "Click 'Create Reel' at the bottom right corner to start breaking down scripts" to "اسکرپٹ شروع کرنے کے لیے نیچے دائیں کونے میں 'ریل بنائیں' پر کلک کریں",
        "No Rendered History" to "کوئی رینڈر شدہ تاریخ نہیں ہے",
        "Once you configure storyboards and export them, generated MP4 entries will persist here" to "ایک بار جب آپ اسٹوری بورڈز ترتیب دیں اور ایکسپورٹ کریں، تیار کردہ MP4 یہاں محفوظ ہوں گے",
        "Delete Project draft?" to "پروجیکٹ ڈرافٹ حذف کریں؟",
        "Are you sure you want to delete" to "کیا آپ واقعی حذف کرنا چاہتے ہیں",
        "permanently? This action cannot be undone." to "مستقل طور پر؟ یہ عمل واپس نہیں لیا جا سکتا۔",
        "Delete" to "حذف کریں",
        "Cancel" to "منسوخ کریں",
        "Remove Export Entry?" to "ایکسپورٹ ہسٹری حذف کریں؟",
        "This will delete the history log for" to "یہ تاریخ کے ریکارڈ کو حذف کر دے گا برائے",
        "It does not delete physical MP4 off device storage." to "یہ آلہ کے اسٹوریج سے اصل MP4 کو حذف نہیں کرتا۔",
        "Remove" to "حذف کریں",
        "App Settings" to "ایپ की ترतीبات",
        "Back" to "واپس",
        "Preferences" to "ترجیحات",
        "Settings" to "ترتیبات",
        "App Theme" to "ایپ تھیم",
        "App Interface Language" to "ایپ انٹرفیس زبان",
        "AI Video Generation Language" to "ویڈیو جنریشن زبان",
        "Legal & About" to "قانونی اور معلومات",
        "Privacy Policy" to "رازداری کی پالیسی",
        "How we protect, save and manage your credentials" to "ہم آپ کے کواڈنشیلز کو کیسے محفوظ اور منظم کرتے ہیں",
        "Terms & Conditions" to "شرائط و ضوابط",
        "Agreement governing AI reel pipeline software usage" to "ساف트 ویئر کے استعمال کو کنٹرول کرنے کا معاہدہ",
        "About Yashora Reel Generator" to "یشورا ریل جنیریٹر کے بارے میں",
        "App version, framework and technologies used" to "ایپ کا ورژن، فریم ورک اور استعمال شدہ ٹیکنالوجی",
        "YASHORA TECHNOLOGIES" to "یشورا ٹیکنالوجیز",
        "Version 1.0.4 (Production Ready)" to "ورژن 1.0.4 (تیار شدہ)",
        "Select Theme Selection" to "تھیم منتخب کریں",
        "Select Language" to "زبان منتخب کریں",
        "English" to "انگریزی",
        "Hindi" to "ہندی",
        "Arabic" to "عربی",
        "Urdu" to "اردو",
        "Bengali" to "بنگالی",
        "Tamil" to "تامل",
        "Telugu" to "تیلگو",
        "Japanese" to "جاپانی",
        "Chinese" to "چینی",
        "Korean" to "کوریائی",
        "German" to "جرمن",
        "French" to "فرانسیسی",
        "Spanish" to "ہسپانوی",
        "Portuguese" to "پرتگالی",
        "Russian" to "روسی",
        "Turkish" to "ترکی",
        "Visual Timeline Editor" to "بصری ٹائم لائن ایڈیٹر",
        "Export" to "ایکسپورٹ",
        "Empty Track Buffer" to "خالی ٹریک بفر",
        "Preview Voice" to "آواز کا نمونہ",
        "Chronological Video Track Timeline" to "ترتیب وار ویڈیو ٹریک ٹائم لائن",
        "Add Clip" to "کلپ شامل کریں",
        "Subtitles" to "سب ٹائٹلز",
        "50+ Filters" to "50+ فلٹرز",
        "Overlays" to "اوورلے",
        "Transitions" to "ٹرانزیشن",
        "AI Background" to "مصنوعی پس منظر",
        "Edit Subtitle Text" to "سب ٹائٹل متن تبدیل کریں",
        "Split Clip" to "کلپ تقسیم کریں",
        "Add Sticker" to "اسٹیکر شامل کریں",
        "Rendering Final Output File" to "آخری آؤٹ پٹ فائل تیار کی جا رہی ہے",
        "Multiplexing tracks, speech frames & LUTs..." to "ٹریکس مکس اور کمپائل ہو رہے ہیں...",
        "Seconds" to "سیکنڈ",
        "s" to "سیکنڈ"
    )

    private val BENGALI_MAP = mapOf(
        "Yashora" to "যশোরা",
        "REEL GENERATOR" to "রিল জেনারেটর",
        "Configure Reel Pipeline" to "রিল পাইপলাইন কনফিগার করুন",
        "Write / Paste Reel Script" to "রিল স্ক্রিপ্ট লিখুন / পেস্ট করুন",
        "Enter or paste your script here. The AI will segment it into scenes, narrate compiling voices, and generate visual prompts automatically..." to "এখানে আপনার স্ক্রিপ্ট লিখুন বা পেস্ট করুন। এআই এটি দৃশ্যে ভাগ করবে, ভয়েস বর্ণনা করবে এবং স্বয়ংক্রিয়ভাবে ভিজ্যুয়াল প্রম্পট তৈরি করবে...",
        "Select Video Narration Style" to "ভিডিও বর্ণনা শৈলী নির্বাচন করুন",
        "Warm storybook textures and soft focuses" to "উষ্ণ স্টোরিবুক টেক্সচার এবং সফ্ট ফোকাস",
        "Speech & Video Language" to "ভাষণ এবং ভিডিওর ভাষা",
        "This controls the spoken accents & subtitles" to "এটি কথ্য উচ্চারণ এবং সাবটাইটেল নিয়ন্ত্রণ করে",
        "Primary Narrator Voice" to "প্রাথমিক কথকের ভয়েস",
        "Selected: " to "নির্বাচিত: ",
        "Male" to "পুরুষ",
        "Female" to "মহিলা",
        "Child" to "শিশু",
        "Speech Speed: " to "গতি: ",
        "Speech Pitch: " to "উচ্চতা: ",
        "Preview Voice Synths" to "ভয়েসের পূর্বরূপ দেখুন",
        "Select Aspect Ratio" to "অ্যাসপেক্ট রেশিও নির্বাচন করুন",
        "Select Output Settings" to "আউটপুট সেটিংস নির্বাচন করুন",
        "Resolution" to "রেজোলিউশন",
        "Video Framerate" to "ভিডিও ফ্রেমরেট",
        "Background Soundtrack Overlay" to "ব্যাকগ্রাউন্ড সাউন্ডট্র্যাক ওভারলে",
        "Add smart rhythmic backing beats" to "স্মার্ট ব্যাকগ্রাউন্ড বিট যোগ করুন",
        "Music Level: " to "মিউজিক লেভেল: ",
        "Voice Level: " to "ভয়েস লেভেল: ",
        "Generate Video" to "ভিডিও তৈরি করুন",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "স্ক্রিপ্টগুলিকে তাত্ক্ষণিকভাবে কাস্টম নিউরাল মডেলের সাথে সমৃদ্ধ ভিজ্যুয়াল স্টোরিবোর্ডে রূপান্তর করুন।",
        "Create Reel" to "রিল তৈরি করুন",
        "AI Reel Architect" to "এআই রিল আর্কিটেক্ট",
        "Recent Projects" to "সাম্প্রতিক প্রকল্পগুলি",
        "Export History" to "রপ্তানি ইতিহাস",
        "No Project Drafts Found" to "কোনো খসড়া প্রকল্প পাওয়া যায়নি",
        "Click 'Create Reel' at the bottom right corner to start breaking down scripts" to "স্ক্রিপ্ট শুরু করার জন্য নিচে ডানদিকের কোণায় 'রিল তৈরি করুন' বাটনে ক্লিক করুন",
        "No Rendered History" to "কোনো রেন্ডার ইতিহাস নেই",
        "Once you configure storyboards and export them, generated MP4 entries will persist here" to "একবার আপনি স্টোরিবোর্ডগুলি কনফিগার এবং রপ্তানি করলে, তৈরি করা MP4 এখানে থাকবে",
        "Delete Project draft?" to "প্রকল্পের খসড়া মুছবেন?",
        "Are you sure you want to delete" to "আপনি কি নিশ্চিত যে মুছতে চান",
        "permanently? This action cannot be undone." to "স্থায়ীভাবে? এই কাজটি আর রোলব্যাক করা যাবে না।",
        "Delete" to "মুছুন",
        "Cancel" to "বাতিল",
        "Remove Export Entry?" to "রপ্তানি এন্ট্রি সরান?",
        "This will delete the history log for" to "এটি ইতিহাসের লগ মুছে ফেলবে",
        "It does not delete physical MP4 off device storage." to "এটি ডিভাইস স্টোরেজ থেকে মূল MP4 মুছে ফেলে না।",
        "Remove" to "সরান",
        "App Settings" to "অ্যাপ সেটিংস",
        "Back" to "পিছনে",
        "Preferences" to "পছন্দসমূহ",
        "Settings" to "সেটিংস",
        "App Theme" to "অ্যাপের থিম",
        "App Interface Language" to "অ্যাপ ইন্টারফেসের ভাষা",
        "AI Video Generation Language" to "ভিডিও তৈরির ভাষা",
        "Legal & About" to "আইনি এবং তথ্য",
        "Privacy Policy" to "গোপনীয়তা नीति",
        "How we protect, save and manage your credentials" to "আমরা কীভাবে তথ্য রক্ষা, সংরক্ষণ এবং পরিচালনা করি",
        "Terms & Conditions" to "নিয়ম ও শর্তাবলী",
        "Agreement governing AI reel pipeline software usage" to "এআই রিল সফটওয়্যার ব্যবহারের জন্য চুক্তি",
        "About Yashora Reel Generator" to "যশোরা রিল জেনারেটর সম্পর্কে",
        "App version, framework and technologies used" to "অ্যাপ্লিকেশন সংস্করণ, ব্যবহৃত প্রযুক্তি",
        "YASHORA TECHNOLOGIES" to "যশোরা টেকনোলজিস",
        "Version 1.0.4 (Production Ready)" to "সংস্করণ ১.০.৪ (প্রস্তুত)",
        "Select Theme Selection" to "থিম পছন্দ করুন",
        "Select Language" to "ভাষা পছন্দ করুন",
        "English" to "ইংরেজি",
        "Hindi" to "হিন্দি",
        "Arabic" to "আরবি",
        "Urdu" to "উর্দু",
        "Bengali" to "বাংলা",
        "Tamil" to "তামিল",
        "Telugu" to "তেলেগু",
        "Japanese" to "জাপানি",
        "Chinese" to "চীনা",
        "Korean" to "কোরিয়ান",
        "German" to "জার্মান",
        "French" to "ফরাসি",
        "Spanish" to "স্পেনীয়",
        "Portuguese" to "পর্তুগিজ",
        "Russian" to "রুশ",
        "Turkish" to "তুর্কি",
        "Visual Timeline Editor" to "ভিজ্যুয়াল টাইমলাইন সম্পাদক",
        "Export" to "রপ্তানি",
        "Empty Track Buffer" to "খালি ট্র্যাক বাফার",
        "Preview Voice" to "ভয়েস প্রিভিউ",
        "Chronological Video Track Timeline" to "ভিডিও ট্র্যাক টাইমলাইন",
        "Add Clip" to "ক্লিপ যোগ করুন",
        "Subtitles" to "সাবটাইটেল",
        "50+ Filters" to "৫০+ ফিল্টার",
        "Overlays" to "ওভারলে",
        "Transitions" to "ট্রানজিশন",
        "AI Background" to "এআই ব্যাকগ্রাউন্ড",
        "Edit Subtitle Text" to "সাবটাইটেল সম্পাদনা করুন",
        "Split Clip" to "ক্লিপ ভাগ করুন",
        "Add Sticker" to "স্টিকার যোগ করুন",
        "Rendering Final Output File" to "চূড়ান্ত আউটপুট ফাইল রেন্ডার করা হচ্ছে",
        "Multiplexing tracks, speech frames & LUTs..." to "ট্র্যাক এবং অডিও কম্পাইল করা হচ্ছে...",
        "Seconds" to "সেকেন্ড",
        "s" to "সেকেন্ড"
    )

    private val TAMIL_MAP = mapOf(
        "Yashora" to "யஷோரா",
        "REEL GENERATOR" to "ரீல் ஜெனரேட்டர்",
        "Configure Reel Pipeline" to "ரீல் பைப்லைனை உள்ளமைக்கவும்",
        "Write / Paste Reel Script" to "ரீல் ஸ்கிரிப்ட் எழுதுக / ஒட்டுக",
        "Enter or paste your script here. The AI will segment it into scenes, narrate compiling voices, and generate visual prompts automatically..." to "உங்கள் ஸ்கிரிப்டை இங்கே எழுதவும் அல்லது ஒட்டவும். செயற்கை அறிவுத்திறன் இதை காட்சிகளாக பிரித்து, பின்னணி ஓலி உருவாக்கி விளக்கும்...",
        "Select Video Narration Style" to "வீடியோ கதை நடை தேர்வு",
        "Warm storybook textures and soft focuses" to "வெதுவெதுப்பான கதை புத்தக அமைப்புகள் மற்றும் மென்மையான கவனம்",
        "Speech & Video Language" to "பேச்சு & வீடியோ மொழி",
        "This controls the spoken accents & subtitles" to "இது ஒலிப்பு உச்சரிப்பு மற்றும் வசனங்களை கட்டுப்படுத்தும்",
        "Primary Narrator Voice" to "முதன்மை கதைகூறுபவர் குரல்",
        "Selected: " to "தேர்ந்தெடுக்கப்பட்டது: ",
        "Male" to "ஆண்",
        "Female" to "பெண்",
        "Child" to "குழந்தை",
        "Speech Speed: " to "பேச்சு வேகம்: ",
        "Speech Pitch: " to "பேச்சு சுருதி: ",
        "Preview Voice Synths" to "குรல் மாதிரியைக் கேட்க",
        "Select Aspect Ratio" to "விகிதம் தேர்வு செய்க",
        "Select Output Settings" to "வெளியீட்டு அமைப்புகள்",
        "Resolution" to "தெளிவுத்திறன்",
        "Video Framerate" to "வீடியோ பிரேம்ரேட்",
        "Background Soundtrack Overlay" to "பின்னணி இசை மேலடுக்கு",
        "Add smart rhythmic backing beats" to "ஸ்மார்ட் பின்னணி தாளங்களைச் சேர்க்கவும்",
        "Music Level: " to "இசை அளவு: ",
        "Voice Level: " to "குரல் அளவு: ",
        "Generate Video" to "வீடியோவை உருவாக்கு",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "ஸ்கிரிப்ட்களை உடனடித் தனிப்பயன் நியூরাল மாதிரிகளுடன் காட்சி பதிவாக மாற்றவும்.",
        "Create Reel" to "ரீலை உருவாக்கு",
        "AI Reel Architect" to "ஏஐ ரீல் ஆர்க்கிடெக்ட்",
        "Recent Projects" to "சமீபத்திய திட்டங்கள்",
        "Export History" to "ஏற்றுமதி வரலாறு",
        "No Project Drafts Found" to "திட்ட வரைவுகள் ஏதும் இல்லை",
        "Click 'Create Reel' at the bottom right corner to start breaking down scripts" to "ஸ்கிரிப்ட் உருவாக்க கீழ் வலது மூலையில் உள்ள 'ரீலை உருவாக்கு' பொத்தானை அழுத்தவும்",
        "No Rendered History" to "சேமிக்கப்பட்ட வரலாறு ஏதுமில்லை",
        "Once you configure storyboards and export them, generated MP4 entries will persist here" to "நீங்கள் காட்சிகளை அமைத்து ஏற்றுமதி செய்ததும், உருவாக்கப்பட்ட MP4 கோப்புகள் இங்கே காண்பிக்கப்படும்",
        "Delete Project draft?" to "வரைவை நீக்கவா?",
        "Are you sure you want to delete" to "நிச்சயமாக நீக்க விரும்புகிறீர்களா",
        "permanently? This action cannot be undone." to "முற்றிலுமாக? இந்தச் செயலைத் திரும்பப் பெற முடியாது.",
        "Delete" to "நீக்குக",
        "Cancel" to "ரத்துசெய்",
        "Remove Export Entry?" to "வரலாற்றை நீக்கவா?",
        "This will delete the history log for" to "இது வரலாற்றுக் குறிப்பை நீக்கும்",
        "It does not delete physical MP4 off device storage." to "இது சாதன சேமிப்பகத்திலிருந்து மூல MP4 கோப்பை நீக்காது.",
        "Remove" to "நீக்கு",
        "App Settings" to "பயன்பாட்டு அமைப்புகள்",
        "Back" to "பின்னால்",
        "Preferences" to "விருப்பத்தேர்வுகள்",
        "Settings" to "அமைப்புகள்",
        "App Theme" to "பயன்பாட்டு தீம்",
        "App Interface Language" to "பயன்பாட்டு இடைமுக மொழி",
        "AI Video Generation Language" to "வீடியோ உருவாக்க மொழி",
        "Legal & About" to "சட்டப்பூர்வ & தகவல்",
        "Privacy Policy" to "தனியுரிமைக் கொள்கை",
        "How we protect, save and manage your credentials" to "உங்கள் நற்சான்றிதழ்களை நாங்கள் எவ்வாறு பாதுகாக்கிறோம்",
        "Terms & Conditions" to "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
        "Agreement governing AI reel pipeline software usage" to "மென்பொருள் பயன்பாட்டு ஒப்பந்தம்",
        "About Yashora Reel Generator" to "யஷோரா ரீல் ஜெனரேட்டர் பற்றி",
        "App version, framework and technologies used" to "பயன்பாட்டு பதிப்பு, பயன்படுத்தப்பட்ட தொழில்நுட்பங்கள்",
        "YASHORA TECHNOLOGIES" to "யஷோரா டெக்னாலஜிஸ்",
        "Version 1.0.4 (Production Ready)" to "பதிப்பு 1.0.4 (தயார் நிலை)",
        "Select Theme Selection" to "தீம் தேர்ந்தெடுக்கவும்",
        "Select Language" to "மொழியைத் தேர்ந்தெடுக்கவும்",
        "English" to "ஆங்கிலம்",
        "Hindi" to "இந்தி",
        "Arabic" to "அரபு",
        "Urdu" to "உருது",
        "Bengali" to "வங்காளம்",
        "Tamil" to "தமிழ்",
        "Telugu" to "தெலுங்கு",
        "Japanese" to "ஜப்பானிய",
        "Chinese" to "சீன",
        "Korean" to "கொரிய",
        "German" to "ஜெர்மन",
        "French" to "பிரஞ்சு",
        "Spanish" to "ஸ்பானிஷ்",
        "Portuguese" to "போர்த்துகீசியம்",
        "Russian" to "ரஷ்ய",
        "Turkish" to "துருக்கிய",
        "Visual Timeline Editor" to "காட்சி காலவரிசை திருத்தி",
        "Export" to "ஏற்றுமதி",
        "Empty Track Buffer" to "தடங்கள் ஏதுமில்லை",
        "Preview Voice" to "குரல் முன்னோட்டம்",
        "Chronological Video Track Timeline" to "காட்சி காலவரிசை",
        "Add Clip" to "கிளிப் சேர்",
        "Subtitles" to "துணைத்தலைப்புகள்",
        "50+ Filters" to "50+ வடிகட்டிகள்",
        "Overlays" to "மேலடுக்குகள்",
        "Transitions" to "மாற்றங்கள்",
        "AI Background" to "செயற்கை நுண்ணறிவு பின்னணி",
        "Edit Subtitle Text" to "வசன உரையைத் திருத்து",
        "Split Clip" to "கிளிப்பை பிரி",
        "Add Sticker" to "ஸ்டிக்கர் சேர்",
        "Rendering Final Output File" to "இறுதி வெளியீட்டு கோப்பு உருவாக்கப்படுகிறது",
        "Multiplexing tracks, speech frames & LUTs..." to "ஒலி மற்றும் விளைவுகள் சேகரிக்கப்படுகின்றன...",
        "Seconds" to "வினாடிகள்",
        "s" to "விநாடி"
    )

    private val TELUGU_MAP = mapOf(
        "Yashora" to "యశోర",
        "REEL GENERATOR" to "రీల్ జనరేటర్",
        "Configure Reel Pipeline" to "రీల్ పైప్‌లైన్‌ను కాన్ఫిగర్ చేయండి",
        "Write / Paste Reel Script" to "రీల్ స్క్రిప్ట్ రాయండి / పేస్ట్ చేయండి",
        "Enter or paste your script here. The AI will segment it into scenes, narrate compiling voices, and generate visual prompts automatically..." to "మీ స్క్రిప్ట్‌ను ఇక్కడ నమోదు చేయండి లేదా పేస్ట్ చేయండి. ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ దీనిని దృశ్యాలుగా విభజించి, నేరేట్ చేస్తుంది...",
        "Select Video Narration Style" to "వీడియో కథన శైలిని ఎంచుకోండి",
        "Warm storybook textures and soft focuses" to "వెచ్చని కథ పుస్తక నిర్మాణాలు మరియు మృదువైన ఫోకస్",
        "Speech & Video Language" to "భాష మరియు వీడియో భాష",
        "This controls the spoken accents & subtitles" to "ఇది మాట్లాడే శైలిని మరియు ఉపశీర్షికలను నియంత్రిస్తుంది",
        "Primary Narrator Voice" to "ప్రాథమిక కథకుడి వాయిస్",
        "Selected: " to "ఎంచుకోబడింది: ",
        "Male" to "పురుషుడు",
        "Female" to "స్త్రీ",
        "Child" to "పిల్లవాడు",
        "Speech Speed: " to "వేగం: ",
        "Speech Pitch: " to "పిచ్: ",
        "Preview Voice Synths" to "వాయిస్ ప్రివ్యూ వినండి",
        "Select Aspect Ratio" to "ఆస్పెక్ట్ రేషియోని ఎంచుకోండి",
        "Select Output Settings" to "అవుట్‌పుట్ సెట్టింగ్‌లు ఎంచుకోండి",
        "Resolution" to "రిజల్యూషన్",
        "Video Framerate" to "వీడియో ఫ్రేమ్‌రేట్",
        "Background Soundtrack Overlay" to "నేపథ్య సౌండ్‌ట్రాక్ ఓవర్‌లే",
        "Add smart rhythmic backing beats" to "స్మార్ట్ బ్యాక్‌గ్రౌండ్ బీట్స్ జోడించండి",
        "Music Level: " to "సంగీతం స్థాయి: ",
        "Voice Level: " to "వాయిస్ స్థాయి: ",
        "Generate Video" to "వీడియోని సృష్టించండి",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "స్క్రిప్ట్‌లను తక్షణమే అనుకూల న్యూరల్ మోడల్‌లతో గొప్ప దృశ్య రూపాల్లోకి మార్చండి.",
        "Create Reel" to "రీల్ సృష్టించండి",
        "AI Reel Architect" to "ఐ రీల్ ఆర్కిటెక్ట్",
        "Recent Projects" to "ఇటీవలి ప్రాజెక్ట్‌లు",
        "Export History" to "ఎగుమతి చరిత్ర",
        "No Project Drafts Found" to "ఎటువంటి ప్రాజెక్ట్ డ్రాఫ్ట్‌లు లేవు",
        "Click 'Create Reel' at the bottom right corner to start breaking down scripts" to "స్క్రిప్ట్‌లను ప్రారంభించడానికి కుడి దిగువ మూలలో ఉన్న 'రీల్ సృష్టించండి' పై క్లిక్ చేయండి",
        "No Rendered History" to "రెండర్ చేయబడిన చరిత్ర లేదు",
        "Once you configure storyboards and export them, generated MP4 entries will persist here" to "మీరు స్టోరీబోర్డ్‌లను కాన్గర్ చేసి ఎగుమతి చేసిన తర్వాత, సృష్టించబడిన MP4లు ఇక్కడ కనిపిస్తాయి",
        "Delete Project draft?" to "ప్రాజెక్ట్ డ్రాఫ్ట్ తొలగించాలా?",
        "Are you sure you want to delete" to "మీరు ఖచ్చితంగా తొలగించాలనుకుంటున్నారా",
        "permanently? This action cannot be undone." to "शाश्वत रूप से? ఈ చర్యను తిరిగి మార్చలేము.",
        "Delete" to "తొలగించు",
        "Cancel" to "రద్దు చేయి",
        "Remove Export Entry?" to "ఎగుమతి లాగ్ తొలగించాలా?",
        "This will delete the history log for" to "ఇది చరిత్ర లాగ్‌ను తొలగిస్తుంది",
        "It does not delete physical MP4 off device storage." to "ఇది డివైజ్ స్టోరేజ్ నుండి అసలు MP4 ఫైల్‌ను తొలగించదు.",
        "Remove" to "తొలగించు",
        "App Settings" to "యాప్ సెట్టింగ్‌లు",
        "Back" to "వెనుకకు",
        "Preferences" to "ప్రాధాన్యతలు",
        "Settings" to "సెట్టింగులు",
        "App Theme" to "యాప్ థీమ్",
        "App Interface Language" to "యాప్ ఇంటర్‌ఫేస్ భాష",
        "AI Video Generation Language" to "వీడియో జనరేషన్ భాష",
        "Legal & About" to "లీగல் & సమాచారం",
        "Privacy Policy" to "గోప్యతా విధానం",
        "How we protect, save and manage your credentials" to "మీ రుజువులను మేము ఎలా రక్షిస్తాము",
        "Terms & Conditions" to "నిబంధనలు & షരతులు",
        "Agreement governing AI reel pipeline software usage" to "సాఫ్ట్‌వేర్ వినియోగ ఒప్పందం",
        "About Yashora Reel Generator" to "యశోర రీల్ జనరేటర్ గురించి",
        "App version, framework and technologies used" to "యాప్ వెర్షన్, ఉపయోగించిన సాంకేతికతలు",
        "YASHORA TECHNOLOGIES" to "యశోర టెక్నాలジーస్",
        "Version 1.0.4 (Production Ready)" to "వెర్షన్ 1.0.4 (సిద్ధంగా ఉంది)",
        "Select Theme Selection" to "థీమ్ ఎంచుకోండి",
        "Select Language" to "భాషను ఎంచుకోండి",
        "English" to "ఆంగ్లం",
        "Hindi" to "హిందీ",
        "Arabic" to "అరబిక్",
        "Urdu" to "ఉర్దూ",
        "Bengali" to "బెంగాలీ",
        "Tamil" to "తమిళం",
        "Telugu" to "తెలుగు",
        "Japanese" to "జపనీస్",
        "Chinese" to "చైనీస్",
        "Korean" to "కొరియన్",
        "German" to "జర్మన్",
        "French" to "ఫ్రెంచ్",
        "Spanish" to "స్పానిష్",
        "Portuguese" to "పోర్చుగీస్",
        "Russian" to "రష్యన్",
        "Turkish" to "టర్కిష్",
        "Visual Timeline Editor" to "విజువల్ కాలక్రమ సంపాదకుడు",
        "Export" to "ఎగుమతి",
        "Empty Track Buffer" to "ట్రాక్‌లు ఖాళీగా ఉన్నాయి",
        "Preview Voice" to "వాయిస్ ప్రివ్యూ",
        "Chronological Video Track Timeline" to "కాలక్రమ వీడియో ట్రాక్",
        "Add Clip" to "క్లిప్ జోడించండి",
        "Subtitles" to "ఉపశీర్షికలు",
        "50+ Filters" to "50+ ఫిల్టర్లు",
        "Overlays" to "ఓవర్‌లేస్",
        "Transitions" to "ట్రాన్సిషన్స్",
        "AI Background" to "AI నేపథ్యం",
        "Edit Subtitle Text" to "ఉపశీర్షిక సవరించండి",
        "Split Clip" to "క్లిప్ విభజించు",
        "Add Sticker" to "స్టిక్కర్ జోడించు",
        "Rendering Final Output File" to "తుది ఫైల్ రెండర్ చేయబడుతోంది",
        "Multiplexing tracks, speech frames & LUTs..." to "సంగీతం మరియు వీడియో కలపబడుతోంది...",
        "Seconds" to "సెకన్లు",
        "s" to "సె."
    )

    private val KOREAN_MAP = mapOf(
        "Yashora" to "야쇼라",
        "REEL GENERATOR" to "릴 제네레이터",
        "Configure Reel Pipeline" to "릴 파이프라인 구성",
        "Write / Paste Reel Script" to "릴 스크립트 작성 / 붙여넣기",
        "Enter or paste your script here. The AI will segment it into scenes, narrate compiling voices, and generate visual prompts automatically..." to "여기에 스크립트를 입력하거나 붙여넣으세요. AI가 장별로 장면을 분류하고 음성 가이드를 구성하며 자동 비주얼 프롬프트를 만듭니다...",
        "Select Video Narration Style" to "비디오 내레이션 스타일 선택",
        "Warm storybook textures and soft focuses" to "따뜻한 스토리북 질감과 부드러운 포커스",
        "Speech & Video Language" to "음성 및 비디오 언어",
        "This controls the spoken accents & subtitles" to "발음 스타일 및 자막 언어 속성을 정의합니다",
        "Primary Narrator Voice" to "기본 성우 내레이터 음성",
        "Selected: " to "선택됨: ",
        "Male" to "남성",
        "Female" to "여성",
        "Child" to "어린이",
        "Speech Speed: " to "음성 속도: ",
        "Speech Pitch: " to "음성 피치: ",
        "Preview Voice Synths" to "목소리 미리 듣기",
        "Select Aspect Ratio" to "화면 비율 선택",
        "Select Output Settings" to "출력 속성 설정",
        "Resolution" to "해상도",
        "Video Framerate" to "비디오 프레임 레이트",
        "Background Soundtrack Overlay" to "배경 음악 오버레이",
        "Add smart rhythmic backing beats" to "지능형 리듬 배경 비트 사운드 추가",
        "Music Level: " to "배경음 볼륨: ",
        "Voice Level: " to "목소리 볼륨: ",
        "Generate Video" to "비디오 출력물 생성",
        "Convert scripts into rich visual storyboards with custom neural models instantly." to "스크립트를 즉시 자체 인공 신경망 모델 기반의 풍부한 시각적 스토리보드로 변환합니다.",
        "Create Reel" to "릴 만들기",
        "AI Reel Architect" to "AI 릴 아키텍트",
        "Recent Projects" to "최근 프로젝트",
        "Export History" to "내보내기 기록",
        "No Project Drafts Found" to "저장된 프로젝트 임시 보관함이 없습니다",
        "Click 'Create Reel' at the bottom right corner to start breaking down scripts" to "스크립트 분류를 시작하시려면 우측 하단의 '릴 만들기' 버튼을 누르세요",
        "No Rendered History" to "내보낸 영상 내역이 없습니다",
        "Once you configure storyboards and export them, generated MP4 entries will persist here" to "스토리보드를 구성하고 출력하신 후, 생성 완료된 MP4 목록이 여기에 표시됩니다",
        "Delete Project draft?" to "프로젝트 보관함을 삭제하시겠습니까?",
        "Are you sure you want to delete" to "정말로 삭제하시겠습니까",
        "permanently? This action cannot be undone." to "영구 삭제됩니다. 이 동작은 취소할 수 없습니다.",
        "Delete" to "삭제",
        "Cancel" to "취소",
        "Remove Export Entry?" to "내보내기 내역을 삭제하시겠습니까?",
        "This will delete the history log for" to "다음 내역의 로그를 삭제합니다",
        "It does not delete physical MP4 off device storage." to "이 동작은 기기 저장소의 원래 MP4 파일 자체를 삭제하지는 않습니다.",
        "Remove" to "삭제",
        "App Settings" to "앱 환경 설정",
        "Back" to "뒤로가기",
        "Preferences" to "사용 성향",
        "Settings" to "설정",
        "App Theme" to "앱 테마 설정",
        "App Interface Language" to "앱 언어 설정",
        "AI Video Generation Language" to "인공지능 비디오 생성 언어",
        "Legal & About" to "법적 고지 및 정보",
        "Privacy Policy" to "개인정보 처리방침",
        "How we protect, save and manage your credentials" to "사용자 개인 정보를 안전하게 저장하고 관리하는 법",
        "Terms & Conditions" to "서비스 이용 약관",
        "Agreement governing AI reel pipeline software usage" to "인공지능 영상 관련 소프트웨어 이용 정책 서약",
        "About Yashora Reel Generator" to "야쇼라 릴 제네레이터 회사 소개",
        "App version, framework and technologies used" to "애플리케이션 버전 정보, 사용된 프레임워크 기술",
        "YASHORA TECHNOLOGIES" to "야쇼라 테크놀로지스",
        "Version 1.0.4 (Production Ready)" to "버전 1.0.4 (상용 버젼)",
        "Select Theme Selection" to "테마 옵션 선택",
        "Select Language" to "언어 옵션 선택",
        "English" to "영어",
        "Hindi" to "힌디어",
        "Arabic" to "아랍어",
        "Urdu" to "우르두어",
        "Bengali" to "뱅골어",
        "Tamil" to "타밀어",
        "Telugu" to "텔루구어",
        "Japanese" to "일본어",
        "Chinese" to "중국어",
        "Korean" to "한국어",
        "German" to "독일어",
        "French" to "프랑스어",
        "Spanish" to "스페인어",
        "Portuguese" to "포르투갈어",
        "Russian" to "러시아어",
        "Turkish" to "터키어",
        "Visual Timeline Editor" to "비디오 조각 편집 타임라인",
        "Export" to "내보내기",
        "Empty Track Buffer" to "비디오 트랙이 비어있음",
        "Preview Voice" to "샘플 목소리 듣기",
        "Chronological Video Track Timeline" to "시간순 비디오 조각 타임라인 흐름",
        "Add Clip" to "비디오 조각 추가",
        "Subtitles" to "자막 설정",
        "50+ Filters" to "50종 이상 인쇄용 필터 LUT",
        "Overlays" to "화면 오버레이",
        "Transitions" to "장면 전환 효과",
        "AI Background" to "인공지능 제작 배경",
        "Edit Subtitle Text" to "자막 내용 직접 수정",
        "Split Clip" to "영상 잘라내어 분할",
        "Add Sticker" to "스티커 아이콘 삽입",
        "Rendering Final Output File" to "최종 비디오 인코딩 처리 중",
        "Multiplexing tracks, speech frames & LUTs..." to "비디오 해상도 채널과 오디오 소스 병합 처리 중...",
        "Seconds" to "초",
        "s" to "초"
    )

    private val TRAN_LANG_MAPS = mapOf(
        "Hindi" to HINDI_MAP,
        "Spanish" to SPANISH_MAP,
        "French" to FRENCH_MAP,
        "German" to GERMAN_MAP,
        "Arabic" to ARABIC_MAP,
        "Chinese" to CHINESE_MAP,
        "Japanese" to JAPANESE_MAP,
        "Portuguese" to PORTUGUESE_MAP,
        "Russian" to RUSSIAN_MAP,
        "Turkish" to TURKISH_MAP,
        "Urdu" to URDU_MAP,
        "Bengali" to BENGALI_MAP,
        "Tamil" to TAMIL_MAP,
        "Telugu" to TELUGU_MAP,
        "Korean" to KOREAN_MAP
    )

    fun translate(englishText: String, targetLanguage: String): String {
        val selectedMap = TRAN_LANG_MAPS[targetLanguage] ?: return englishText
        
        // Fast unique lookup
        selectedMap[englishText]?.let { return it }
        
        // Substring search / partial translation for items that are built dynamically (e.g., "Selected: Male", "Speech Speed: 1.0x", etc.)
        for ((key, value) in selectedMap) {
            if (englishText.startsWith(key)) {
                val remaining = englishText.substring(key.length)
                // If remaining is just a name or format value, translate key and append remaining
                val remainingTranslated = when (remaining.trim()) {
                    "Male" -> selectedMap["Male"] ?: "Male"
                    "Female" -> selectedMap["Female"] ?: "Female"
                    "Child" -> selectedMap["Child"] ?: "Child"
                    else -> remaining
                }
                return value + remainingTranslated
            }
        }
        return englishText
    }
}

/**
 * Extension function on String to comfortably translate/localize UI texts inline.
 */
fun String.localize(languageState: String): String {
    return Localization.translate(this, languageState)
}
